package cn.com.chinatelecom.pms.pojo;

import java.util.ArrayList;
import java.util.List;

public class AdminExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ADMIN
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ADMIN
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ADMIN
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN
     *
     * @mbggenerated
     */
    public AdminExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ADMIN
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUseridIsNull() {
            addCriterion("USERID is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("USERID is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("USERID =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("USERID <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("USERID >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("USERID >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("USERID <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("USERID <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("USERID like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("USERID not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("USERID in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("USERID not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("USERID between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("USERID not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("USERNAME is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("USERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("USERNAME =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("USERNAME <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("USERNAME >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("USERNAME >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("USERNAME <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("USERNAME <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("USERNAME like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("USERNAME not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("USERNAME in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("USERNAME not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("USERNAME between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("USERNAME not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsertypeIsNull() {
            addCriterion("USERTYPE is null");
            return (Criteria) this;
        }

        public Criteria andUsertypeIsNotNull() {
            addCriterion("USERTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andUsertypeEqualTo(String value) {
            addCriterion("USERTYPE =", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeNotEqualTo(String value) {
            addCriterion("USERTYPE <>", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeGreaterThan(String value) {
            addCriterion("USERTYPE >", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeGreaterThanOrEqualTo(String value) {
            addCriterion("USERTYPE >=", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeLessThan(String value) {
            addCriterion("USERTYPE <", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeLessThanOrEqualTo(String value) {
            addCriterion("USERTYPE <=", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeLike(String value) {
            addCriterion("USERTYPE like", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeNotLike(String value) {
            addCriterion("USERTYPE not like", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeIn(List<String> values) {
            addCriterion("USERTYPE in", values, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeNotIn(List<String> values) {
            addCriterion("USERTYPE not in", values, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeBetween(String value1, String value2) {
            addCriterion("USERTYPE between", value1, value2, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeNotBetween(String value1, String value2) {
            addCriterion("USERTYPE not between", value1, value2, "usertype");
            return (Criteria) this;
        }

        public Criteria andUseremailIsNull() {
            addCriterion("USEREMAIL is null");
            return (Criteria) this;
        }

        public Criteria andUseremailIsNotNull() {
            addCriterion("USEREMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andUseremailEqualTo(String value) {
            addCriterion("USEREMAIL =", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailNotEqualTo(String value) {
            addCriterion("USEREMAIL <>", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailGreaterThan(String value) {
            addCriterion("USEREMAIL >", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailGreaterThanOrEqualTo(String value) {
            addCriterion("USEREMAIL >=", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailLessThan(String value) {
            addCriterion("USEREMAIL <", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailLessThanOrEqualTo(String value) {
            addCriterion("USEREMAIL <=", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailLike(String value) {
            addCriterion("USEREMAIL like", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailNotLike(String value) {
            addCriterion("USEREMAIL not like", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailIn(List<String> values) {
            addCriterion("USEREMAIL in", values, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailNotIn(List<String> values) {
            addCriterion("USEREMAIL not in", values, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailBetween(String value1, String value2) {
            addCriterion("USEREMAIL between", value1, value2, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailNotBetween(String value1, String value2) {
            addCriterion("USEREMAIL not between", value1, value2, "useremail");
            return (Criteria) this;
        }

        public Criteria andMobilenumIsNull() {
            addCriterion("MOBILENUM is null");
            return (Criteria) this;
        }

        public Criteria andMobilenumIsNotNull() {
            addCriterion("MOBILENUM is not null");
            return (Criteria) this;
        }

        public Criteria andMobilenumEqualTo(String value) {
            addCriterion("MOBILENUM =", value, "mobilenum");
            return (Criteria) this;
        }

        public Criteria andMobilenumNotEqualTo(String value) {
            addCriterion("MOBILENUM <>", value, "mobilenum");
            return (Criteria) this;
        }

        public Criteria andMobilenumGreaterThan(String value) {
            addCriterion("MOBILENUM >", value, "mobilenum");
            return (Criteria) this;
        }

        public Criteria andMobilenumGreaterThanOrEqualTo(String value) {
            addCriterion("MOBILENUM >=", value, "mobilenum");
            return (Criteria) this;
        }

        public Criteria andMobilenumLessThan(String value) {
            addCriterion("MOBILENUM <", value, "mobilenum");
            return (Criteria) this;
        }

        public Criteria andMobilenumLessThanOrEqualTo(String value) {
            addCriterion("MOBILENUM <=", value, "mobilenum");
            return (Criteria) this;
        }

        public Criteria andMobilenumLike(String value) {
            addCriterion("MOBILENUM like", value, "mobilenum");
            return (Criteria) this;
        }

        public Criteria andMobilenumNotLike(String value) {
            addCriterion("MOBILENUM not like", value, "mobilenum");
            return (Criteria) this;
        }

        public Criteria andMobilenumIn(List<String> values) {
            addCriterion("MOBILENUM in", values, "mobilenum");
            return (Criteria) this;
        }

        public Criteria andMobilenumNotIn(List<String> values) {
            addCriterion("MOBILENUM not in", values, "mobilenum");
            return (Criteria) this;
        }

        public Criteria andMobilenumBetween(String value1, String value2) {
            addCriterion("MOBILENUM between", value1, value2, "mobilenum");
            return (Criteria) this;
        }

        public Criteria andMobilenumNotBetween(String value1, String value2) {
            addCriterion("MOBILENUM not between", value1, value2, "mobilenum");
            return (Criteria) this;
        }

        public Criteria andTelnumIsNull() {
            addCriterion("TELNUM is null");
            return (Criteria) this;
        }

        public Criteria andTelnumIsNotNull() {
            addCriterion("TELNUM is not null");
            return (Criteria) this;
        }

        public Criteria andTelnumEqualTo(String value) {
            addCriterion("TELNUM =", value, "telnum");
            return (Criteria) this;
        }

        public Criteria andTelnumNotEqualTo(String value) {
            addCriterion("TELNUM <>", value, "telnum");
            return (Criteria) this;
        }

        public Criteria andTelnumGreaterThan(String value) {
            addCriterion("TELNUM >", value, "telnum");
            return (Criteria) this;
        }

        public Criteria andTelnumGreaterThanOrEqualTo(String value) {
            addCriterion("TELNUM >=", value, "telnum");
            return (Criteria) this;
        }

        public Criteria andTelnumLessThan(String value) {
            addCriterion("TELNUM <", value, "telnum");
            return (Criteria) this;
        }

        public Criteria andTelnumLessThanOrEqualTo(String value) {
            addCriterion("TELNUM <=", value, "telnum");
            return (Criteria) this;
        }

        public Criteria andTelnumLike(String value) {
            addCriterion("TELNUM like", value, "telnum");
            return (Criteria) this;
        }

        public Criteria andTelnumNotLike(String value) {
            addCriterion("TELNUM not like", value, "telnum");
            return (Criteria) this;
        }

        public Criteria andTelnumIn(List<String> values) {
            addCriterion("TELNUM in", values, "telnum");
            return (Criteria) this;
        }

        public Criteria andTelnumNotIn(List<String> values) {
            addCriterion("TELNUM not in", values, "telnum");
            return (Criteria) this;
        }

        public Criteria andTelnumBetween(String value1, String value2) {
            addCriterion("TELNUM between", value1, value2, "telnum");
            return (Criteria) this;
        }

        public Criteria andTelnumNotBetween(String value1, String value2) {
            addCriterion("TELNUM not between", value1, value2, "telnum");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNull() {
            addCriterion("NICKNAME is null");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNotNull() {
            addCriterion("NICKNAME is not null");
            return (Criteria) this;
        }

        public Criteria andNicknameEqualTo(String value) {
            addCriterion("NICKNAME =", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotEqualTo(String value) {
            addCriterion("NICKNAME <>", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThan(String value) {
            addCriterion("NICKNAME >", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("NICKNAME >=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThan(String value) {
            addCriterion("NICKNAME <", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThanOrEqualTo(String value) {
            addCriterion("NICKNAME <=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLike(String value) {
            addCriterion("NICKNAME like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotLike(String value) {
            addCriterion("NICKNAME not like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameIn(List<String> values) {
            addCriterion("NICKNAME in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotIn(List<String> values) {
            addCriterion("NICKNAME not in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameBetween(String value1, String value2) {
            addCriterion("NICKNAME between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotBetween(String value1, String value2) {
            addCriterion("NICKNAME not between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andRealnameIsNull() {
            addCriterion("REALNAME is null");
            return (Criteria) this;
        }

        public Criteria andRealnameIsNotNull() {
            addCriterion("REALNAME is not null");
            return (Criteria) this;
        }

        public Criteria andRealnameEqualTo(String value) {
            addCriterion("REALNAME =", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotEqualTo(String value) {
            addCriterion("REALNAME <>", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameGreaterThan(String value) {
            addCriterion("REALNAME >", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameGreaterThanOrEqualTo(String value) {
            addCriterion("REALNAME >=", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLessThan(String value) {
            addCriterion("REALNAME <", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLessThanOrEqualTo(String value) {
            addCriterion("REALNAME <=", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLike(String value) {
            addCriterion("REALNAME like", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotLike(String value) {
            addCriterion("REALNAME not like", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameIn(List<String> values) {
            addCriterion("REALNAME in", values, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotIn(List<String> values) {
            addCriterion("REALNAME not in", values, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameBetween(String value1, String value2) {
            addCriterion("REALNAME between", value1, value2, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotBetween(String value1, String value2) {
            addCriterion("REALNAME not between", value1, value2, "realname");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("SEX is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("SEX is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("SEX =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("SEX <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("SEX >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("SEX >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("SEX <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("SEX <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("SEX like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("SEX not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("SEX in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("SEX not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("SEX between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("SEX not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("AGE is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("AGE is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Short value) {
            addCriterion("AGE =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Short value) {
            addCriterion("AGE <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Short value) {
            addCriterion("AGE >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Short value) {
            addCriterion("AGE >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Short value) {
            addCriterion("AGE <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Short value) {
            addCriterion("AGE <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Short> values) {
            addCriterion("AGE in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Short> values) {
            addCriterion("AGE not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Short value1, Short value2) {
            addCriterion("AGE between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Short value1, Short value2) {
            addCriterion("AGE not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andCardtypeIsNull() {
            addCriterion("CARDTYPE is null");
            return (Criteria) this;
        }

        public Criteria andCardtypeIsNotNull() {
            addCriterion("CARDTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCardtypeEqualTo(String value) {
            addCriterion("CARDTYPE =", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeNotEqualTo(String value) {
            addCriterion("CARDTYPE <>", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeGreaterThan(String value) {
            addCriterion("CARDTYPE >", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeGreaterThanOrEqualTo(String value) {
            addCriterion("CARDTYPE >=", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeLessThan(String value) {
            addCriterion("CARDTYPE <", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeLessThanOrEqualTo(String value) {
            addCriterion("CARDTYPE <=", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeLike(String value) {
            addCriterion("CARDTYPE like", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeNotLike(String value) {
            addCriterion("CARDTYPE not like", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeIn(List<String> values) {
            addCriterion("CARDTYPE in", values, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeNotIn(List<String> values) {
            addCriterion("CARDTYPE not in", values, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeBetween(String value1, String value2) {
            addCriterion("CARDTYPE between", value1, value2, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeNotBetween(String value1, String value2) {
            addCriterion("CARDTYPE not between", value1, value2, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardnumIsNull() {
            addCriterion("CARDNUM is null");
            return (Criteria) this;
        }

        public Criteria andCardnumIsNotNull() {
            addCriterion("CARDNUM is not null");
            return (Criteria) this;
        }

        public Criteria andCardnumEqualTo(String value) {
            addCriterion("CARDNUM =", value, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumNotEqualTo(String value) {
            addCriterion("CARDNUM <>", value, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumGreaterThan(String value) {
            addCriterion("CARDNUM >", value, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumGreaterThanOrEqualTo(String value) {
            addCriterion("CARDNUM >=", value, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumLessThan(String value) {
            addCriterion("CARDNUM <", value, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumLessThanOrEqualTo(String value) {
            addCriterion("CARDNUM <=", value, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumLike(String value) {
            addCriterion("CARDNUM like", value, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumNotLike(String value) {
            addCriterion("CARDNUM not like", value, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumIn(List<String> values) {
            addCriterion("CARDNUM in", values, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumNotIn(List<String> values) {
            addCriterion("CARDNUM not in", values, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumBetween(String value1, String value2) {
            addCriterion("CARDNUM between", value1, value2, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumNotBetween(String value1, String value2) {
            addCriterion("CARDNUM not between", value1, value2, "cardnum");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("PROVINCE is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("PROVINCE is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("PROVINCE =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("PROVINCE <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("PROVINCE >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("PROVINCE >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("PROVINCE <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("PROVINCE <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("PROVINCE like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("PROVINCE not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("PROVINCE in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("PROVINCE not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("PROVINCE between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("PROVINCE not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("CITY is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("CITY is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("CITY =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("CITY <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("CITY >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("CITY >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("CITY <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("CITY <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("CITY like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("CITY not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("CITY in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("CITY not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("CITY between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("CITY not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCountyIsNull() {
            addCriterion("COUNTY is null");
            return (Criteria) this;
        }

        public Criteria andCountyIsNotNull() {
            addCriterion("COUNTY is not null");
            return (Criteria) this;
        }

        public Criteria andCountyEqualTo(String value) {
            addCriterion("COUNTY =", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyNotEqualTo(String value) {
            addCriterion("COUNTY <>", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyGreaterThan(String value) {
            addCriterion("COUNTY >", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyGreaterThanOrEqualTo(String value) {
            addCriterion("COUNTY >=", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyLessThan(String value) {
            addCriterion("COUNTY <", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyLessThanOrEqualTo(String value) {
            addCriterion("COUNTY <=", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyLike(String value) {
            addCriterion("COUNTY like", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyNotLike(String value) {
            addCriterion("COUNTY not like", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyIn(List<String> values) {
            addCriterion("COUNTY in", values, "county");
            return (Criteria) this;
        }

        public Criteria andCountyNotIn(List<String> values) {
            addCriterion("COUNTY not in", values, "county");
            return (Criteria) this;
        }

        public Criteria andCountyBetween(String value1, String value2) {
            addCriterion("COUNTY between", value1, value2, "county");
            return (Criteria) this;
        }

        public Criteria andCountyNotBetween(String value1, String value2) {
            addCriterion("COUNTY not between", value1, value2, "county");
            return (Criteria) this;
        }

        public Criteria andPostcodeIsNull() {
            addCriterion("POSTCODE is null");
            return (Criteria) this;
        }

        public Criteria andPostcodeIsNotNull() {
            addCriterion("POSTCODE is not null");
            return (Criteria) this;
        }

        public Criteria andPostcodeEqualTo(String value) {
            addCriterion("POSTCODE =", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeNotEqualTo(String value) {
            addCriterion("POSTCODE <>", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeGreaterThan(String value) {
            addCriterion("POSTCODE >", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeGreaterThanOrEqualTo(String value) {
            addCriterion("POSTCODE >=", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeLessThan(String value) {
            addCriterion("POSTCODE <", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeLessThanOrEqualTo(String value) {
            addCriterion("POSTCODE <=", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeLike(String value) {
            addCriterion("POSTCODE like", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeNotLike(String value) {
            addCriterion("POSTCODE not like", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeIn(List<String> values) {
            addCriterion("POSTCODE in", values, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeNotIn(List<String> values) {
            addCriterion("POSTCODE not in", values, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeBetween(String value1, String value2) {
            addCriterion("POSTCODE between", value1, value2, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeNotBetween(String value1, String value2) {
            addCriterion("POSTCODE not between", value1, value2, "postcode");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("ADDRESS =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("ADDRESS <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("ADDRESS >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("ADDRESS <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("ADDRESS like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("ADDRESS not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("ADDRESS in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("ADDRESS not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("ADDRESS between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("ADDRESS not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andRegtimeIsNull() {
            addCriterion("REGTIME is null");
            return (Criteria) this;
        }

        public Criteria andRegtimeIsNotNull() {
            addCriterion("REGTIME is not null");
            return (Criteria) this;
        }

        public Criteria andRegtimeEqualTo(Object value) {
            addCriterion("REGTIME =", value, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeNotEqualTo(Object value) {
            addCriterion("REGTIME <>", value, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeGreaterThan(Object value) {
            addCriterion("REGTIME >", value, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeGreaterThanOrEqualTo(Object value) {
            addCriterion("REGTIME >=", value, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeLessThan(Object value) {
            addCriterion("REGTIME <", value, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeLessThanOrEqualTo(Object value) {
            addCriterion("REGTIME <=", value, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeIn(List<Object> values) {
            addCriterion("REGTIME in", values, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeNotIn(List<Object> values) {
            addCriterion("REGTIME not in", values, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeBetween(Object value1, Object value2) {
            addCriterion("REGTIME between", value1, value2, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeNotBetween(Object value1, Object value2) {
            addCriterion("REGTIME not between", value1, value2, "regtime");
            return (Criteria) this;
        }

        public Criteria andWorkunitIsNull() {
            addCriterion("WORKUNIT is null");
            return (Criteria) this;
        }

        public Criteria andWorkunitIsNotNull() {
            addCriterion("WORKUNIT is not null");
            return (Criteria) this;
        }

        public Criteria andWorkunitEqualTo(String value) {
            addCriterion("WORKUNIT =", value, "workunit");
            return (Criteria) this;
        }

        public Criteria andWorkunitNotEqualTo(String value) {
            addCriterion("WORKUNIT <>", value, "workunit");
            return (Criteria) this;
        }

        public Criteria andWorkunitGreaterThan(String value) {
            addCriterion("WORKUNIT >", value, "workunit");
            return (Criteria) this;
        }

        public Criteria andWorkunitGreaterThanOrEqualTo(String value) {
            addCriterion("WORKUNIT >=", value, "workunit");
            return (Criteria) this;
        }

        public Criteria andWorkunitLessThan(String value) {
            addCriterion("WORKUNIT <", value, "workunit");
            return (Criteria) this;
        }

        public Criteria andWorkunitLessThanOrEqualTo(String value) {
            addCriterion("WORKUNIT <=", value, "workunit");
            return (Criteria) this;
        }

        public Criteria andWorkunitLike(String value) {
            addCriterion("WORKUNIT like", value, "workunit");
            return (Criteria) this;
        }

        public Criteria andWorkunitNotLike(String value) {
            addCriterion("WORKUNIT not like", value, "workunit");
            return (Criteria) this;
        }

        public Criteria andWorkunitIn(List<String> values) {
            addCriterion("WORKUNIT in", values, "workunit");
            return (Criteria) this;
        }

        public Criteria andWorkunitNotIn(List<String> values) {
            addCriterion("WORKUNIT not in", values, "workunit");
            return (Criteria) this;
        }

        public Criteria andWorkunitBetween(String value1, String value2) {
            addCriterion("WORKUNIT between", value1, value2, "workunit");
            return (Criteria) this;
        }

        public Criteria andWorkunitNotBetween(String value1, String value2) {
            addCriterion("WORKUNIT not between", value1, value2, "workunit");
            return (Criteria) this;
        }

        public Criteria andJobIsNull() {
            addCriterion("JOB is null");
            return (Criteria) this;
        }

        public Criteria andJobIsNotNull() {
            addCriterion("JOB is not null");
            return (Criteria) this;
        }

        public Criteria andJobEqualTo(String value) {
            addCriterion("JOB =", value, "job");
            return (Criteria) this;
        }

        public Criteria andJobNotEqualTo(String value) {
            addCriterion("JOB <>", value, "job");
            return (Criteria) this;
        }

        public Criteria andJobGreaterThan(String value) {
            addCriterion("JOB >", value, "job");
            return (Criteria) this;
        }

        public Criteria andJobGreaterThanOrEqualTo(String value) {
            addCriterion("JOB >=", value, "job");
            return (Criteria) this;
        }

        public Criteria andJobLessThan(String value) {
            addCriterion("JOB <", value, "job");
            return (Criteria) this;
        }

        public Criteria andJobLessThanOrEqualTo(String value) {
            addCriterion("JOB <=", value, "job");
            return (Criteria) this;
        }

        public Criteria andJobLike(String value) {
            addCriterion("JOB like", value, "job");
            return (Criteria) this;
        }

        public Criteria andJobNotLike(String value) {
            addCriterion("JOB not like", value, "job");
            return (Criteria) this;
        }

        public Criteria andJobIn(List<String> values) {
            addCriterion("JOB in", values, "job");
            return (Criteria) this;
        }

        public Criteria andJobNotIn(List<String> values) {
            addCriterion("JOB not in", values, "job");
            return (Criteria) this;
        }

        public Criteria andJobBetween(String value1, String value2) {
            addCriterion("JOB between", value1, value2, "job");
            return (Criteria) this;
        }

        public Criteria andJobNotBetween(String value1, String value2) {
            addCriterion("JOB not between", value1, value2, "job");
            return (Criteria) this;
        }

        public Criteria andClubCardnoIsNull() {
            addCriterion("CLUB_CARDNO is null");
            return (Criteria) this;
        }

        public Criteria andClubCardnoIsNotNull() {
            addCriterion("CLUB_CARDNO is not null");
            return (Criteria) this;
        }

        public Criteria andClubCardnoEqualTo(String value) {
            addCriterion("CLUB_CARDNO =", value, "clubCardno");
            return (Criteria) this;
        }

        public Criteria andClubCardnoNotEqualTo(String value) {
            addCriterion("CLUB_CARDNO <>", value, "clubCardno");
            return (Criteria) this;
        }

        public Criteria andClubCardnoGreaterThan(String value) {
            addCriterion("CLUB_CARDNO >", value, "clubCardno");
            return (Criteria) this;
        }

        public Criteria andClubCardnoGreaterThanOrEqualTo(String value) {
            addCriterion("CLUB_CARDNO >=", value, "clubCardno");
            return (Criteria) this;
        }

        public Criteria andClubCardnoLessThan(String value) {
            addCriterion("CLUB_CARDNO <", value, "clubCardno");
            return (Criteria) this;
        }

        public Criteria andClubCardnoLessThanOrEqualTo(String value) {
            addCriterion("CLUB_CARDNO <=", value, "clubCardno");
            return (Criteria) this;
        }

        public Criteria andClubCardnoLike(String value) {
            addCriterion("CLUB_CARDNO like", value, "clubCardno");
            return (Criteria) this;
        }

        public Criteria andClubCardnoNotLike(String value) {
            addCriterion("CLUB_CARDNO not like", value, "clubCardno");
            return (Criteria) this;
        }

        public Criteria andClubCardnoIn(List<String> values) {
            addCriterion("CLUB_CARDNO in", values, "clubCardno");
            return (Criteria) this;
        }

        public Criteria andClubCardnoNotIn(List<String> values) {
            addCriterion("CLUB_CARDNO not in", values, "clubCardno");
            return (Criteria) this;
        }

        public Criteria andClubCardnoBetween(String value1, String value2) {
            addCriterion("CLUB_CARDNO between", value1, value2, "clubCardno");
            return (Criteria) this;
        }

        public Criteria andClubCardnoNotBetween(String value1, String value2) {
            addCriterion("CLUB_CARDNO not between", value1, value2, "clubCardno");
            return (Criteria) this;
        }

        public Criteria andIfcontactaccountsIsNull() {
            addCriterion("IFCONTACTACCOUNTS is null");
            return (Criteria) this;
        }

        public Criteria andIfcontactaccountsIsNotNull() {
            addCriterion("IFCONTACTACCOUNTS is not null");
            return (Criteria) this;
        }

        public Criteria andIfcontactaccountsEqualTo(String value) {
            addCriterion("IFCONTACTACCOUNTS =", value, "ifcontactaccounts");
            return (Criteria) this;
        }

        public Criteria andIfcontactaccountsNotEqualTo(String value) {
            addCriterion("IFCONTACTACCOUNTS <>", value, "ifcontactaccounts");
            return (Criteria) this;
        }

        public Criteria andIfcontactaccountsGreaterThan(String value) {
            addCriterion("IFCONTACTACCOUNTS >", value, "ifcontactaccounts");
            return (Criteria) this;
        }

        public Criteria andIfcontactaccountsGreaterThanOrEqualTo(String value) {
            addCriterion("IFCONTACTACCOUNTS >=", value, "ifcontactaccounts");
            return (Criteria) this;
        }

        public Criteria andIfcontactaccountsLessThan(String value) {
            addCriterion("IFCONTACTACCOUNTS <", value, "ifcontactaccounts");
            return (Criteria) this;
        }

        public Criteria andIfcontactaccountsLessThanOrEqualTo(String value) {
            addCriterion("IFCONTACTACCOUNTS <=", value, "ifcontactaccounts");
            return (Criteria) this;
        }

        public Criteria andIfcontactaccountsLike(String value) {
            addCriterion("IFCONTACTACCOUNTS like", value, "ifcontactaccounts");
            return (Criteria) this;
        }

        public Criteria andIfcontactaccountsNotLike(String value) {
            addCriterion("IFCONTACTACCOUNTS not like", value, "ifcontactaccounts");
            return (Criteria) this;
        }

        public Criteria andIfcontactaccountsIn(List<String> values) {
            addCriterion("IFCONTACTACCOUNTS in", values, "ifcontactaccounts");
            return (Criteria) this;
        }

        public Criteria andIfcontactaccountsNotIn(List<String> values) {
            addCriterion("IFCONTACTACCOUNTS not in", values, "ifcontactaccounts");
            return (Criteria) this;
        }

        public Criteria andIfcontactaccountsBetween(String value1, String value2) {
            addCriterion("IFCONTACTACCOUNTS between", value1, value2, "ifcontactaccounts");
            return (Criteria) this;
        }

        public Criteria andIfcontactaccountsNotBetween(String value1, String value2) {
            addCriterion("IFCONTACTACCOUNTS not between", value1, value2, "ifcontactaccounts");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeIsNull() {
            addCriterion("LASTLOGTIME is null");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeIsNotNull() {
            addCriterion("LASTLOGTIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeEqualTo(Object value) {
            addCriterion("LASTLOGTIME =", value, "lastlogtime");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeNotEqualTo(Object value) {
            addCriterion("LASTLOGTIME <>", value, "lastlogtime");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeGreaterThan(Object value) {
            addCriterion("LASTLOGTIME >", value, "lastlogtime");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeGreaterThanOrEqualTo(Object value) {
            addCriterion("LASTLOGTIME >=", value, "lastlogtime");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeLessThan(Object value) {
            addCriterion("LASTLOGTIME <", value, "lastlogtime");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeLessThanOrEqualTo(Object value) {
            addCriterion("LASTLOGTIME <=", value, "lastlogtime");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeIn(List<Object> values) {
            addCriterion("LASTLOGTIME in", values, "lastlogtime");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeNotIn(List<Object> values) {
            addCriterion("LASTLOGTIME not in", values, "lastlogtime");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeBetween(Object value1, Object value2) {
            addCriterion("LASTLOGTIME between", value1, value2, "lastlogtime");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeNotBetween(Object value1, Object value2) {
            addCriterion("LASTLOGTIME not between", value1, value2, "lastlogtime");
            return (Criteria) this;
        }

        public Criteria andExpandIsNull() {
            addCriterion("EXPAND is null");
            return (Criteria) this;
        }

        public Criteria andExpandIsNotNull() {
            addCriterion("EXPAND is not null");
            return (Criteria) this;
        }

        public Criteria andExpandEqualTo(String value) {
            addCriterion("EXPAND =", value, "expand");
            return (Criteria) this;
        }

        public Criteria andExpandNotEqualTo(String value) {
            addCriterion("EXPAND <>", value, "expand");
            return (Criteria) this;
        }

        public Criteria andExpandGreaterThan(String value) {
            addCriterion("EXPAND >", value, "expand");
            return (Criteria) this;
        }

        public Criteria andExpandGreaterThanOrEqualTo(String value) {
            addCriterion("EXPAND >=", value, "expand");
            return (Criteria) this;
        }

        public Criteria andExpandLessThan(String value) {
            addCriterion("EXPAND <", value, "expand");
            return (Criteria) this;
        }

        public Criteria andExpandLessThanOrEqualTo(String value) {
            addCriterion("EXPAND <=", value, "expand");
            return (Criteria) this;
        }

        public Criteria andExpandLike(String value) {
            addCriterion("EXPAND like", value, "expand");
            return (Criteria) this;
        }

        public Criteria andExpandNotLike(String value) {
            addCriterion("EXPAND not like", value, "expand");
            return (Criteria) this;
        }

        public Criteria andExpandIn(List<String> values) {
            addCriterion("EXPAND in", values, "expand");
            return (Criteria) this;
        }

        public Criteria andExpandNotIn(List<String> values) {
            addCriterion("EXPAND not in", values, "expand");
            return (Criteria) this;
        }

        public Criteria andExpandBetween(String value1, String value2) {
            addCriterion("EXPAND between", value1, value2, "expand");
            return (Criteria) this;
        }

        public Criteria andExpandNotBetween(String value1, String value2) {
            addCriterion("EXPAND not between", value1, value2, "expand");
            return (Criteria) this;
        }

        public Criteria andTsGsNmIsNull() {
            addCriterion("TS_GS_NM is null");
            return (Criteria) this;
        }

        public Criteria andTsGsNmIsNotNull() {
            addCriterion("TS_GS_NM is not null");
            return (Criteria) this;
        }

        public Criteria andTsGsNmEqualTo(String value) {
            addCriterion("TS_GS_NM =", value, "tsGsNm");
            return (Criteria) this;
        }

        public Criteria andTsGsNmNotEqualTo(String value) {
            addCriterion("TS_GS_NM <>", value, "tsGsNm");
            return (Criteria) this;
        }

        public Criteria andTsGsNmGreaterThan(String value) {
            addCriterion("TS_GS_NM >", value, "tsGsNm");
            return (Criteria) this;
        }

        public Criteria andTsGsNmGreaterThanOrEqualTo(String value) {
            addCriterion("TS_GS_NM >=", value, "tsGsNm");
            return (Criteria) this;
        }

        public Criteria andTsGsNmLessThan(String value) {
            addCriterion("TS_GS_NM <", value, "tsGsNm");
            return (Criteria) this;
        }

        public Criteria andTsGsNmLessThanOrEqualTo(String value) {
            addCriterion("TS_GS_NM <=", value, "tsGsNm");
            return (Criteria) this;
        }

        public Criteria andTsGsNmLike(String value) {
            addCriterion("TS_GS_NM like", value, "tsGsNm");
            return (Criteria) this;
        }

        public Criteria andTsGsNmNotLike(String value) {
            addCriterion("TS_GS_NM not like", value, "tsGsNm");
            return (Criteria) this;
        }

        public Criteria andTsGsNmIn(List<String> values) {
            addCriterion("TS_GS_NM in", values, "tsGsNm");
            return (Criteria) this;
        }

        public Criteria andTsGsNmNotIn(List<String> values) {
            addCriterion("TS_GS_NM not in", values, "tsGsNm");
            return (Criteria) this;
        }

        public Criteria andTsGsNmBetween(String value1, String value2) {
            addCriterion("TS_GS_NM between", value1, value2, "tsGsNm");
            return (Criteria) this;
        }

        public Criteria andTsGsNmNotBetween(String value1, String value2) {
            addCriterion("TS_GS_NM not between", value1, value2, "tsGsNm");
            return (Criteria) this;
        }

        public Criteria andMailVerifyIsNull() {
            addCriterion("MAIL_VERIFY is null");
            return (Criteria) this;
        }

        public Criteria andMailVerifyIsNotNull() {
            addCriterion("MAIL_VERIFY is not null");
            return (Criteria) this;
        }

        public Criteria andMailVerifyEqualTo(String value) {
            addCriterion("MAIL_VERIFY =", value, "mailVerify");
            return (Criteria) this;
        }

        public Criteria andMailVerifyNotEqualTo(String value) {
            addCriterion("MAIL_VERIFY <>", value, "mailVerify");
            return (Criteria) this;
        }

        public Criteria andMailVerifyGreaterThan(String value) {
            addCriterion("MAIL_VERIFY >", value, "mailVerify");
            return (Criteria) this;
        }

        public Criteria andMailVerifyGreaterThanOrEqualTo(String value) {
            addCriterion("MAIL_VERIFY >=", value, "mailVerify");
            return (Criteria) this;
        }

        public Criteria andMailVerifyLessThan(String value) {
            addCriterion("MAIL_VERIFY <", value, "mailVerify");
            return (Criteria) this;
        }

        public Criteria andMailVerifyLessThanOrEqualTo(String value) {
            addCriterion("MAIL_VERIFY <=", value, "mailVerify");
            return (Criteria) this;
        }

        public Criteria andMailVerifyLike(String value) {
            addCriterion("MAIL_VERIFY like", value, "mailVerify");
            return (Criteria) this;
        }

        public Criteria andMailVerifyNotLike(String value) {
            addCriterion("MAIL_VERIFY not like", value, "mailVerify");
            return (Criteria) this;
        }

        public Criteria andMailVerifyIn(List<String> values) {
            addCriterion("MAIL_VERIFY in", values, "mailVerify");
            return (Criteria) this;
        }

        public Criteria andMailVerifyNotIn(List<String> values) {
            addCriterion("MAIL_VERIFY not in", values, "mailVerify");
            return (Criteria) this;
        }

        public Criteria andMailVerifyBetween(String value1, String value2) {
            addCriterion("MAIL_VERIFY between", value1, value2, "mailVerify");
            return (Criteria) this;
        }

        public Criteria andMailVerifyNotBetween(String value1, String value2) {
            addCriterion("MAIL_VERIFY not between", value1, value2, "mailVerify");
            return (Criteria) this;
        }

        public Criteria andOrderYeIsNull() {
            addCriterion("ORDER_YE is null");
            return (Criteria) this;
        }

        public Criteria andOrderYeIsNotNull() {
            addCriterion("ORDER_YE is not null");
            return (Criteria) this;
        }

        public Criteria andOrderYeEqualTo(String value) {
            addCriterion("ORDER_YE =", value, "orderYe");
            return (Criteria) this;
        }

        public Criteria andOrderYeNotEqualTo(String value) {
            addCriterion("ORDER_YE <>", value, "orderYe");
            return (Criteria) this;
        }

        public Criteria andOrderYeGreaterThan(String value) {
            addCriterion("ORDER_YE >", value, "orderYe");
            return (Criteria) this;
        }

        public Criteria andOrderYeGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_YE >=", value, "orderYe");
            return (Criteria) this;
        }

        public Criteria andOrderYeLessThan(String value) {
            addCriterion("ORDER_YE <", value, "orderYe");
            return (Criteria) this;
        }

        public Criteria andOrderYeLessThanOrEqualTo(String value) {
            addCriterion("ORDER_YE <=", value, "orderYe");
            return (Criteria) this;
        }

        public Criteria andOrderYeLike(String value) {
            addCriterion("ORDER_YE like", value, "orderYe");
            return (Criteria) this;
        }

        public Criteria andOrderYeNotLike(String value) {
            addCriterion("ORDER_YE not like", value, "orderYe");
            return (Criteria) this;
        }

        public Criteria andOrderYeIn(List<String> values) {
            addCriterion("ORDER_YE in", values, "orderYe");
            return (Criteria) this;
        }

        public Criteria andOrderYeNotIn(List<String> values) {
            addCriterion("ORDER_YE not in", values, "orderYe");
            return (Criteria) this;
        }

        public Criteria andOrderYeBetween(String value1, String value2) {
            addCriterion("ORDER_YE between", value1, value2, "orderYe");
            return (Criteria) this;
        }

        public Criteria andOrderYeNotBetween(String value1, String value2) {
            addCriterion("ORDER_YE not between", value1, value2, "orderYe");
            return (Criteria) this;
        }

        public Criteria andTsGsCodeIsNull() {
            addCriterion("TS_GS_CODE is null");
            return (Criteria) this;
        }

        public Criteria andTsGsCodeIsNotNull() {
            addCriterion("TS_GS_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andTsGsCodeEqualTo(String value) {
            addCriterion("TS_GS_CODE =", value, "tsGsCode");
            return (Criteria) this;
        }

        public Criteria andTsGsCodeNotEqualTo(String value) {
            addCriterion("TS_GS_CODE <>", value, "tsGsCode");
            return (Criteria) this;
        }

        public Criteria andTsGsCodeGreaterThan(String value) {
            addCriterion("TS_GS_CODE >", value, "tsGsCode");
            return (Criteria) this;
        }

        public Criteria andTsGsCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TS_GS_CODE >=", value, "tsGsCode");
            return (Criteria) this;
        }

        public Criteria andTsGsCodeLessThan(String value) {
            addCriterion("TS_GS_CODE <", value, "tsGsCode");
            return (Criteria) this;
        }

        public Criteria andTsGsCodeLessThanOrEqualTo(String value) {
            addCriterion("TS_GS_CODE <=", value, "tsGsCode");
            return (Criteria) this;
        }

        public Criteria andTsGsCodeLike(String value) {
            addCriterion("TS_GS_CODE like", value, "tsGsCode");
            return (Criteria) this;
        }

        public Criteria andTsGsCodeNotLike(String value) {
            addCriterion("TS_GS_CODE not like", value, "tsGsCode");
            return (Criteria) this;
        }

        public Criteria andTsGsCodeIn(List<String> values) {
            addCriterion("TS_GS_CODE in", values, "tsGsCode");
            return (Criteria) this;
        }

        public Criteria andTsGsCodeNotIn(List<String> values) {
            addCriterion("TS_GS_CODE not in", values, "tsGsCode");
            return (Criteria) this;
        }

        public Criteria andTsGsCodeBetween(String value1, String value2) {
            addCriterion("TS_GS_CODE between", value1, value2, "tsGsCode");
            return (Criteria) this;
        }

        public Criteria andTsGsCodeNotBetween(String value1, String value2) {
            addCriterion("TS_GS_CODE not between", value1, value2, "tsGsCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ADMIN
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ADMIN
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}