package cn.com.chinatelecom.pms.pojo;

import java.math.BigDecimal;

public class EffectAction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EFFECT_ACTION.EFFECT_ACTION_ID
     *
     * @mbggenerated
     */
    private String effectActionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EFFECT_ACTION.EFFECT_ACTION_CODE
     *
     * @mbggenerated
     */
    private BigDecimal effectActionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EFFECT_ACTION.EFFECT_ACTION_NAME
     *
     * @mbggenerated
     */
    private String effectActionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EFFECT_ACTION.EFFECT_ACTION_DESC
     *
     * @mbggenerated
     */
    private String effectActionDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EFFECT_ACTION.MODULE_ID
     *
     * @mbggenerated
     */
    private String moduleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EFFECT_ACTION.EFFECT_ACTION_ID
     *
     * @return the value of EFFECT_ACTION.EFFECT_ACTION_ID
     *
     * @mbggenerated
     */
    public String getEffectActionId() {
        return effectActionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EFFECT_ACTION.EFFECT_ACTION_ID
     *
     * @param effectActionId the value for EFFECT_ACTION.EFFECT_ACTION_ID
     *
     * @mbggenerated
     */
    public void setEffectActionId(String effectActionId) {
        this.effectActionId = effectActionId == null ? null : effectActionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EFFECT_ACTION.EFFECT_ACTION_CODE
     *
     * @return the value of EFFECT_ACTION.EFFECT_ACTION_CODE
     *
     * @mbggenerated
     */
    public BigDecimal getEffectActionCode() {
        return effectActionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EFFECT_ACTION.EFFECT_ACTION_CODE
     *
     * @param effectActionCode the value for EFFECT_ACTION.EFFECT_ACTION_CODE
     *
     * @mbggenerated
     */
    public void setEffectActionCode(BigDecimal effectActionCode) {
        this.effectActionCode = effectActionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EFFECT_ACTION.EFFECT_ACTION_NAME
     *
     * @return the value of EFFECT_ACTION.EFFECT_ACTION_NAME
     *
     * @mbggenerated
     */
    public String getEffectActionName() {
        return effectActionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EFFECT_ACTION.EFFECT_ACTION_NAME
     *
     * @param effectActionName the value for EFFECT_ACTION.EFFECT_ACTION_NAME
     *
     * @mbggenerated
     */
    public void setEffectActionName(String effectActionName) {
        this.effectActionName = effectActionName == null ? null : effectActionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EFFECT_ACTION.EFFECT_ACTION_DESC
     *
     * @return the value of EFFECT_ACTION.EFFECT_ACTION_DESC
     *
     * @mbggenerated
     */
    public String getEffectActionDesc() {
        return effectActionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EFFECT_ACTION.EFFECT_ACTION_DESC
     *
     * @param effectActionDesc the value for EFFECT_ACTION.EFFECT_ACTION_DESC
     *
     * @mbggenerated
     */
    public void setEffectActionDesc(String effectActionDesc) {
        this.effectActionDesc = effectActionDesc == null ? null : effectActionDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EFFECT_ACTION.MODULE_ID
     *
     * @return the value of EFFECT_ACTION.MODULE_ID
     *
     * @mbggenerated
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EFFECT_ACTION.MODULE_ID
     *
     * @param moduleId the value for EFFECT_ACTION.MODULE_ID
     *
     * @mbggenerated
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }
}