package cn.com.chinatelecom.pms.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class EffectProcessExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	protected String	orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	protected boolean	distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	protected List<Criteria>	oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	public EffectProcessExample(){
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause){
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	public String getOrderByClause(){
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct){
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	public boolean isDistinct(){
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria(){
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	public void or(Criteria criteria){
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	public Criteria or(){
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	public Criteria createCriteria(){
		Criteria criteria = createCriteriaInternal();
		if(oredCriteria.size()==0){
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal(){
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	public void clear(){
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion>	criteria;

		protected GeneratedCriteria(){
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid(){
			return criteria.size()>0;
		}

		public List<Criterion> getAllCriteria(){
			return criteria;
		}

		public List<Criterion> getCriteria(){
			return criteria;
		}

		protected void addCriterion(String condition){
			if(condition==null){
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition,Object value,
				String property){
			if(value==null){
				throw new RuntimeException("Value for "+property
						+" cannot be null");
			}
			criteria.add(new Criterion(condition,value));
		}

		protected void addCriterion(String condition,Object value1,
				Object value2,String property){
			if(value1==null||value2==null){
				throw new RuntimeException("Between values for "+property
						+" cannot be null");
			}
			criteria.add(new Criterion(condition,value1,value2));
		}

		public Criteria andEffectProcessIdIsNull(){
			addCriterion("EFFECT_PROCESS_ID is null");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdIsNotNull(){
			addCriterion("EFFECT_PROCESS_ID is not null");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdEqualTo(String value){
			addCriterion("EFFECT_PROCESS_ID =",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdNotEqualTo(String value){
			addCriterion("EFFECT_PROCESS_ID <>",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdGreaterThan(String value){
			addCriterion("EFFECT_PROCESS_ID >",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdGreaterThanOrEqualTo(String value){
			addCriterion("EFFECT_PROCESS_ID >=",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdLessThan(String value){
			addCriterion("EFFECT_PROCESS_ID <",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdLessThanOrEqualTo(String value){
			addCriterion("EFFECT_PROCESS_ID <=",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdLike(String value){
			addCriterion("EFFECT_PROCESS_ID like",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdNotLike(String value){
			addCriterion("EFFECT_PROCESS_ID not like",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdIn(List<String> values){
			addCriterion("EFFECT_PROCESS_ID in",values,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdNotIn(List<String> values){
			addCriterion("EFFECT_PROCESS_ID not in",values,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdBetween(String value1,String value2){
			addCriterion("EFFECT_PROCESS_ID between",value1,value2,
					"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdNotBetween(String value1,String value2){
			addCriterion("EFFECT_PROCESS_ID not between",value1,value2,
					"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessCodeIsNull(){
			addCriterion("EFFECT_PROCESS_CODE is null");
			return (Criteria)this;
		}

		public Criteria andEffectProcessCodeIsNotNull(){
			addCriterion("EFFECT_PROCESS_CODE is not null");
			return (Criteria)this;
		}

		public Criteria andEffectProcessCodeEqualTo(BigDecimal value){
			addCriterion("EFFECT_PROCESS_CODE =",value,"effectProcessCode");
			return (Criteria)this;
		}

		public Criteria andEffectProcessCodeNotEqualTo(BigDecimal value){
			addCriterion("EFFECT_PROCESS_CODE <>",value,"effectProcessCode");
			return (Criteria)this;
		}

		public Criteria andEffectProcessCodeGreaterThan(BigDecimal value){
			addCriterion("EFFECT_PROCESS_CODE >",value,"effectProcessCode");
			return (Criteria)this;
		}

		public Criteria andEffectProcessCodeGreaterThanOrEqualTo(
				BigDecimal value){
			addCriterion("EFFECT_PROCESS_CODE >=",value,"effectProcessCode");
			return (Criteria)this;
		}

		public Criteria andEffectProcessCodeLessThan(BigDecimal value){
			addCriterion("EFFECT_PROCESS_CODE <",value,"effectProcessCode");
			return (Criteria)this;
		}

		public Criteria andEffectProcessCodeLessThanOrEqualTo(BigDecimal value){
			addCriterion("EFFECT_PROCESS_CODE <=",value,"effectProcessCode");
			return (Criteria)this;
		}

		public Criteria andEffectProcessCodeIn(List<BigDecimal> values){
			addCriterion("EFFECT_PROCESS_CODE in",values,"effectProcessCode");
			return (Criteria)this;
		}

		public Criteria andEffectProcessCodeNotIn(List<BigDecimal> values){
			addCriterion("EFFECT_PROCESS_CODE not in",values,
					"effectProcessCode");
			return (Criteria)this;
		}

		public Criteria andEffectProcessCodeBetween(BigDecimal value1,
				BigDecimal value2){
			addCriterion("EFFECT_PROCESS_CODE between",value1,value2,
					"effectProcessCode");
			return (Criteria)this;
		}

		public Criteria andEffectProcessCodeNotBetween(BigDecimal value1,
				BigDecimal value2){
			addCriterion("EFFECT_PROCESS_CODE not between",value1,value2,
					"effectProcessCode");
			return (Criteria)this;
		}

		public Criteria andEffectProcessNameIsNull(){
			addCriterion("EFFECT_PROCESS_NAME is null");
			return (Criteria)this;
		}

		public Criteria andEffectProcessNameIsNotNull(){
			addCriterion("EFFECT_PROCESS_NAME is not null");
			return (Criteria)this;
		}

		public Criteria andEffectProcessNameEqualTo(String value){
			addCriterion("EFFECT_PROCESS_NAME =",value,"effectProcessName");
			return (Criteria)this;
		}

		public Criteria andEffectProcessNameNotEqualTo(String value){
			addCriterion("EFFECT_PROCESS_NAME <>",value,"effectProcessName");
			return (Criteria)this;
		}

		public Criteria andEffectProcessNameGreaterThan(String value){
			addCriterion("EFFECT_PROCESS_NAME >",value,"effectProcessName");
			return (Criteria)this;
		}

		public Criteria andEffectProcessNameGreaterThanOrEqualTo(String value){
			addCriterion("EFFECT_PROCESS_NAME >=",value,"effectProcessName");
			return (Criteria)this;
		}

		public Criteria andEffectProcessNameLessThan(String value){
			addCriterion("EFFECT_PROCESS_NAME <",value,"effectProcessName");
			return (Criteria)this;
		}

		public Criteria andEffectProcessNameLessThanOrEqualTo(String value){
			addCriterion("EFFECT_PROCESS_NAME <=",value,"effectProcessName");
			return (Criteria)this;
		}

		public Criteria andEffectProcessNameLike(String value){
			addCriterion("EFFECT_PROCESS_NAME like",value,"effectProcessName");
			return (Criteria)this;
		}

		public Criteria andEffectProcessNameNotLike(String value){
			addCriterion("EFFECT_PROCESS_NAME not like",value,
					"effectProcessName");
			return (Criteria)this;
		}

		public Criteria andEffectProcessNameIn(List<String> values){
			addCriterion("EFFECT_PROCESS_NAME in",values,"effectProcessName");
			return (Criteria)this;
		}

		public Criteria andEffectProcessNameNotIn(List<String> values){
			addCriterion("EFFECT_PROCESS_NAME not in",values,
					"effectProcessName");
			return (Criteria)this;
		}

		public Criteria andEffectProcessNameBetween(String value1,String value2){
			addCriterion("EFFECT_PROCESS_NAME between",value1,value2,
					"effectProcessName");
			return (Criteria)this;
		}

		public Criteria andEffectProcessNameNotBetween(String value1,
				String value2){
			addCriterion("EFFECT_PROCESS_NAME not between",value1,value2,
					"effectProcessName");
			return (Criteria)this;
		}

		public Criteria andEffectProcessDescIsNull(){
			addCriterion("EFFECT_PROCESS_DESC is null");
			return (Criteria)this;
		}

		public Criteria andEffectProcessDescIsNotNull(){
			addCriterion("EFFECT_PROCESS_DESC is not null");
			return (Criteria)this;
		}

		public Criteria andEffectProcessDescEqualTo(String value){
			addCriterion("EFFECT_PROCESS_DESC =",value,"effectProcessDesc");
			return (Criteria)this;
		}

		public Criteria andEffectProcessDescNotEqualTo(String value){
			addCriterion("EFFECT_PROCESS_DESC <>",value,"effectProcessDesc");
			return (Criteria)this;
		}

		public Criteria andEffectProcessDescGreaterThan(String value){
			addCriterion("EFFECT_PROCESS_DESC >",value,"effectProcessDesc");
			return (Criteria)this;
		}

		public Criteria andEffectProcessDescGreaterThanOrEqualTo(String value){
			addCriterion("EFFECT_PROCESS_DESC >=",value,"effectProcessDesc");
			return (Criteria)this;
		}

		public Criteria andEffectProcessDescLessThan(String value){
			addCriterion("EFFECT_PROCESS_DESC <",value,"effectProcessDesc");
			return (Criteria)this;
		}

		public Criteria andEffectProcessDescLessThanOrEqualTo(String value){
			addCriterion("EFFECT_PROCESS_DESC <=",value,"effectProcessDesc");
			return (Criteria)this;
		}

		public Criteria andEffectProcessDescLike(String value){
			addCriterion("EFFECT_PROCESS_DESC like",value,"effectProcessDesc");
			return (Criteria)this;
		}

		public Criteria andEffectProcessDescNotLike(String value){
			addCriterion("EFFECT_PROCESS_DESC not like",value,
					"effectProcessDesc");
			return (Criteria)this;
		}

		public Criteria andEffectProcessDescIn(List<String> values){
			addCriterion("EFFECT_PROCESS_DESC in",values,"effectProcessDesc");
			return (Criteria)this;
		}

		public Criteria andEffectProcessDescNotIn(List<String> values){
			addCriterion("EFFECT_PROCESS_DESC not in",values,
					"effectProcessDesc");
			return (Criteria)this;
		}

		public Criteria andEffectProcessDescBetween(String value1,String value2){
			addCriterion("EFFECT_PROCESS_DESC between",value1,value2,
					"effectProcessDesc");
			return (Criteria)this;
		}

		public Criteria andEffectProcessDescNotBetween(String value1,
				String value2){
			addCriterion("EFFECT_PROCESS_DESC not between",value1,value2,
					"effectProcessDesc");
			return (Criteria)this;
		}

		public Criteria andEffectProcessVersionIsNull(){
			addCriterion("EFFECT_PROCESS_VERSION is null");
			return (Criteria)this;
		}

		public Criteria andEffectProcessVersionIsNotNull(){
			addCriterion("EFFECT_PROCESS_VERSION is not null");
			return (Criteria)this;
		}

		public Criteria andEffectProcessVersionEqualTo(String value){
			addCriterion("EFFECT_PROCESS_VERSION =",value,
					"effectProcessVersion");
			return (Criteria)this;
		}

		public Criteria andEffectProcessVersionNotEqualTo(String value){
			addCriterion("EFFECT_PROCESS_VERSION <>",value,
					"effectProcessVersion");
			return (Criteria)this;
		}

		public Criteria andEffectProcessVersionGreaterThan(String value){
			addCriterion("EFFECT_PROCESS_VERSION >",value,
					"effectProcessVersion");
			return (Criteria)this;
		}

		public Criteria andEffectProcessVersionGreaterThanOrEqualTo(String value){
			addCriterion("EFFECT_PROCESS_VERSION >=",value,
					"effectProcessVersion");
			return (Criteria)this;
		}

		public Criteria andEffectProcessVersionLessThan(String value){
			addCriterion("EFFECT_PROCESS_VERSION <",value,
					"effectProcessVersion");
			return (Criteria)this;
		}

		public Criteria andEffectProcessVersionLessThanOrEqualTo(String value){
			addCriterion("EFFECT_PROCESS_VERSION <=",value,
					"effectProcessVersion");
			return (Criteria)this;
		}

		public Criteria andEffectProcessVersionLike(String value){
			addCriterion("EFFECT_PROCESS_VERSION like",value,
					"effectProcessVersion");
			return (Criteria)this;
		}

		public Criteria andEffectProcessVersionNotLike(String value){
			addCriterion("EFFECT_PROCESS_VERSION not like",value,
					"effectProcessVersion");
			return (Criteria)this;
		}

		public Criteria andEffectProcessVersionIn(List<String> values){
			addCriterion("EFFECT_PROCESS_VERSION in",values,
					"effectProcessVersion");
			return (Criteria)this;
		}

		public Criteria andEffectProcessVersionNotIn(List<String> values){
			addCriterion("EFFECT_PROCESS_VERSION not in",values,
					"effectProcessVersion");
			return (Criteria)this;
		}

		public Criteria andEffectProcessVersionBetween(String value1,
				String value2){
			addCriterion("EFFECT_PROCESS_VERSION between",value1,value2,
					"effectProcessVersion");
			return (Criteria)this;
		}

		public Criteria andEffectProcessVersionNotBetween(String value1,
				String value2){
			addCriterion("EFFECT_PROCESS_VERSION not between",value1,value2,
					"effectProcessVersion");
			return (Criteria)this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	public static class Criterion {
		private String	condition;
		private Object	value;
		private Object	secondValue;
		private boolean	noValue;
		private boolean	singleValue;
		private boolean	betweenValue;
		private boolean	listValue;
		private String	typeHandler;

		public String getCondition(){
			return condition;
		}

		public Object getValue(){
			return value;
		}

		public Object getSecondValue(){
			return secondValue;
		}

		public boolean isNoValue(){
			return noValue;
		}

		public boolean isSingleValue(){
			return singleValue;
		}

		public boolean isBetweenValue(){
			return betweenValue;
		}

		public boolean isListValue(){
			return listValue;
		}

		public String getTypeHandler(){
			return typeHandler;
		}

		protected Criterion(String condition){
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition,Object value,String typeHandler){
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if(value instanceof List<?>){
				this.listValue = true;
			} else{
				this.singleValue = true;
			}
		}

		protected Criterion(String condition,Object value){
			this(condition,value,null);
		}

		protected Criterion(String condition,Object value,Object secondValue,
				String typeHandler){
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition,Object value,Object secondValue){
			this(condition,value,secondValue,null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table EFFECT_PROCESS
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}