package cn.com.chinatelecom.pms.pojo;

import java.math.BigDecimal;

public class EffectProcess {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EFFECT_PROCESS.EFFECT_PROCESS_ID
	 * @mbggenerated
	 */
	private String	effectProcessId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EFFECT_PROCESS.EFFECT_PROCESS_CODE
	 * @mbggenerated
	 */
	private BigDecimal	effectProcessCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EFFECT_PROCESS.EFFECT_PROCESS_NAME
	 * @mbggenerated
	 */
	private String	effectProcessName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EFFECT_PROCESS.EFFECT_PROCESS_DESC
	 * @mbggenerated
	 */
	private String	effectProcessDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EFFECT_PROCESS.EFFECT_PROCESS_VERSION
	 * @mbggenerated
	 */
	private String	effectProcessVersion;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EFFECT_PROCESS.EFFECT_PROCESS_ID
	 * @return  the value of EFFECT_PROCESS.EFFECT_PROCESS_ID
	 * @mbggenerated
	 */
	public String getEffectProcessId(){
		return effectProcessId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EFFECT_PROCESS.EFFECT_PROCESS_ID
	 * @param effectProcessId  the value for EFFECT_PROCESS.EFFECT_PROCESS_ID
	 * @mbggenerated
	 */
	public void setEffectProcessId(String effectProcessId){
		this.effectProcessId = effectProcessId==null ? null : effectProcessId
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EFFECT_PROCESS.EFFECT_PROCESS_CODE
	 * @return  the value of EFFECT_PROCESS.EFFECT_PROCESS_CODE
	 * @mbggenerated
	 */
	public BigDecimal getEffectProcessCode(){
		return effectProcessCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EFFECT_PROCESS.EFFECT_PROCESS_CODE
	 * @param effectProcessCode  the value for EFFECT_PROCESS.EFFECT_PROCESS_CODE
	 * @mbggenerated
	 */
	public void setEffectProcessCode(BigDecimal effectProcessCode){
		this.effectProcessCode = effectProcessCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EFFECT_PROCESS.EFFECT_PROCESS_NAME
	 * @return  the value of EFFECT_PROCESS.EFFECT_PROCESS_NAME
	 * @mbggenerated
	 */
	public String getEffectProcessName(){
		return effectProcessName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EFFECT_PROCESS.EFFECT_PROCESS_NAME
	 * @param effectProcessName  the value for EFFECT_PROCESS.EFFECT_PROCESS_NAME
	 * @mbggenerated
	 */
	public void setEffectProcessName(String effectProcessName){
		this.effectProcessName = effectProcessName==null ? null
				: effectProcessName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EFFECT_PROCESS.EFFECT_PROCESS_DESC
	 * @return  the value of EFFECT_PROCESS.EFFECT_PROCESS_DESC
	 * @mbggenerated
	 */
	public String getEffectProcessDesc(){
		return effectProcessDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EFFECT_PROCESS.EFFECT_PROCESS_DESC
	 * @param effectProcessDesc  the value for EFFECT_PROCESS.EFFECT_PROCESS_DESC
	 * @mbggenerated
	 */
	public void setEffectProcessDesc(String effectProcessDesc){
		this.effectProcessDesc = effectProcessDesc==null ? null
				: effectProcessDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EFFECT_PROCESS.EFFECT_PROCESS_VERSION
	 * @return  the value of EFFECT_PROCESS.EFFECT_PROCESS_VERSION
	 * @mbggenerated
	 */
	public String getEffectProcessVersion(){
		return effectProcessVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EFFECT_PROCESS.EFFECT_PROCESS_VERSION
	 * @param effectProcessVersion  the value for EFFECT_PROCESS.EFFECT_PROCESS_VERSION
	 * @mbggenerated
	 */
	public void setEffectProcessVersion(String effectProcessVersion){
		this.effectProcessVersion = effectProcessVersion==null ? null
				: effectProcessVersion.trim();
	}
}