package cn.com.chinatelecom.pms.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class EffectActionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    public EffectActionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEffectActionIdIsNull() {
            addCriterion("EFFECT_ACTION_ID is null");
            return (Criteria) this;
        }

        public Criteria andEffectActionIdIsNotNull() {
            addCriterion("EFFECT_ACTION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEffectActionIdEqualTo(String value) {
            addCriterion("EFFECT_ACTION_ID =", value, "effectActionId");
            return (Criteria) this;
        }

        public Criteria andEffectActionIdNotEqualTo(String value) {
            addCriterion("EFFECT_ACTION_ID <>", value, "effectActionId");
            return (Criteria) this;
        }

        public Criteria andEffectActionIdGreaterThan(String value) {
            addCriterion("EFFECT_ACTION_ID >", value, "effectActionId");
            return (Criteria) this;
        }

        public Criteria andEffectActionIdGreaterThanOrEqualTo(String value) {
            addCriterion("EFFECT_ACTION_ID >=", value, "effectActionId");
            return (Criteria) this;
        }

        public Criteria andEffectActionIdLessThan(String value) {
            addCriterion("EFFECT_ACTION_ID <", value, "effectActionId");
            return (Criteria) this;
        }

        public Criteria andEffectActionIdLessThanOrEqualTo(String value) {
            addCriterion("EFFECT_ACTION_ID <=", value, "effectActionId");
            return (Criteria) this;
        }

        public Criteria andEffectActionIdLike(String value) {
            addCriterion("EFFECT_ACTION_ID like", value, "effectActionId");
            return (Criteria) this;
        }

        public Criteria andEffectActionIdNotLike(String value) {
            addCriterion("EFFECT_ACTION_ID not like", value, "effectActionId");
            return (Criteria) this;
        }

        public Criteria andEffectActionIdIn(List<String> values) {
            addCriterion("EFFECT_ACTION_ID in", values, "effectActionId");
            return (Criteria) this;
        }

        public Criteria andEffectActionIdNotIn(List<String> values) {
            addCriterion("EFFECT_ACTION_ID not in", values, "effectActionId");
            return (Criteria) this;
        }

        public Criteria andEffectActionIdBetween(String value1, String value2) {
            addCriterion("EFFECT_ACTION_ID between", value1, value2, "effectActionId");
            return (Criteria) this;
        }

        public Criteria andEffectActionIdNotBetween(String value1, String value2) {
            addCriterion("EFFECT_ACTION_ID not between", value1, value2, "effectActionId");
            return (Criteria) this;
        }

        public Criteria andEffectActionCodeIsNull() {
            addCriterion("EFFECT_ACTION_CODE is null");
            return (Criteria) this;
        }

        public Criteria andEffectActionCodeIsNotNull() {
            addCriterion("EFFECT_ACTION_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andEffectActionCodeEqualTo(BigDecimal value) {
            addCriterion("EFFECT_ACTION_CODE =", value, "effectActionCode");
            return (Criteria) this;
        }

        public Criteria andEffectActionCodeNotEqualTo(BigDecimal value) {
            addCriterion("EFFECT_ACTION_CODE <>", value, "effectActionCode");
            return (Criteria) this;
        }

        public Criteria andEffectActionCodeGreaterThan(BigDecimal value) {
            addCriterion("EFFECT_ACTION_CODE >", value, "effectActionCode");
            return (Criteria) this;
        }

        public Criteria andEffectActionCodeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("EFFECT_ACTION_CODE >=", value, "effectActionCode");
            return (Criteria) this;
        }

        public Criteria andEffectActionCodeLessThan(BigDecimal value) {
            addCriterion("EFFECT_ACTION_CODE <", value, "effectActionCode");
            return (Criteria) this;
        }

        public Criteria andEffectActionCodeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("EFFECT_ACTION_CODE <=", value, "effectActionCode");
            return (Criteria) this;
        }

        public Criteria andEffectActionCodeIn(List<BigDecimal> values) {
            addCriterion("EFFECT_ACTION_CODE in", values, "effectActionCode");
            return (Criteria) this;
        }

        public Criteria andEffectActionCodeNotIn(List<BigDecimal> values) {
            addCriterion("EFFECT_ACTION_CODE not in", values, "effectActionCode");
            return (Criteria) this;
        }

        public Criteria andEffectActionCodeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EFFECT_ACTION_CODE between", value1, value2, "effectActionCode");
            return (Criteria) this;
        }

        public Criteria andEffectActionCodeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EFFECT_ACTION_CODE not between", value1, value2, "effectActionCode");
            return (Criteria) this;
        }

        public Criteria andEffectActionNameIsNull() {
            addCriterion("EFFECT_ACTION_NAME is null");
            return (Criteria) this;
        }

        public Criteria andEffectActionNameIsNotNull() {
            addCriterion("EFFECT_ACTION_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andEffectActionNameEqualTo(String value) {
            addCriterion("EFFECT_ACTION_NAME =", value, "effectActionName");
            return (Criteria) this;
        }

        public Criteria andEffectActionNameNotEqualTo(String value) {
            addCriterion("EFFECT_ACTION_NAME <>", value, "effectActionName");
            return (Criteria) this;
        }

        public Criteria andEffectActionNameGreaterThan(String value) {
            addCriterion("EFFECT_ACTION_NAME >", value, "effectActionName");
            return (Criteria) this;
        }

        public Criteria andEffectActionNameGreaterThanOrEqualTo(String value) {
            addCriterion("EFFECT_ACTION_NAME >=", value, "effectActionName");
            return (Criteria) this;
        }

        public Criteria andEffectActionNameLessThan(String value) {
            addCriterion("EFFECT_ACTION_NAME <", value, "effectActionName");
            return (Criteria) this;
        }

        public Criteria andEffectActionNameLessThanOrEqualTo(String value) {
            addCriterion("EFFECT_ACTION_NAME <=", value, "effectActionName");
            return (Criteria) this;
        }

        public Criteria andEffectActionNameLike(String value) {
            addCriterion("EFFECT_ACTION_NAME like", value, "effectActionName");
            return (Criteria) this;
        }

        public Criteria andEffectActionNameNotLike(String value) {
            addCriterion("EFFECT_ACTION_NAME not like", value, "effectActionName");
            return (Criteria) this;
        }

        public Criteria andEffectActionNameIn(List<String> values) {
            addCriterion("EFFECT_ACTION_NAME in", values, "effectActionName");
            return (Criteria) this;
        }

        public Criteria andEffectActionNameNotIn(List<String> values) {
            addCriterion("EFFECT_ACTION_NAME not in", values, "effectActionName");
            return (Criteria) this;
        }

        public Criteria andEffectActionNameBetween(String value1, String value2) {
            addCriterion("EFFECT_ACTION_NAME between", value1, value2, "effectActionName");
            return (Criteria) this;
        }

        public Criteria andEffectActionNameNotBetween(String value1, String value2) {
            addCriterion("EFFECT_ACTION_NAME not between", value1, value2, "effectActionName");
            return (Criteria) this;
        }

        public Criteria andEffectActionDescIsNull() {
            addCriterion("EFFECT_ACTION_DESC is null");
            return (Criteria) this;
        }

        public Criteria andEffectActionDescIsNotNull() {
            addCriterion("EFFECT_ACTION_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andEffectActionDescEqualTo(String value) {
            addCriterion("EFFECT_ACTION_DESC =", value, "effectActionDesc");
            return (Criteria) this;
        }

        public Criteria andEffectActionDescNotEqualTo(String value) {
            addCriterion("EFFECT_ACTION_DESC <>", value, "effectActionDesc");
            return (Criteria) this;
        }

        public Criteria andEffectActionDescGreaterThan(String value) {
            addCriterion("EFFECT_ACTION_DESC >", value, "effectActionDesc");
            return (Criteria) this;
        }

        public Criteria andEffectActionDescGreaterThanOrEqualTo(String value) {
            addCriterion("EFFECT_ACTION_DESC >=", value, "effectActionDesc");
            return (Criteria) this;
        }

        public Criteria andEffectActionDescLessThan(String value) {
            addCriterion("EFFECT_ACTION_DESC <", value, "effectActionDesc");
            return (Criteria) this;
        }

        public Criteria andEffectActionDescLessThanOrEqualTo(String value) {
            addCriterion("EFFECT_ACTION_DESC <=", value, "effectActionDesc");
            return (Criteria) this;
        }

        public Criteria andEffectActionDescLike(String value) {
            addCriterion("EFFECT_ACTION_DESC like", value, "effectActionDesc");
            return (Criteria) this;
        }

        public Criteria andEffectActionDescNotLike(String value) {
            addCriterion("EFFECT_ACTION_DESC not like", value, "effectActionDesc");
            return (Criteria) this;
        }

        public Criteria andEffectActionDescIn(List<String> values) {
            addCriterion("EFFECT_ACTION_DESC in", values, "effectActionDesc");
            return (Criteria) this;
        }

        public Criteria andEffectActionDescNotIn(List<String> values) {
            addCriterion("EFFECT_ACTION_DESC not in", values, "effectActionDesc");
            return (Criteria) this;
        }

        public Criteria andEffectActionDescBetween(String value1, String value2) {
            addCriterion("EFFECT_ACTION_DESC between", value1, value2, "effectActionDesc");
            return (Criteria) this;
        }

        public Criteria andEffectActionDescNotBetween(String value1, String value2) {
            addCriterion("EFFECT_ACTION_DESC not between", value1, value2, "effectActionDesc");
            return (Criteria) this;
        }

        public Criteria andModuleIdIsNull() {
            addCriterion("MODULE_ID is null");
            return (Criteria) this;
        }

        public Criteria andModuleIdIsNotNull() {
            addCriterion("MODULE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andModuleIdEqualTo(String value) {
            addCriterion("MODULE_ID =", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdNotEqualTo(String value) {
            addCriterion("MODULE_ID <>", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdGreaterThan(String value) {
            addCriterion("MODULE_ID >", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdGreaterThanOrEqualTo(String value) {
            addCriterion("MODULE_ID >=", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdLessThan(String value) {
            addCriterion("MODULE_ID <", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdLessThanOrEqualTo(String value) {
            addCriterion("MODULE_ID <=", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdLike(String value) {
            addCriterion("MODULE_ID like", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdNotLike(String value) {
            addCriterion("MODULE_ID not like", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdIn(List<String> values) {
            addCriterion("MODULE_ID in", values, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdNotIn(List<String> values) {
            addCriterion("MODULE_ID not in", values, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdBetween(String value1, String value2) {
            addCriterion("MODULE_ID between", value1, value2, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdNotBetween(String value1, String value2) {
            addCriterion("MODULE_ID not between", value1, value2, "moduleId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}