package cn.com.chinatelecom.pms.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ExecuteOrgExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	protected String	orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	protected boolean	distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	protected List<Criteria>	oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	public ExecuteOrgExample(){
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause){
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	public String getOrderByClause(){
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct){
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	public boolean isDistinct(){
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria(){
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	public void or(Criteria criteria){
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	public Criteria or(){
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	public Criteria createCriteria(){
		Criteria criteria = createCriteriaInternal();
		if(oredCriteria.size()==0){
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal(){
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	public void clear(){
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion>	criteria;

		protected GeneratedCriteria(){
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid(){
			return criteria.size()>0;
		}

		public List<Criterion> getAllCriteria(){
			return criteria;
		}

		public List<Criterion> getCriteria(){
			return criteria;
		}

		protected void addCriterion(String condition){
			if(condition==null){
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition,Object value,
				String property){
			if(value==null){
				throw new RuntimeException("Value for "+property
						+" cannot be null");
			}
			criteria.add(new Criterion(condition,value));
		}

		protected void addCriterion(String condition,Object value1,
				Object value2,String property){
			if(value1==null||value2==null){
				throw new RuntimeException("Between values for "+property
						+" cannot be null");
			}
			criteria.add(new Criterion(condition,value1,value2));
		}

		public Criteria andExecuteOrgIdIsNull(){
			addCriterion("EXECUTE_ORG_ID is null");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdIsNotNull(){
			addCriterion("EXECUTE_ORG_ID is not null");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdEqualTo(String value){
			addCriterion("EXECUTE_ORG_ID =",value,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdNotEqualTo(String value){
			addCriterion("EXECUTE_ORG_ID <>",value,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdGreaterThan(String value){
			addCriterion("EXECUTE_ORG_ID >",value,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdGreaterThanOrEqualTo(String value){
			addCriterion("EXECUTE_ORG_ID >=",value,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdLessThan(String value){
			addCriterion("EXECUTE_ORG_ID <",value,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdLessThanOrEqualTo(String value){
			addCriterion("EXECUTE_ORG_ID <=",value,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdLike(String value){
			addCriterion("EXECUTE_ORG_ID like",value,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdNotLike(String value){
			addCriterion("EXECUTE_ORG_ID not like",value,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdIn(List<String> values){
			addCriterion("EXECUTE_ORG_ID in",values,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdNotIn(List<String> values){
			addCriterion("EXECUTE_ORG_ID not in",values,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdBetween(String value1,String value2){
			addCriterion("EXECUTE_ORG_ID between",value1,value2,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdNotBetween(String value1,String value2){
			addCriterion("EXECUTE_ORG_ID not between",value1,value2,
					"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgCodeIsNull(){
			addCriterion("EXECUTE_ORG_CODE is null");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgCodeIsNotNull(){
			addCriterion("EXECUTE_ORG_CODE is not null");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgCodeEqualTo(BigDecimal value){
			addCriterion("EXECUTE_ORG_CODE =",value,"executeOrgCode");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgCodeNotEqualTo(BigDecimal value){
			addCriterion("EXECUTE_ORG_CODE <>",value,"executeOrgCode");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgCodeGreaterThan(BigDecimal value){
			addCriterion("EXECUTE_ORG_CODE >",value,"executeOrgCode");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgCodeGreaterThanOrEqualTo(BigDecimal value){
			addCriterion("EXECUTE_ORG_CODE >=",value,"executeOrgCode");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgCodeLessThan(BigDecimal value){
			addCriterion("EXECUTE_ORG_CODE <",value,"executeOrgCode");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgCodeLessThanOrEqualTo(BigDecimal value){
			addCriterion("EXECUTE_ORG_CODE <=",value,"executeOrgCode");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgCodeIn(List<BigDecimal> values){
			addCriterion("EXECUTE_ORG_CODE in",values,"executeOrgCode");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgCodeNotIn(List<BigDecimal> values){
			addCriterion("EXECUTE_ORG_CODE not in",values,"executeOrgCode");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgCodeBetween(BigDecimal value1,
				BigDecimal value2){
			addCriterion("EXECUTE_ORG_CODE between",value1,value2,
					"executeOrgCode");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgCodeNotBetween(BigDecimal value1,
				BigDecimal value2){
			addCriterion("EXECUTE_ORG_CODE not between",value1,value2,
					"executeOrgCode");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgNameIsNull(){
			addCriterion("EXECUTE_ORG_NAME is null");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgNameIsNotNull(){
			addCriterion("EXECUTE_ORG_NAME is not null");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgNameEqualTo(String value){
			addCriterion("EXECUTE_ORG_NAME =",value,"executeOrgName");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgNameNotEqualTo(String value){
			addCriterion("EXECUTE_ORG_NAME <>",value,"executeOrgName");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgNameGreaterThan(String value){
			addCriterion("EXECUTE_ORG_NAME >",value,"executeOrgName");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgNameGreaterThanOrEqualTo(String value){
			addCriterion("EXECUTE_ORG_NAME >=",value,"executeOrgName");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgNameLessThan(String value){
			addCriterion("EXECUTE_ORG_NAME <",value,"executeOrgName");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgNameLessThanOrEqualTo(String value){
			addCriterion("EXECUTE_ORG_NAME <=",value,"executeOrgName");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgNameLike(String value){
			addCriterion("EXECUTE_ORG_NAME like",value,"executeOrgName");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgNameNotLike(String value){
			addCriterion("EXECUTE_ORG_NAME not like",value,"executeOrgName");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgNameIn(List<String> values){
			addCriterion("EXECUTE_ORG_NAME in",values,"executeOrgName");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgNameNotIn(List<String> values){
			addCriterion("EXECUTE_ORG_NAME not in",values,"executeOrgName");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgNameBetween(String value1,String value2){
			addCriterion("EXECUTE_ORG_NAME between",value1,value2,
					"executeOrgName");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgNameNotBetween(String value1,String value2){
			addCriterion("EXECUTE_ORG_NAME not between",value1,value2,
					"executeOrgName");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgDescIsNull(){
			addCriterion("EXECUTE_ORG_DESC is null");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgDescIsNotNull(){
			addCriterion("EXECUTE_ORG_DESC is not null");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgDescEqualTo(String value){
			addCriterion("EXECUTE_ORG_DESC =",value,"executeOrgDesc");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgDescNotEqualTo(String value){
			addCriterion("EXECUTE_ORG_DESC <>",value,"executeOrgDesc");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgDescGreaterThan(String value){
			addCriterion("EXECUTE_ORG_DESC >",value,"executeOrgDesc");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgDescGreaterThanOrEqualTo(String value){
			addCriterion("EXECUTE_ORG_DESC >=",value,"executeOrgDesc");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgDescLessThan(String value){
			addCriterion("EXECUTE_ORG_DESC <",value,"executeOrgDesc");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgDescLessThanOrEqualTo(String value){
			addCriterion("EXECUTE_ORG_DESC <=",value,"executeOrgDesc");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgDescLike(String value){
			addCriterion("EXECUTE_ORG_DESC like",value,"executeOrgDesc");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgDescNotLike(String value){
			addCriterion("EXECUTE_ORG_DESC not like",value,"executeOrgDesc");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgDescIn(List<String> values){
			addCriterion("EXECUTE_ORG_DESC in",values,"executeOrgDesc");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgDescNotIn(List<String> values){
			addCriterion("EXECUTE_ORG_DESC not in",values,"executeOrgDesc");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgDescBetween(String value1,String value2){
			addCriterion("EXECUTE_ORG_DESC between",value1,value2,
					"executeOrgDesc");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgDescNotBetween(String value1,String value2){
			addCriterion("EXECUTE_ORG_DESC not between",value1,value2,
					"executeOrgDesc");
			return (Criteria)this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	public static class Criterion {
		private String	condition;
		private Object	value;
		private Object	secondValue;
		private boolean	noValue;
		private boolean	singleValue;
		private boolean	betweenValue;
		private boolean	listValue;
		private String	typeHandler;

		public String getCondition(){
			return condition;
		}

		public Object getValue(){
			return value;
		}

		public Object getSecondValue(){
			return secondValue;
		}

		public boolean isNoValue(){
			return noValue;
		}

		public boolean isSingleValue(){
			return singleValue;
		}

		public boolean isBetweenValue(){
			return betweenValue;
		}

		public boolean isListValue(){
			return listValue;
		}

		public String getTypeHandler(){
			return typeHandler;
		}

		protected Criterion(String condition){
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition,Object value,String typeHandler){
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if(value instanceof List<?>){
				this.listValue = true;
			} else{
				this.singleValue = true;
			}
		}

		protected Criterion(String condition,Object value){
			this(condition,value,null);
		}

		protected Criterion(String condition,Object value,Object secondValue,
				String typeHandler){
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition,Object value,Object secondValue){
			this(condition,value,secondValue,null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table EXECUTE_ORG
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}