package cn.com.chinatelecom.pms.pojo;

import java.util.ArrayList;
import java.util.List;

public class MembersExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	protected String	orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	protected boolean	distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	protected List<Criteria>	oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	public MembersExample(){
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause){
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	public String getOrderByClause(){
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct){
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	public boolean isDistinct(){
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria(){
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	public void or(Criteria criteria){
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	public Criteria or(){
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	public Criteria createCriteria(){
		Criteria criteria = createCriteriaInternal();
		if(oredCriteria.size()==0){
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal(){
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	public void clear(){
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion>	criteria;

		protected GeneratedCriteria(){
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid(){
			return criteria.size()>0;
		}

		public List<Criterion> getAllCriteria(){
			return criteria;
		}

		public List<Criterion> getCriteria(){
			return criteria;
		}

		protected void addCriterion(String condition){
			if(condition==null){
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition,Object value,
				String property){
			if(value==null){
				throw new RuntimeException("Value for "+property
						+" cannot be null");
			}
			criteria.add(new Criterion(condition,value));
		}

		protected void addCriterion(String condition,Object value1,
				Object value2,String property){
			if(value1==null||value2==null){
				throw new RuntimeException("Between values for "+property
						+" cannot be null");
			}
			criteria.add(new Criterion(condition,value1,value2));
		}

		public Criteria andMemberIdIsNull(){
			addCriterion("MEMBER_ID is null");
			return (Criteria)this;
		}

		public Criteria andMemberIdIsNotNull(){
			addCriterion("MEMBER_ID is not null");
			return (Criteria)this;
		}

		public Criteria andMemberIdEqualTo(String value){
			addCriterion("MEMBER_ID =",value,"memberId");
			return (Criteria)this;
		}

		public Criteria andMemberIdNotEqualTo(String value){
			addCriterion("MEMBER_ID <>",value,"memberId");
			return (Criteria)this;
		}

		public Criteria andMemberIdGreaterThan(String value){
			addCriterion("MEMBER_ID >",value,"memberId");
			return (Criteria)this;
		}

		public Criteria andMemberIdGreaterThanOrEqualTo(String value){
			addCriterion("MEMBER_ID >=",value,"memberId");
			return (Criteria)this;
		}

		public Criteria andMemberIdLessThan(String value){
			addCriterion("MEMBER_ID <",value,"memberId");
			return (Criteria)this;
		}

		public Criteria andMemberIdLessThanOrEqualTo(String value){
			addCriterion("MEMBER_ID <=",value,"memberId");
			return (Criteria)this;
		}

		public Criteria andMemberIdLike(String value){
			addCriterion("MEMBER_ID like",value,"memberId");
			return (Criteria)this;
		}

		public Criteria andMemberIdNotLike(String value){
			addCriterion("MEMBER_ID not like",value,"memberId");
			return (Criteria)this;
		}

		public Criteria andMemberIdIn(List<String> values){
			addCriterion("MEMBER_ID in",values,"memberId");
			return (Criteria)this;
		}

		public Criteria andMemberIdNotIn(List<String> values){
			addCriterion("MEMBER_ID not in",values,"memberId");
			return (Criteria)this;
		}

		public Criteria andMemberIdBetween(String value1,String value2){
			addCriterion("MEMBER_ID between",value1,value2,"memberId");
			return (Criteria)this;
		}

		public Criteria andMemberIdNotBetween(String value1,String value2){
			addCriterion("MEMBER_ID not between",value1,value2,"memberId");
			return (Criteria)this;
		}

		public Criteria andMemberGroupIdIsNull(){
			addCriterion("MEMBER_GROUP_ID is null");
			return (Criteria)this;
		}

		public Criteria andMemberGroupIdIsNotNull(){
			addCriterion("MEMBER_GROUP_ID is not null");
			return (Criteria)this;
		}

		public Criteria andMemberGroupIdEqualTo(String value){
			addCriterion("MEMBER_GROUP_ID =",value,"memberGroupId");
			return (Criteria)this;
		}

		public Criteria andMemberGroupIdNotEqualTo(String value){
			addCriterion("MEMBER_GROUP_ID <>",value,"memberGroupId");
			return (Criteria)this;
		}

		public Criteria andMemberGroupIdGreaterThan(String value){
			addCriterion("MEMBER_GROUP_ID >",value,"memberGroupId");
			return (Criteria)this;
		}

		public Criteria andMemberGroupIdGreaterThanOrEqualTo(String value){
			addCriterion("MEMBER_GROUP_ID >=",value,"memberGroupId");
			return (Criteria)this;
		}

		public Criteria andMemberGroupIdLessThan(String value){
			addCriterion("MEMBER_GROUP_ID <",value,"memberGroupId");
			return (Criteria)this;
		}

		public Criteria andMemberGroupIdLessThanOrEqualTo(String value){
			addCriterion("MEMBER_GROUP_ID <=",value,"memberGroupId");
			return (Criteria)this;
		}

		public Criteria andMemberGroupIdLike(String value){
			addCriterion("MEMBER_GROUP_ID like",value,"memberGroupId");
			return (Criteria)this;
		}

		public Criteria andMemberGroupIdNotLike(String value){
			addCriterion("MEMBER_GROUP_ID not like",value,"memberGroupId");
			return (Criteria)this;
		}

		public Criteria andMemberGroupIdIn(List<String> values){
			addCriterion("MEMBER_GROUP_ID in",values,"memberGroupId");
			return (Criteria)this;
		}

		public Criteria andMemberGroupIdNotIn(List<String> values){
			addCriterion("MEMBER_GROUP_ID not in",values,"memberGroupId");
			return (Criteria)this;
		}

		public Criteria andMemberGroupIdBetween(String value1,String value2){
			addCriterion("MEMBER_GROUP_ID between",value1,value2,
					"memberGroupId");
			return (Criteria)this;
		}

		public Criteria andMemberGroupIdNotBetween(String value1,String value2){
			addCriterion("MEMBER_GROUP_ID not between",value1,value2,
					"memberGroupId");
			return (Criteria)this;
		}

		public Criteria andMemberCodeIsNull(){
			addCriterion("MEMBER_CODE is null");
			return (Criteria)this;
		}

		public Criteria andMemberCodeIsNotNull(){
			addCriterion("MEMBER_CODE is not null");
			return (Criteria)this;
		}

		public Criteria andMemberCodeEqualTo(String value){
			addCriterion("MEMBER_CODE =",value,"memberCode");
			return (Criteria)this;
		}

		public Criteria andMemberCodeNotEqualTo(String value){
			addCriterion("MEMBER_CODE <>",value,"memberCode");
			return (Criteria)this;
		}

		public Criteria andMemberCodeGreaterThan(String value){
			addCriterion("MEMBER_CODE >",value,"memberCode");
			return (Criteria)this;
		}

		public Criteria andMemberCodeGreaterThanOrEqualTo(String value){
			addCriterion("MEMBER_CODE >=",value,"memberCode");
			return (Criteria)this;
		}

		public Criteria andMemberCodeLessThan(String value){
			addCriterion("MEMBER_CODE <",value,"memberCode");
			return (Criteria)this;
		}

		public Criteria andMemberCodeLessThanOrEqualTo(String value){
			addCriterion("MEMBER_CODE <=",value,"memberCode");
			return (Criteria)this;
		}

		public Criteria andMemberCodeLike(String value){
			addCriterion("MEMBER_CODE like",value,"memberCode");
			return (Criteria)this;
		}

		public Criteria andMemberCodeNotLike(String value){
			addCriterion("MEMBER_CODE not like",value,"memberCode");
			return (Criteria)this;
		}

		public Criteria andMemberCodeIn(List<String> values){
			addCriterion("MEMBER_CODE in",values,"memberCode");
			return (Criteria)this;
		}

		public Criteria andMemberCodeNotIn(List<String> values){
			addCriterion("MEMBER_CODE not in",values,"memberCode");
			return (Criteria)this;
		}

		public Criteria andMemberCodeBetween(String value1,String value2){
			addCriterion("MEMBER_CODE between",value1,value2,"memberCode");
			return (Criteria)this;
		}

		public Criteria andMemberCodeNotBetween(String value1,String value2){
			addCriterion("MEMBER_CODE not between",value1,value2,"memberCode");
			return (Criteria)this;
		}

		public Criteria andMemberNameIsNull(){
			addCriterion("MEMBER_NAME is null");
			return (Criteria)this;
		}

		public Criteria andMemberNameIsNotNull(){
			addCriterion("MEMBER_NAME is not null");
			return (Criteria)this;
		}

		public Criteria andMemberNameEqualTo(String value){
			addCriterion("MEMBER_NAME =",value,"memberName");
			return (Criteria)this;
		}

		public Criteria andMemberNameNotEqualTo(String value){
			addCriterion("MEMBER_NAME <>",value,"memberName");
			return (Criteria)this;
		}

		public Criteria andMemberNameGreaterThan(String value){
			addCriterion("MEMBER_NAME >",value,"memberName");
			return (Criteria)this;
		}

		public Criteria andMemberNameGreaterThanOrEqualTo(String value){
			addCriterion("MEMBER_NAME >=",value,"memberName");
			return (Criteria)this;
		}

		public Criteria andMemberNameLessThan(String value){
			addCriterion("MEMBER_NAME <",value,"memberName");
			return (Criteria)this;
		}

		public Criteria andMemberNameLessThanOrEqualTo(String value){
			addCriterion("MEMBER_NAME <=",value,"memberName");
			return (Criteria)this;
		}

		public Criteria andMemberNameLike(String value){
			addCriterion("MEMBER_NAME like",value,"memberName");
			return (Criteria)this;
		}

		public Criteria andMemberNameNotLike(String value){
			addCriterion("MEMBER_NAME not like",value,"memberName");
			return (Criteria)this;
		}

		public Criteria andMemberNameIn(List<String> values){
			addCriterion("MEMBER_NAME in",values,"memberName");
			return (Criteria)this;
		}

		public Criteria andMemberNameNotIn(List<String> values){
			addCriterion("MEMBER_NAME not in",values,"memberName");
			return (Criteria)this;
		}

		public Criteria andMemberNameBetween(String value1,String value2){
			addCriterion("MEMBER_NAME between",value1,value2,"memberName");
			return (Criteria)this;
		}

		public Criteria andMemberNameNotBetween(String value1,String value2){
			addCriterion("MEMBER_NAME not between",value1,value2,"memberName");
			return (Criteria)this;
		}

		public Criteria andMemberSexIsNull(){
			addCriterion("MEMBER_SEX is null");
			return (Criteria)this;
		}

		public Criteria andMemberSexIsNotNull(){
			addCriterion("MEMBER_SEX is not null");
			return (Criteria)this;
		}

		public Criteria andMemberSexEqualTo(String value){
			addCriterion("MEMBER_SEX =",value,"memberSex");
			return (Criteria)this;
		}

		public Criteria andMemberSexNotEqualTo(String value){
			addCriterion("MEMBER_SEX <>",value,"memberSex");
			return (Criteria)this;
		}

		public Criteria andMemberSexGreaterThan(String value){
			addCriterion("MEMBER_SEX >",value,"memberSex");
			return (Criteria)this;
		}

		public Criteria andMemberSexGreaterThanOrEqualTo(String value){
			addCriterion("MEMBER_SEX >=",value,"memberSex");
			return (Criteria)this;
		}

		public Criteria andMemberSexLessThan(String value){
			addCriterion("MEMBER_SEX <",value,"memberSex");
			return (Criteria)this;
		}

		public Criteria andMemberSexLessThanOrEqualTo(String value){
			addCriterion("MEMBER_SEX <=",value,"memberSex");
			return (Criteria)this;
		}

		public Criteria andMemberSexLike(String value){
			addCriterion("MEMBER_SEX like",value,"memberSex");
			return (Criteria)this;
		}

		public Criteria andMemberSexNotLike(String value){
			addCriterion("MEMBER_SEX not like",value,"memberSex");
			return (Criteria)this;
		}

		public Criteria andMemberSexIn(List<String> values){
			addCriterion("MEMBER_SEX in",values,"memberSex");
			return (Criteria)this;
		}

		public Criteria andMemberSexNotIn(List<String> values){
			addCriterion("MEMBER_SEX not in",values,"memberSex");
			return (Criteria)this;
		}

		public Criteria andMemberSexBetween(String value1,String value2){
			addCriterion("MEMBER_SEX between",value1,value2,"memberSex");
			return (Criteria)this;
		}

		public Criteria andMemberSexNotBetween(String value1,String value2){
			addCriterion("MEMBER_SEX not between",value1,value2,"memberSex");
			return (Criteria)this;
		}

		public Criteria andMemberEmailIsNull(){
			addCriterion("MEMBER_EMAIL is null");
			return (Criteria)this;
		}

		public Criteria andMemberEmailIsNotNull(){
			addCriterion("MEMBER_EMAIL is not null");
			return (Criteria)this;
		}

		public Criteria andMemberEmailEqualTo(String value){
			addCriterion("MEMBER_EMAIL =",value,"memberEmail");
			return (Criteria)this;
		}

		public Criteria andMemberEmailNotEqualTo(String value){
			addCriterion("MEMBER_EMAIL <>",value,"memberEmail");
			return (Criteria)this;
		}

		public Criteria andMemberEmailGreaterThan(String value){
			addCriterion("MEMBER_EMAIL >",value,"memberEmail");
			return (Criteria)this;
		}

		public Criteria andMemberEmailGreaterThanOrEqualTo(String value){
			addCriterion("MEMBER_EMAIL >=",value,"memberEmail");
			return (Criteria)this;
		}

		public Criteria andMemberEmailLessThan(String value){
			addCriterion("MEMBER_EMAIL <",value,"memberEmail");
			return (Criteria)this;
		}

		public Criteria andMemberEmailLessThanOrEqualTo(String value){
			addCriterion("MEMBER_EMAIL <=",value,"memberEmail");
			return (Criteria)this;
		}

		public Criteria andMemberEmailLike(String value){
			addCriterion("MEMBER_EMAIL like",value,"memberEmail");
			return (Criteria)this;
		}

		public Criteria andMemberEmailNotLike(String value){
			addCriterion("MEMBER_EMAIL not like",value,"memberEmail");
			return (Criteria)this;
		}

		public Criteria andMemberEmailIn(List<String> values){
			addCriterion("MEMBER_EMAIL in",values,"memberEmail");
			return (Criteria)this;
		}

		public Criteria andMemberEmailNotIn(List<String> values){
			addCriterion("MEMBER_EMAIL not in",values,"memberEmail");
			return (Criteria)this;
		}

		public Criteria andMemberEmailBetween(String value1,String value2){
			addCriterion("MEMBER_EMAIL between",value1,value2,"memberEmail");
			return (Criteria)this;
		}

		public Criteria andMemberEmailNotBetween(String value1,String value2){
			addCriterion("MEMBER_EMAIL not between",value1,value2,"memberEmail");
			return (Criteria)this;
		}

		public Criteria andMemberPositionIsNull(){
			addCriterion("MEMBER_POSITION is null");
			return (Criteria)this;
		}

		public Criteria andMemberPositionIsNotNull(){
			addCriterion("MEMBER_POSITION is not null");
			return (Criteria)this;
		}

		public Criteria andMemberPositionEqualTo(String value){
			addCriterion("MEMBER_POSITION =",value,"memberPosition");
			return (Criteria)this;
		}

		public Criteria andMemberPositionNotEqualTo(String value){
			addCriterion("MEMBER_POSITION <>",value,"memberPosition");
			return (Criteria)this;
		}

		public Criteria andMemberPositionGreaterThan(String value){
			addCriterion("MEMBER_POSITION >",value,"memberPosition");
			return (Criteria)this;
		}

		public Criteria andMemberPositionGreaterThanOrEqualTo(String value){
			addCriterion("MEMBER_POSITION >=",value,"memberPosition");
			return (Criteria)this;
		}

		public Criteria andMemberPositionLessThan(String value){
			addCriterion("MEMBER_POSITION <",value,"memberPosition");
			return (Criteria)this;
		}

		public Criteria andMemberPositionLessThanOrEqualTo(String value){
			addCriterion("MEMBER_POSITION <=",value,"memberPosition");
			return (Criteria)this;
		}

		public Criteria andMemberPositionLike(String value){
			addCriterion("MEMBER_POSITION like",value,"memberPosition");
			return (Criteria)this;
		}

		public Criteria andMemberPositionNotLike(String value){
			addCriterion("MEMBER_POSITION not like",value,"memberPosition");
			return (Criteria)this;
		}

		public Criteria andMemberPositionIn(List<String> values){
			addCriterion("MEMBER_POSITION in",values,"memberPosition");
			return (Criteria)this;
		}

		public Criteria andMemberPositionNotIn(List<String> values){
			addCriterion("MEMBER_POSITION not in",values,"memberPosition");
			return (Criteria)this;
		}

		public Criteria andMemberPositionBetween(String value1,String value2){
			addCriterion("MEMBER_POSITION between",value1,value2,
					"memberPosition");
			return (Criteria)this;
		}

		public Criteria andMemberPositionNotBetween(String value1,String value2){
			addCriterion("MEMBER_POSITION not between",value1,value2,
					"memberPosition");
			return (Criteria)this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	public static class Criterion {
		private String	condition;
		private Object	value;
		private Object	secondValue;
		private boolean	noValue;
		private boolean	singleValue;
		private boolean	betweenValue;
		private boolean	listValue;
		private String	typeHandler;

		public String getCondition(){
			return condition;
		}

		public Object getValue(){
			return value;
		}

		public Object getSecondValue(){
			return secondValue;
		}

		public boolean isNoValue(){
			return noValue;
		}

		public boolean isSingleValue(){
			return singleValue;
		}

		public boolean isBetweenValue(){
			return betweenValue;
		}

		public boolean isListValue(){
			return listValue;
		}

		public String getTypeHandler(){
			return typeHandler;
		}

		protected Criterion(String condition){
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition,Object value,String typeHandler){
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if(value instanceof List<?>){
				this.listValue = true;
			} else{
				this.singleValue = true;
			}
		}

		protected Criterion(String condition,Object value){
			this(condition,value,null);
		}

		protected Criterion(String condition,Object value,Object secondValue,
				String typeHandler){
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition,Object value,Object secondValue){
			this(condition,value,secondValue,null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MEMBERS
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}