package cn.com.chinatelecom.pms.pojo;

import java.math.BigDecimal;

public class MemberGroup {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEMBER_GROUP.MEMBER_GROUP_ID
	 * @mbggenerated
	 */
	private String	memberGroupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEMBER_GROUP.MEMBER_GROUP_CODE
	 * @mbggenerated
	 */
	private BigDecimal	memberGroupCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEMBER_GROUP.MEMBER_GROUP_NAME
	 * @mbggenerated
	 */
	private String	memberGroupName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEMBER_GROUP.MEMBER_GROUP_DESC
	 * @mbggenerated
	 */
	private String	memberGroupDesc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEMBER_GROUP.MEMBER_GROUP_ID
	 * @return  the value of MEMBER_GROUP.MEMBER_GROUP_ID
	 * @mbggenerated
	 */
	public String getMemberGroupId(){
		return memberGroupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEMBER_GROUP.MEMBER_GROUP_ID
	 * @param memberGroupId  the value for MEMBER_GROUP.MEMBER_GROUP_ID
	 * @mbggenerated
	 */
	public void setMemberGroupId(String memberGroupId){
		this.memberGroupId = memberGroupId==null ? null : memberGroupId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEMBER_GROUP.MEMBER_GROUP_CODE
	 * @return  the value of MEMBER_GROUP.MEMBER_GROUP_CODE
	 * @mbggenerated
	 */
	public BigDecimal getMemberGroupCode(){
		return memberGroupCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEMBER_GROUP.MEMBER_GROUP_CODE
	 * @param memberGroupCode  the value for MEMBER_GROUP.MEMBER_GROUP_CODE
	 * @mbggenerated
	 */
	public void setMemberGroupCode(BigDecimal memberGroupCode){
		this.memberGroupCode = memberGroupCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEMBER_GROUP.MEMBER_GROUP_NAME
	 * @return  the value of MEMBER_GROUP.MEMBER_GROUP_NAME
	 * @mbggenerated
	 */
	public String getMemberGroupName(){
		return memberGroupName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEMBER_GROUP.MEMBER_GROUP_NAME
	 * @param memberGroupName  the value for MEMBER_GROUP.MEMBER_GROUP_NAME
	 * @mbggenerated
	 */
	public void setMemberGroupName(String memberGroupName){
		this.memberGroupName = memberGroupName==null ? null : memberGroupName
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEMBER_GROUP.MEMBER_GROUP_DESC
	 * @return  the value of MEMBER_GROUP.MEMBER_GROUP_DESC
	 * @mbggenerated
	 */
	public String getMemberGroupDesc(){
		return memberGroupDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEMBER_GROUP.MEMBER_GROUP_DESC
	 * @param memberGroupDesc  the value for MEMBER_GROUP.MEMBER_GROUP_DESC
	 * @mbggenerated
	 */
	public void setMemberGroupDesc(String memberGroupDesc){
		this.memberGroupDesc = memberGroupDesc==null ? null : memberGroupDesc
				.trim();
	}
}