package cn.com.chinatelecom.pms.pojo;

public class Members {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEMBERS.MEMBER_ID
	 * @mbggenerated
	 */
	private String	memberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEMBERS.MEMBER_GROUP_ID
	 * @mbggenerated
	 */
	private String	memberGroupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEMBERS.MEMBER_CODE
	 * @mbggenerated
	 */
	private String	memberCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEMBERS.MEMBER_NAME
	 * @mbggenerated
	 */
	private String	memberName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEMBERS.MEMBER_SEX
	 * @mbggenerated
	 */
	private String	memberSex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEMBERS.MEMBER_EMAIL
	 * @mbggenerated
	 */
	private String	memberEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEMBERS.MEMBER_POSITION
	 * @mbggenerated
	 */
	private String	memberPosition;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEMBERS.MEMBER_ID
	 * @return  the value of MEMBERS.MEMBER_ID
	 * @mbggenerated
	 */
	public String getMemberId(){
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEMBERS.MEMBER_ID
	 * @param memberId  the value for MEMBERS.MEMBER_ID
	 * @mbggenerated
	 */
	public void setMemberId(String memberId){
		this.memberId = memberId==null ? null : memberId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEMBERS.MEMBER_GROUP_ID
	 * @return  the value of MEMBERS.MEMBER_GROUP_ID
	 * @mbggenerated
	 */
	public String getMemberGroupId(){
		return memberGroupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEMBERS.MEMBER_GROUP_ID
	 * @param memberGroupId  the value for MEMBERS.MEMBER_GROUP_ID
	 * @mbggenerated
	 */
	public void setMemberGroupId(String memberGroupId){
		this.memberGroupId = memberGroupId==null ? null : memberGroupId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEMBERS.MEMBER_CODE
	 * @return  the value of MEMBERS.MEMBER_CODE
	 * @mbggenerated
	 */
	public String getMemberCode(){
		return memberCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEMBERS.MEMBER_CODE
	 * @param memberCode  the value for MEMBERS.MEMBER_CODE
	 * @mbggenerated
	 */
	public void setMemberCode(String memberCode){
		this.memberCode = memberCode==null ? null : memberCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEMBERS.MEMBER_NAME
	 * @return  the value of MEMBERS.MEMBER_NAME
	 * @mbggenerated
	 */
	public String getMemberName(){
		return memberName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEMBERS.MEMBER_NAME
	 * @param memberName  the value for MEMBERS.MEMBER_NAME
	 * @mbggenerated
	 */
	public void setMemberName(String memberName){
		this.memberName = memberName==null ? null : memberName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEMBERS.MEMBER_SEX
	 * @return  the value of MEMBERS.MEMBER_SEX
	 * @mbggenerated
	 */
	public String getMemberSex(){
		return memberSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEMBERS.MEMBER_SEX
	 * @param memberSex  the value for MEMBERS.MEMBER_SEX
	 * @mbggenerated
	 */
	public void setMemberSex(String memberSex){
		this.memberSex = memberSex==null ? null : memberSex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEMBERS.MEMBER_EMAIL
	 * @return  the value of MEMBERS.MEMBER_EMAIL
	 * @mbggenerated
	 */
	public String getMemberEmail(){
		return memberEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEMBERS.MEMBER_EMAIL
	 * @param memberEmail  the value for MEMBERS.MEMBER_EMAIL
	 * @mbggenerated
	 */
	public void setMemberEmail(String memberEmail){
		this.memberEmail = memberEmail==null ? null : memberEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEMBERS.MEMBER_POSITION
	 * @return  the value of MEMBERS.MEMBER_POSITION
	 * @mbggenerated
	 */
	public String getMemberPosition(){
		return memberPosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEMBERS.MEMBER_POSITION
	 * @param memberPosition  the value for MEMBERS.MEMBER_POSITION
	 * @mbggenerated
	 */
	public void setMemberPosition(String memberPosition){
		this.memberPosition = memberPosition==null ? null : memberPosition
				.trim();
	}
}