package cn.com.chinatelecom.pms.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ModuleExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table MODULE
	 * @mbggenerated
	 */
	protected String	orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table MODULE
	 * @mbggenerated
	 */
	protected boolean	distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table MODULE
	 * @mbggenerated
	 */
	protected List<Criteria>	oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	public ModuleExample(){
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause){
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	public String getOrderByClause(){
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct){
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	public boolean isDistinct(){
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria(){
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	public void or(Criteria criteria){
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	public Criteria or(){
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	public Criteria createCriteria(){
		Criteria criteria = createCriteriaInternal();
		if(oredCriteria.size()==0){
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal(){
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	public void clear(){
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table MODULE
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion>	criteria;

		protected GeneratedCriteria(){
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid(){
			return criteria.size()>0;
		}

		public List<Criterion> getAllCriteria(){
			return criteria;
		}

		public List<Criterion> getCriteria(){
			return criteria;
		}

		protected void addCriterion(String condition){
			if(condition==null){
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition,Object value,
				String property){
			if(value==null){
				throw new RuntimeException("Value for "+property
						+" cannot be null");
			}
			criteria.add(new Criterion(condition,value));
		}

		protected void addCriterion(String condition,Object value1,
				Object value2,String property){
			if(value1==null||value2==null){
				throw new RuntimeException("Between values for "+property
						+" cannot be null");
			}
			criteria.add(new Criterion(condition,value1,value2));
		}

		public Criteria andModuleIdIsNull(){
			addCriterion("MODULE_ID is null");
			return (Criteria)this;
		}

		public Criteria andModuleIdIsNotNull(){
			addCriterion("MODULE_ID is not null");
			return (Criteria)this;
		}

		public Criteria andModuleIdEqualTo(String value){
			addCriterion("MODULE_ID =",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdNotEqualTo(String value){
			addCriterion("MODULE_ID <>",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdGreaterThan(String value){
			addCriterion("MODULE_ID >",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdGreaterThanOrEqualTo(String value){
			addCriterion("MODULE_ID >=",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdLessThan(String value){
			addCriterion("MODULE_ID <",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdLessThanOrEqualTo(String value){
			addCriterion("MODULE_ID <=",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdLike(String value){
			addCriterion("MODULE_ID like",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdNotLike(String value){
			addCriterion("MODULE_ID not like",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdIn(List<String> values){
			addCriterion("MODULE_ID in",values,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdNotIn(List<String> values){
			addCriterion("MODULE_ID not in",values,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdBetween(String value1,String value2){
			addCriterion("MODULE_ID between",value1,value2,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdNotBetween(String value1,String value2){
			addCriterion("MODULE_ID not between",value1,value2,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleCodeIsNull(){
			addCriterion("MODULE_CODE is null");
			return (Criteria)this;
		}

		public Criteria andModuleCodeIsNotNull(){
			addCriterion("MODULE_CODE is not null");
			return (Criteria)this;
		}

		public Criteria andModuleCodeEqualTo(BigDecimal value){
			addCriterion("MODULE_CODE =",value,"moduleCode");
			return (Criteria)this;
		}

		public Criteria andModuleCodeNotEqualTo(BigDecimal value){
			addCriterion("MODULE_CODE <>",value,"moduleCode");
			return (Criteria)this;
		}

		public Criteria andModuleCodeGreaterThan(BigDecimal value){
			addCriterion("MODULE_CODE >",value,"moduleCode");
			return (Criteria)this;
		}

		public Criteria andModuleCodeGreaterThanOrEqualTo(BigDecimal value){
			addCriterion("MODULE_CODE >=",value,"moduleCode");
			return (Criteria)this;
		}

		public Criteria andModuleCodeLessThan(BigDecimal value){
			addCriterion("MODULE_CODE <",value,"moduleCode");
			return (Criteria)this;
		}

		public Criteria andModuleCodeLessThanOrEqualTo(BigDecimal value){
			addCriterion("MODULE_CODE <=",value,"moduleCode");
			return (Criteria)this;
		}

		public Criteria andModuleCodeIn(List<BigDecimal> values){
			addCriterion("MODULE_CODE in",values,"moduleCode");
			return (Criteria)this;
		}

		public Criteria andModuleCodeNotIn(List<BigDecimal> values){
			addCriterion("MODULE_CODE not in",values,"moduleCode");
			return (Criteria)this;
		}

		public Criteria andModuleCodeBetween(BigDecimal value1,BigDecimal value2){
			addCriterion("MODULE_CODE between",value1,value2,"moduleCode");
			return (Criteria)this;
		}

		public Criteria andModuleCodeNotBetween(BigDecimal value1,
				BigDecimal value2){
			addCriterion("MODULE_CODE not between",value1,value2,"moduleCode");
			return (Criteria)this;
		}

		public Criteria andModuleNameIsNull(){
			addCriterion("MODULE_NAME is null");
			return (Criteria)this;
		}

		public Criteria andModuleNameIsNotNull(){
			addCriterion("MODULE_NAME is not null");
			return (Criteria)this;
		}

		public Criteria andModuleNameEqualTo(String value){
			addCriterion("MODULE_NAME =",value,"moduleName");
			return (Criteria)this;
		}

		public Criteria andModuleNameNotEqualTo(String value){
			addCriterion("MODULE_NAME <>",value,"moduleName");
			return (Criteria)this;
		}

		public Criteria andModuleNameGreaterThan(String value){
			addCriterion("MODULE_NAME >",value,"moduleName");
			return (Criteria)this;
		}

		public Criteria andModuleNameGreaterThanOrEqualTo(String value){
			addCriterion("MODULE_NAME >=",value,"moduleName");
			return (Criteria)this;
		}

		public Criteria andModuleNameLessThan(String value){
			addCriterion("MODULE_NAME <",value,"moduleName");
			return (Criteria)this;
		}

		public Criteria andModuleNameLessThanOrEqualTo(String value){
			addCriterion("MODULE_NAME <=",value,"moduleName");
			return (Criteria)this;
		}

		public Criteria andModuleNameLike(String value){
			addCriterion("MODULE_NAME like",value,"moduleName");
			return (Criteria)this;
		}

		public Criteria andModuleNameNotLike(String value){
			addCriterion("MODULE_NAME not like",value,"moduleName");
			return (Criteria)this;
		}

		public Criteria andModuleNameIn(List<String> values){
			addCriterion("MODULE_NAME in",values,"moduleName");
			return (Criteria)this;
		}

		public Criteria andModuleNameNotIn(List<String> values){
			addCriterion("MODULE_NAME not in",values,"moduleName");
			return (Criteria)this;
		}

		public Criteria andModuleNameBetween(String value1,String value2){
			addCriterion("MODULE_NAME between",value1,value2,"moduleName");
			return (Criteria)this;
		}

		public Criteria andModuleNameNotBetween(String value1,String value2){
			addCriterion("MODULE_NAME not between",value1,value2,"moduleName");
			return (Criteria)this;
		}

		public Criteria andModuleDescIsNull(){
			addCriterion("MODULE_DESC is null");
			return (Criteria)this;
		}

		public Criteria andModuleDescIsNotNull(){
			addCriterion("MODULE_DESC is not null");
			return (Criteria)this;
		}

		public Criteria andModuleDescEqualTo(String value){
			addCriterion("MODULE_DESC =",value,"moduleDesc");
			return (Criteria)this;
		}

		public Criteria andModuleDescNotEqualTo(String value){
			addCriterion("MODULE_DESC <>",value,"moduleDesc");
			return (Criteria)this;
		}

		public Criteria andModuleDescGreaterThan(String value){
			addCriterion("MODULE_DESC >",value,"moduleDesc");
			return (Criteria)this;
		}

		public Criteria andModuleDescGreaterThanOrEqualTo(String value){
			addCriterion("MODULE_DESC >=",value,"moduleDesc");
			return (Criteria)this;
		}

		public Criteria andModuleDescLessThan(String value){
			addCriterion("MODULE_DESC <",value,"moduleDesc");
			return (Criteria)this;
		}

		public Criteria andModuleDescLessThanOrEqualTo(String value){
			addCriterion("MODULE_DESC <=",value,"moduleDesc");
			return (Criteria)this;
		}

		public Criteria andModuleDescLike(String value){
			addCriterion("MODULE_DESC like",value,"moduleDesc");
			return (Criteria)this;
		}

		public Criteria andModuleDescNotLike(String value){
			addCriterion("MODULE_DESC not like",value,"moduleDesc");
			return (Criteria)this;
		}

		public Criteria andModuleDescIn(List<String> values){
			addCriterion("MODULE_DESC in",values,"moduleDesc");
			return (Criteria)this;
		}

		public Criteria andModuleDescNotIn(List<String> values){
			addCriterion("MODULE_DESC not in",values,"moduleDesc");
			return (Criteria)this;
		}

		public Criteria andModuleDescBetween(String value1,String value2){
			addCriterion("MODULE_DESC between",value1,value2,"moduleDesc");
			return (Criteria)this;
		}

		public Criteria andModuleDescNotBetween(String value1,String value2){
			addCriterion("MODULE_DESC not between",value1,value2,"moduleDesc");
			return (Criteria)this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table MODULE
	 * @mbggenerated
	 */
	public static class Criterion {
		private String	condition;
		private Object	value;
		private Object	secondValue;
		private boolean	noValue;
		private boolean	singleValue;
		private boolean	betweenValue;
		private boolean	listValue;
		private String	typeHandler;

		public String getCondition(){
			return condition;
		}

		public Object getValue(){
			return value;
		}

		public Object getSecondValue(){
			return secondValue;
		}

		public boolean isNoValue(){
			return noValue;
		}

		public boolean isSingleValue(){
			return singleValue;
		}

		public boolean isBetweenValue(){
			return betweenValue;
		}

		public boolean isListValue(){
			return listValue;
		}

		public String getTypeHandler(){
			return typeHandler;
		}

		protected Criterion(String condition){
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition,Object value,String typeHandler){
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if(value instanceof List<?>){
				this.listValue = true;
			} else{
				this.singleValue = true;
			}
		}

		protected Criterion(String condition,Object value){
			this(condition,value,null);
		}

		protected Criterion(String condition,Object value,Object secondValue,
				String typeHandler){
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition,Object value,Object secondValue){
			this(condition,value,secondValue,null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MODULE
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}