package cn.com.chinatelecom.pms.pojo;

import java.math.BigDecimal;

public class Module {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODULE.MODULE_ID
     *
     * @mbggenerated
     */
    private String moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODULE.MODULE_CODE
     *
     * @mbggenerated
     */
    private BigDecimal moduleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODULE.MODULE_NAME
     *
     * @mbggenerated
     */
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODULE.MODULE_DESC
     *
     * @mbggenerated
     */
    private String moduleDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODULE.MODULE_ID
     *
     * @return the value of MODULE.MODULE_ID
     *
     * @mbggenerated
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODULE.MODULE_ID
     *
     * @param moduleId the value for MODULE.MODULE_ID
     *
     * @mbggenerated
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODULE.MODULE_CODE
     *
     * @return the value of MODULE.MODULE_CODE
     *
     * @mbggenerated
     */
    public BigDecimal getModuleCode() {
        return moduleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODULE.MODULE_CODE
     *
     * @param moduleCode the value for MODULE.MODULE_CODE
     *
     * @mbggenerated
     */
    public void setModuleCode(BigDecimal moduleCode) {
        this.moduleCode = moduleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODULE.MODULE_NAME
     *
     * @return the value of MODULE.MODULE_NAME
     *
     * @mbggenerated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODULE.MODULE_NAME
     *
     * @param moduleName the value for MODULE.MODULE_NAME
     *
     * @mbggenerated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODULE.MODULE_DESC
     *
     * @return the value of MODULE.MODULE_DESC
     *
     * @mbggenerated
     */
    public String getModuleDesc() {
        return moduleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODULE.MODULE_DESC
     *
     * @param moduleDesc the value for MODULE.MODULE_DESC
     *
     * @mbggenerated
     */
    public void setModuleDesc(String moduleDesc) {
        this.moduleDesc = moduleDesc == null ? null : moduleDesc.trim();
    }
}