package cn.com.chinatelecom.pms.pojo;

import java.io.Serializable;
import java.util.Date;

public class OperationLogs implements Serializable {
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECT_OPERATION_LOGS.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECT_OPERATION_LOGS.TIME
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECT_OPERATION_LOGS.LEVEL_INFO
     *
     * @mbggenerated
     */
    private String levelInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECT_OPERATION_LOGS.HOST_NAME
     *
     * @mbggenerated
     */
    private String hostName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECT_OPERATION_LOGS.THREAD
     *
     * @mbggenerated
     */
    private String thread;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECT_OPERATION_LOGS.USER_INFO
     *
     * @mbggenerated
     */
    private String userInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECT_OPERATION_LOGS.URL
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECT_OPERATION_LOGS.WITH_TIME
     *
     * @mbggenerated
     */
    private String withTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECT_OPERATION_LOGS.PARAMETER
     *
     * @mbggenerated
     */
    private String parameter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECT_OPERATION_LOGS.ID
     *
     * @return the value of ECT_OPERATION_LOGS.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECT_OPERATION_LOGS.ID
     *
     * @param id the value for ECT_OPERATION_LOGS.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECT_OPERATION_LOGS.TIME
     *
     * @return the value of ECT_OPERATION_LOGS.TIME
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECT_OPERATION_LOGS.TIME
     *
     * @param time the value for ECT_OPERATION_LOGS.TIME
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECT_OPERATION_LOGS.LEVEL_INFO
     *
     * @return the value of ECT_OPERATION_LOGS.LEVEL_INFO
     *
     * @mbggenerated
     */
    public String getLevelInfo() {
        return levelInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECT_OPERATION_LOGS.LEVEL_INFO
     *
     * @param levelInfo the value for ECT_OPERATION_LOGS.LEVEL_INFO
     *
     * @mbggenerated
     */
    public void setLevelInfo(String levelInfo) {
        this.levelInfo = levelInfo == null ? null : levelInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECT_OPERATION_LOGS.HOST_NAME
     *
     * @return the value of ECT_OPERATION_LOGS.HOST_NAME
     *
     * @mbggenerated
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECT_OPERATION_LOGS.HOST_NAME
     *
     * @param hostName the value for ECT_OPERATION_LOGS.HOST_NAME
     *
     * @mbggenerated
     */
    public void setHostName(String hostName) {
        this.hostName = hostName == null ? null : hostName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECT_OPERATION_LOGS.THREAD
     *
     * @return the value of ECT_OPERATION_LOGS.THREAD
     *
     * @mbggenerated
     */
    public String getThread() {
        return thread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECT_OPERATION_LOGS.THREAD
     *
     * @param thread the value for ECT_OPERATION_LOGS.THREAD
     *
     * @mbggenerated
     */
    public void setThread(String thread) {
        this.thread = thread == null ? null : thread.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECT_OPERATION_LOGS.USER_INFO
     *
     * @return the value of ECT_OPERATION_LOGS.USER_INFO
     *
     * @mbggenerated
     */
    public String getUserInfo() {
        return userInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECT_OPERATION_LOGS.USER_INFO
     *
     * @param userInfo the value for ECT_OPERATION_LOGS.USER_INFO
     *
     * @mbggenerated
     */
    public void setUserInfo(String userInfo) {
        this.userInfo = userInfo == null ? null : userInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECT_OPERATION_LOGS.URL
     *
     * @return the value of ECT_OPERATION_LOGS.URL
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECT_OPERATION_LOGS.URL
     *
     * @param url the value for ECT_OPERATION_LOGS.URL
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECT_OPERATION_LOGS.WITH_TIME
     *
     * @return the value of ECT_OPERATION_LOGS.WITH_TIME
     *
     * @mbggenerated
     */
    public String getWithTime() {
        return withTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECT_OPERATION_LOGS.WITH_TIME
     *
     * @param withTime the value for ECT_OPERATION_LOGS.WITH_TIME
     *
     * @mbggenerated
     */
    public void setWithTime(String withTime) {
        this.withTime = withTime == null ? null : withTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECT_OPERATION_LOGS.PARAMETER
     *
     * @return the value of ECT_OPERATION_LOGS.PARAMETER
     *
     * @mbggenerated
     */
    public String getParameter() {
        return parameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECT_OPERATION_LOGS.PARAMETER
     *
     * @param parameter the value for ECT_OPERATION_LOGS.PARAMETER
     *
     * @mbggenerated
     */
    public void setParameter(String parameter) {
        this.parameter = parameter == null ? null : parameter.trim();
    }
    
    private static final long serialVersionUID = -8182279972281599885L;
}