package cn.com.chinatelecom.pms.pojo;

import java.math.BigDecimal;

public class Process {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROCESS.PROCESS_ID
	 * @mbggenerated
	 */
	private String	processId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROCESS.PROCESS_CODE
	 * @mbggenerated
	 */
	private BigDecimal	processCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROCESS.PROCESS_NAME
	 * @mbggenerated
	 */
	private String	processName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROCESS.PROCESS_DESC
	 * @mbggenerated
	 */
	private String	processDesc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROCESS.PROCESS_ID
	 * @return  the value of PROCESS.PROCESS_ID
	 * @mbggenerated
	 */
	public String getProcessId(){
		return processId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROCESS.PROCESS_ID
	 * @param processId  the value for PROCESS.PROCESS_ID
	 * @mbggenerated
	 */
	public void setProcessId(String processId){
		this.processId = processId==null ? null : processId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROCESS.PROCESS_CODE
	 * @return  the value of PROCESS.PROCESS_CODE
	 * @mbggenerated
	 */
	public BigDecimal getProcessCode(){
		return processCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROCESS.PROCESS_CODE
	 * @param processCode  the value for PROCESS.PROCESS_CODE
	 * @mbggenerated
	 */
	public void setProcessCode(BigDecimal processCode){
		this.processCode = processCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROCESS.PROCESS_NAME
	 * @return  the value of PROCESS.PROCESS_NAME
	 * @mbggenerated
	 */
	public String getProcessName(){
		return processName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROCESS.PROCESS_NAME
	 * @param processName  the value for PROCESS.PROCESS_NAME
	 * @mbggenerated
	 */
	public void setProcessName(String processName){
		this.processName = processName==null ? null : processName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROCESS.PROCESS_DESC
	 * @return  the value of PROCESS.PROCESS_DESC
	 * @mbggenerated
	 */
	public String getProcessDesc(){
		return processDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROCESS.PROCESS_DESC
	 * @param processDesc  the value for PROCESS.PROCESS_DESC
	 * @mbggenerated
	 */
	public void setProcessDesc(String processDesc){
		this.processDesc = processDesc==null ? null : processDesc.trim();
	}
}