package cn.com.chinatelecom.pms.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ProcessExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	protected String	orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	protected boolean	distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	protected List<Criteria>	oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	public ProcessExample(){
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause){
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	public String getOrderByClause(){
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct){
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	public boolean isDistinct(){
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria(){
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	public void or(Criteria criteria){
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	public Criteria or(){
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	public Criteria createCriteria(){
		Criteria criteria = createCriteriaInternal();
		if(oredCriteria.size()==0){
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal(){
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	public void clear(){
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion>	criteria;

		protected GeneratedCriteria(){
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid(){
			return criteria.size()>0;
		}

		public List<Criterion> getAllCriteria(){
			return criteria;
		}

		public List<Criterion> getCriteria(){
			return criteria;
		}

		protected void addCriterion(String condition){
			if(condition==null){
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition,Object value,
				String property){
			if(value==null){
				throw new RuntimeException("Value for "+property
						+" cannot be null");
			}
			criteria.add(new Criterion(condition,value));
		}

		protected void addCriterion(String condition,Object value1,
				Object value2,String property){
			if(value1==null||value2==null){
				throw new RuntimeException("Between values for "+property
						+" cannot be null");
			}
			criteria.add(new Criterion(condition,value1,value2));
		}

		public Criteria andProcessIdIsNull(){
			addCriterion("PROCESS_ID is null");
			return (Criteria)this;
		}

		public Criteria andProcessIdIsNotNull(){
			addCriterion("PROCESS_ID is not null");
			return (Criteria)this;
		}

		public Criteria andProcessIdEqualTo(String value){
			addCriterion("PROCESS_ID =",value,"processId");
			return (Criteria)this;
		}

		public Criteria andProcessIdNotEqualTo(String value){
			addCriterion("PROCESS_ID <>",value,"processId");
			return (Criteria)this;
		}

		public Criteria andProcessIdGreaterThan(String value){
			addCriterion("PROCESS_ID >",value,"processId");
			return (Criteria)this;
		}

		public Criteria andProcessIdGreaterThanOrEqualTo(String value){
			addCriterion("PROCESS_ID >=",value,"processId");
			return (Criteria)this;
		}

		public Criteria andProcessIdLessThan(String value){
			addCriterion("PROCESS_ID <",value,"processId");
			return (Criteria)this;
		}

		public Criteria andProcessIdLessThanOrEqualTo(String value){
			addCriterion("PROCESS_ID <=",value,"processId");
			return (Criteria)this;
		}

		public Criteria andProcessIdLike(String value){
			addCriterion("PROCESS_ID like",value,"processId");
			return (Criteria)this;
		}

		public Criteria andProcessIdNotLike(String value){
			addCriterion("PROCESS_ID not like",value,"processId");
			return (Criteria)this;
		}

		public Criteria andProcessIdIn(List<String> values){
			addCriterion("PROCESS_ID in",values,"processId");
			return (Criteria)this;
		}

		public Criteria andProcessIdNotIn(List<String> values){
			addCriterion("PROCESS_ID not in",values,"processId");
			return (Criteria)this;
		}

		public Criteria andProcessIdBetween(String value1,String value2){
			addCriterion("PROCESS_ID between",value1,value2,"processId");
			return (Criteria)this;
		}

		public Criteria andProcessIdNotBetween(String value1,String value2){
			addCriterion("PROCESS_ID not between",value1,value2,"processId");
			return (Criteria)this;
		}

		public Criteria andProcessCodeIsNull(){
			addCriterion("PROCESS_CODE is null");
			return (Criteria)this;
		}

		public Criteria andProcessCodeIsNotNull(){
			addCriterion("PROCESS_CODE is not null");
			return (Criteria)this;
		}

		public Criteria andProcessCodeEqualTo(BigDecimal value){
			addCriterion("PROCESS_CODE =",value,"processCode");
			return (Criteria)this;
		}

		public Criteria andProcessCodeNotEqualTo(BigDecimal value){
			addCriterion("PROCESS_CODE <>",value,"processCode");
			return (Criteria)this;
		}

		public Criteria andProcessCodeGreaterThan(BigDecimal value){
			addCriterion("PROCESS_CODE >",value,"processCode");
			return (Criteria)this;
		}

		public Criteria andProcessCodeGreaterThanOrEqualTo(BigDecimal value){
			addCriterion("PROCESS_CODE >=",value,"processCode");
			return (Criteria)this;
		}

		public Criteria andProcessCodeLessThan(BigDecimal value){
			addCriterion("PROCESS_CODE <",value,"processCode");
			return (Criteria)this;
		}

		public Criteria andProcessCodeLessThanOrEqualTo(BigDecimal value){
			addCriterion("PROCESS_CODE <=",value,"processCode");
			return (Criteria)this;
		}

		public Criteria andProcessCodeIn(List<BigDecimal> values){
			addCriterion("PROCESS_CODE in",values,"processCode");
			return (Criteria)this;
		}

		public Criteria andProcessCodeNotIn(List<BigDecimal> values){
			addCriterion("PROCESS_CODE not in",values,"processCode");
			return (Criteria)this;
		}

		public Criteria andProcessCodeBetween(BigDecimal value1,
				BigDecimal value2){
			addCriterion("PROCESS_CODE between",value1,value2,"processCode");
			return (Criteria)this;
		}

		public Criteria andProcessCodeNotBetween(BigDecimal value1,
				BigDecimal value2){
			addCriterion("PROCESS_CODE not between",value1,value2,"processCode");
			return (Criteria)this;
		}

		public Criteria andProcessNameIsNull(){
			addCriterion("PROCESS_NAME is null");
			return (Criteria)this;
		}

		public Criteria andProcessNameIsNotNull(){
			addCriterion("PROCESS_NAME is not null");
			return (Criteria)this;
		}

		public Criteria andProcessNameEqualTo(String value){
			addCriterion("PROCESS_NAME =",value,"processName");
			return (Criteria)this;
		}

		public Criteria andProcessNameNotEqualTo(String value){
			addCriterion("PROCESS_NAME <>",value,"processName");
			return (Criteria)this;
		}

		public Criteria andProcessNameGreaterThan(String value){
			addCriterion("PROCESS_NAME >",value,"processName");
			return (Criteria)this;
		}

		public Criteria andProcessNameGreaterThanOrEqualTo(String value){
			addCriterion("PROCESS_NAME >=",value,"processName");
			return (Criteria)this;
		}

		public Criteria andProcessNameLessThan(String value){
			addCriterion("PROCESS_NAME <",value,"processName");
			return (Criteria)this;
		}

		public Criteria andProcessNameLessThanOrEqualTo(String value){
			addCriterion("PROCESS_NAME <=",value,"processName");
			return (Criteria)this;
		}

		public Criteria andProcessNameLike(String value){
			addCriterion("PROCESS_NAME like",value,"processName");
			return (Criteria)this;
		}

		public Criteria andProcessNameNotLike(String value){
			addCriterion("PROCESS_NAME not like",value,"processName");
			return (Criteria)this;
		}

		public Criteria andProcessNameIn(List<String> values){
			addCriterion("PROCESS_NAME in",values,"processName");
			return (Criteria)this;
		}

		public Criteria andProcessNameNotIn(List<String> values){
			addCriterion("PROCESS_NAME not in",values,"processName");
			return (Criteria)this;
		}

		public Criteria andProcessNameBetween(String value1,String value2){
			addCriterion("PROCESS_NAME between",value1,value2,"processName");
			return (Criteria)this;
		}

		public Criteria andProcessNameNotBetween(String value1,String value2){
			addCriterion("PROCESS_NAME not between",value1,value2,"processName");
			return (Criteria)this;
		}

		public Criteria andProcessDescIsNull(){
			addCriterion("PROCESS_DESC is null");
			return (Criteria)this;
		}

		public Criteria andProcessDescIsNotNull(){
			addCriterion("PROCESS_DESC is not null");
			return (Criteria)this;
		}

		public Criteria andProcessDescEqualTo(String value){
			addCriterion("PROCESS_DESC =",value,"processDesc");
			return (Criteria)this;
		}

		public Criteria andProcessDescNotEqualTo(String value){
			addCriterion("PROCESS_DESC <>",value,"processDesc");
			return (Criteria)this;
		}

		public Criteria andProcessDescGreaterThan(String value){
			addCriterion("PROCESS_DESC >",value,"processDesc");
			return (Criteria)this;
		}

		public Criteria andProcessDescGreaterThanOrEqualTo(String value){
			addCriterion("PROCESS_DESC >=",value,"processDesc");
			return (Criteria)this;
		}

		public Criteria andProcessDescLessThan(String value){
			addCriterion("PROCESS_DESC <",value,"processDesc");
			return (Criteria)this;
		}

		public Criteria andProcessDescLessThanOrEqualTo(String value){
			addCriterion("PROCESS_DESC <=",value,"processDesc");
			return (Criteria)this;
		}

		public Criteria andProcessDescLike(String value){
			addCriterion("PROCESS_DESC like",value,"processDesc");
			return (Criteria)this;
		}

		public Criteria andProcessDescNotLike(String value){
			addCriterion("PROCESS_DESC not like",value,"processDesc");
			return (Criteria)this;
		}

		public Criteria andProcessDescIn(List<String> values){
			addCriterion("PROCESS_DESC in",values,"processDesc");
			return (Criteria)this;
		}

		public Criteria andProcessDescNotIn(List<String> values){
			addCriterion("PROCESS_DESC not in",values,"processDesc");
			return (Criteria)this;
		}

		public Criteria andProcessDescBetween(String value1,String value2){
			addCriterion("PROCESS_DESC between",value1,value2,"processDesc");
			return (Criteria)this;
		}

		public Criteria andProcessDescNotBetween(String value1,String value2){
			addCriterion("PROCESS_DESC not between",value1,value2,"processDesc");
			return (Criteria)this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	public static class Criterion {
		private String	condition;
		private Object	value;
		private Object	secondValue;
		private boolean	noValue;
		private boolean	singleValue;
		private boolean	betweenValue;
		private boolean	listValue;
		private String	typeHandler;

		public String getCondition(){
			return condition;
		}

		public Object getValue(){
			return value;
		}

		public Object getSecondValue(){
			return secondValue;
		}

		public boolean isNoValue(){
			return noValue;
		}

		public boolean isSingleValue(){
			return singleValue;
		}

		public boolean isBetweenValue(){
			return betweenValue;
		}

		public boolean isListValue(){
			return listValue;
		}

		public String getTypeHandler(){
			return typeHandler;
		}

		protected Criterion(String condition){
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition,Object value,String typeHandler){
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if(value instanceof List<?>){
				this.listValue = true;
			} else{
				this.singleValue = true;
			}
		}

		protected Criterion(String condition,Object value){
			this(condition,value,null);
		}

		protected Criterion(String condition,Object value,Object secondValue,
				String typeHandler){
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition,Object value,Object secondValue){
			this(condition,value,secondValue,null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PROCESS
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}