package cn.com.chinatelecom.pms.pojo;

public class ProjecGtroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROJECT_GROUP.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROJECT_GROUP.GROUP_NAME
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROJECT_GROUP.ID
     *
     * @return the value of T_PROJECT_GROUP.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROJECT_GROUP.ID
     *
     * @param id the value for T_PROJECT_GROUP.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROJECT_GROUP.GROUP_NAME
     *
     * @return the value of T_PROJECT_GROUP.GROUP_NAME
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROJECT_GROUP.GROUP_NAME
     *
     * @param groupName the value for T_PROJECT_GROUP.GROUP_NAME
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }
}