package cn.com.chinatelecom.pms.pojo;

import java.math.BigDecimal;

public class RequirePriority {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REQUIRE_PRIORITY.PRIORITY_ID
     *
     * @mbggenerated
     */
    private String priorityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REQUIRE_PRIORITY.PRIORITY_CODE
     *
     * @mbggenerated
     */
    private BigDecimal priorityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REQUIRE_PRIORITY.PRIORITY_NAME
     *
     * @mbggenerated
     */
    private String priorityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REQUIRE_PRIORITY.PRIORITY_DESC
     *
     * @mbggenerated
     */
    private String priorityDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REQUIRE_PRIORITY.PRIORITY_ID
     *
     * @return the value of REQUIRE_PRIORITY.PRIORITY_ID
     *
     * @mbggenerated
     */
    public String getPriorityId() {
        return priorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REQUIRE_PRIORITY.PRIORITY_ID
     *
     * @param priorityId the value for REQUIRE_PRIORITY.PRIORITY_ID
     *
     * @mbggenerated
     */
    public void setPriorityId(String priorityId) {
        this.priorityId = priorityId == null ? null : priorityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REQUIRE_PRIORITY.PRIORITY_CODE
     *
     * @return the value of REQUIRE_PRIORITY.PRIORITY_CODE
     *
     * @mbggenerated
     */
    public BigDecimal getPriorityCode() {
        return priorityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REQUIRE_PRIORITY.PRIORITY_CODE
     *
     * @param priorityCode the value for REQUIRE_PRIORITY.PRIORITY_CODE
     *
     * @mbggenerated
     */
    public void setPriorityCode(BigDecimal priorityCode) {
        this.priorityCode = priorityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REQUIRE_PRIORITY.PRIORITY_NAME
     *
     * @return the value of REQUIRE_PRIORITY.PRIORITY_NAME
     *
     * @mbggenerated
     */
    public String getPriorityName() {
        return priorityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REQUIRE_PRIORITY.PRIORITY_NAME
     *
     * @param priorityName the value for REQUIRE_PRIORITY.PRIORITY_NAME
     *
     * @mbggenerated
     */
    public void setPriorityName(String priorityName) {
        this.priorityName = priorityName == null ? null : priorityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REQUIRE_PRIORITY.PRIORITY_DESC
     *
     * @return the value of REQUIRE_PRIORITY.PRIORITY_DESC
     *
     * @mbggenerated
     */
    public String getPriorityDesc() {
        return priorityDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REQUIRE_PRIORITY.PRIORITY_DESC
     *
     * @param priorityDesc the value for REQUIRE_PRIORITY.PRIORITY_DESC
     *
     * @mbggenerated
     */
    public void setPriorityDesc(String priorityDesc) {
        this.priorityDesc = priorityDesc == null ? null : priorityDesc.trim();
    }
}