package cn.com.chinatelecom.pms.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class RequireKindExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	protected String	orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	protected boolean	distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	protected List<Criteria>	oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	public RequireKindExample(){
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause){
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	public String getOrderByClause(){
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct){
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	public boolean isDistinct(){
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria(){
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	public void or(Criteria criteria){
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	public Criteria or(){
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	public Criteria createCriteria(){
		Criteria criteria = createCriteriaInternal();
		if(oredCriteria.size()==0){
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal(){
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	public void clear(){
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion>	criteria;

		protected GeneratedCriteria(){
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid(){
			return criteria.size()>0;
		}

		public List<Criterion> getAllCriteria(){
			return criteria;
		}

		public List<Criterion> getCriteria(){
			return criteria;
		}

		protected void addCriterion(String condition){
			if(condition==null){
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition,Object value,
				String property){
			if(value==null){
				throw new RuntimeException("Value for "+property
						+" cannot be null");
			}
			criteria.add(new Criterion(condition,value));
		}

		protected void addCriterion(String condition,Object value1,
				Object value2,String property){
			if(value1==null||value2==null){
				throw new RuntimeException("Between values for "+property
						+" cannot be null");
			}
			criteria.add(new Criterion(condition,value1,value2));
		}

		public Criteria andRequireKindIdIsNull(){
			addCriterion("REQUIRE_KIND_ID is null");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdIsNotNull(){
			addCriterion("REQUIRE_KIND_ID is not null");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdEqualTo(String value){
			addCriterion("REQUIRE_KIND_ID =",value,"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdNotEqualTo(String value){
			addCriterion("REQUIRE_KIND_ID <>",value,"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdGreaterThan(String value){
			addCriterion("REQUIRE_KIND_ID >",value,"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdGreaterThanOrEqualTo(String value){
			addCriterion("REQUIRE_KIND_ID >=",value,"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdLessThan(String value){
			addCriterion("REQUIRE_KIND_ID <",value,"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdLessThanOrEqualTo(String value){
			addCriterion("REQUIRE_KIND_ID <=",value,"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdLike(String value){
			addCriterion("REQUIRE_KIND_ID like",value,"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdNotLike(String value){
			addCriterion("REQUIRE_KIND_ID not like",value,"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdIn(List<String> values){
			addCriterion("REQUIRE_KIND_ID in",values,"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdNotIn(List<String> values){
			addCriterion("REQUIRE_KIND_ID not in",values,"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdBetween(String value1,String value2){
			addCriterion("REQUIRE_KIND_ID between",value1,value2,
					"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdNotBetween(String value1,String value2){
			addCriterion("REQUIRE_KIND_ID not between",value1,value2,
					"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindCodeIsNull(){
			addCriterion("REQUIRE_KIND_CODE is null");
			return (Criteria)this;
		}

		public Criteria andRequireKindCodeIsNotNull(){
			addCriterion("REQUIRE_KIND_CODE is not null");
			return (Criteria)this;
		}

		public Criteria andRequireKindCodeEqualTo(BigDecimal value){
			addCriterion("REQUIRE_KIND_CODE =",value,"requireKindCode");
			return (Criteria)this;
		}

		public Criteria andRequireKindCodeNotEqualTo(BigDecimal value){
			addCriterion("REQUIRE_KIND_CODE <>",value,"requireKindCode");
			return (Criteria)this;
		}

		public Criteria andRequireKindCodeGreaterThan(BigDecimal value){
			addCriterion("REQUIRE_KIND_CODE >",value,"requireKindCode");
			return (Criteria)this;
		}

		public Criteria andRequireKindCodeGreaterThanOrEqualTo(BigDecimal value){
			addCriterion("REQUIRE_KIND_CODE >=",value,"requireKindCode");
			return (Criteria)this;
		}

		public Criteria andRequireKindCodeLessThan(BigDecimal value){
			addCriterion("REQUIRE_KIND_CODE <",value,"requireKindCode");
			return (Criteria)this;
		}

		public Criteria andRequireKindCodeLessThanOrEqualTo(BigDecimal value){
			addCriterion("REQUIRE_KIND_CODE <=",value,"requireKindCode");
			return (Criteria)this;
		}

		public Criteria andRequireKindCodeIn(List<BigDecimal> values){
			addCriterion("REQUIRE_KIND_CODE in",values,"requireKindCode");
			return (Criteria)this;
		}

		public Criteria andRequireKindCodeNotIn(List<BigDecimal> values){
			addCriterion("REQUIRE_KIND_CODE not in",values,"requireKindCode");
			return (Criteria)this;
		}

		public Criteria andRequireKindCodeBetween(BigDecimal value1,
				BigDecimal value2){
			addCriterion("REQUIRE_KIND_CODE between",value1,value2,
					"requireKindCode");
			return (Criteria)this;
		}

		public Criteria andRequireKindCodeNotBetween(BigDecimal value1,
				BigDecimal value2){
			addCriterion("REQUIRE_KIND_CODE not between",value1,value2,
					"requireKindCode");
			return (Criteria)this;
		}

		public Criteria andRequireKindNameIsNull(){
			addCriterion("REQUIRE_KIND_NAME is null");
			return (Criteria)this;
		}

		public Criteria andRequireKindNameIsNotNull(){
			addCriterion("REQUIRE_KIND_NAME is not null");
			return (Criteria)this;
		}

		public Criteria andRequireKindNameEqualTo(String value){
			addCriterion("REQUIRE_KIND_NAME =",value,"requireKindName");
			return (Criteria)this;
		}

		public Criteria andRequireKindNameNotEqualTo(String value){
			addCriterion("REQUIRE_KIND_NAME <>",value,"requireKindName");
			return (Criteria)this;
		}

		public Criteria andRequireKindNameGreaterThan(String value){
			addCriterion("REQUIRE_KIND_NAME >",value,"requireKindName");
			return (Criteria)this;
		}

		public Criteria andRequireKindNameGreaterThanOrEqualTo(String value){
			addCriterion("REQUIRE_KIND_NAME >=",value,"requireKindName");
			return (Criteria)this;
		}

		public Criteria andRequireKindNameLessThan(String value){
			addCriterion("REQUIRE_KIND_NAME <",value,"requireKindName");
			return (Criteria)this;
		}

		public Criteria andRequireKindNameLessThanOrEqualTo(String value){
			addCriterion("REQUIRE_KIND_NAME <=",value,"requireKindName");
			return (Criteria)this;
		}

		public Criteria andRequireKindNameLike(String value){
			addCriterion("REQUIRE_KIND_NAME like",value,"requireKindName");
			return (Criteria)this;
		}

		public Criteria andRequireKindNameNotLike(String value){
			addCriterion("REQUIRE_KIND_NAME not like",value,"requireKindName");
			return (Criteria)this;
		}

		public Criteria andRequireKindNameIn(List<String> values){
			addCriterion("REQUIRE_KIND_NAME in",values,"requireKindName");
			return (Criteria)this;
		}

		public Criteria andRequireKindNameNotIn(List<String> values){
			addCriterion("REQUIRE_KIND_NAME not in",values,"requireKindName");
			return (Criteria)this;
		}

		public Criteria andRequireKindNameBetween(String value1,String value2){
			addCriterion("REQUIRE_KIND_NAME between",value1,value2,
					"requireKindName");
			return (Criteria)this;
		}

		public Criteria andRequireKindNameNotBetween(String value1,String value2){
			addCriterion("REQUIRE_KIND_NAME not between",value1,value2,
					"requireKindName");
			return (Criteria)this;
		}

		public Criteria andRequireKindDescIsNull(){
			addCriterion("REQUIRE_KIND_DESC is null");
			return (Criteria)this;
		}

		public Criteria andRequireKindDescIsNotNull(){
			addCriterion("REQUIRE_KIND_DESC is not null");
			return (Criteria)this;
		}

		public Criteria andRequireKindDescEqualTo(String value){
			addCriterion("REQUIRE_KIND_DESC =",value,"requireKindDesc");
			return (Criteria)this;
		}

		public Criteria andRequireKindDescNotEqualTo(String value){
			addCriterion("REQUIRE_KIND_DESC <>",value,"requireKindDesc");
			return (Criteria)this;
		}

		public Criteria andRequireKindDescGreaterThan(String value){
			addCriterion("REQUIRE_KIND_DESC >",value,"requireKindDesc");
			return (Criteria)this;
		}

		public Criteria andRequireKindDescGreaterThanOrEqualTo(String value){
			addCriterion("REQUIRE_KIND_DESC >=",value,"requireKindDesc");
			return (Criteria)this;
		}

		public Criteria andRequireKindDescLessThan(String value){
			addCriterion("REQUIRE_KIND_DESC <",value,"requireKindDesc");
			return (Criteria)this;
		}

		public Criteria andRequireKindDescLessThanOrEqualTo(String value){
			addCriterion("REQUIRE_KIND_DESC <=",value,"requireKindDesc");
			return (Criteria)this;
		}

		public Criteria andRequireKindDescLike(String value){
			addCriterion("REQUIRE_KIND_DESC like",value,"requireKindDesc");
			return (Criteria)this;
		}

		public Criteria andRequireKindDescNotLike(String value){
			addCriterion("REQUIRE_KIND_DESC not like",value,"requireKindDesc");
			return (Criteria)this;
		}

		public Criteria andRequireKindDescIn(List<String> values){
			addCriterion("REQUIRE_KIND_DESC in",values,"requireKindDesc");
			return (Criteria)this;
		}

		public Criteria andRequireKindDescNotIn(List<String> values){
			addCriterion("REQUIRE_KIND_DESC not in",values,"requireKindDesc");
			return (Criteria)this;
		}

		public Criteria andRequireKindDescBetween(String value1,String value2){
			addCriterion("REQUIRE_KIND_DESC between",value1,value2,
					"requireKindDesc");
			return (Criteria)this;
		}

		public Criteria andRequireKindDescNotBetween(String value1,String value2){
			addCriterion("REQUIRE_KIND_DESC not between",value1,value2,
					"requireKindDesc");
			return (Criteria)this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	public static class Criterion {
		private String	condition;
		private Object	value;
		private Object	secondValue;
		private boolean	noValue;
		private boolean	singleValue;
		private boolean	betweenValue;
		private boolean	listValue;
		private String	typeHandler;

		public String getCondition(){
			return condition;
		}

		public Object getValue(){
			return value;
		}

		public Object getSecondValue(){
			return secondValue;
		}

		public boolean isNoValue(){
			return noValue;
		}

		public boolean isSingleValue(){
			return singleValue;
		}

		public boolean isBetweenValue(){
			return betweenValue;
		}

		public boolean isListValue(){
			return listValue;
		}

		public String getTypeHandler(){
			return typeHandler;
		}

		protected Criterion(String condition){
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition,Object value,String typeHandler){
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if(value instanceof List<?>){
				this.listValue = true;
			} else{
				this.singleValue = true;
			}
		}

		protected Criterion(String condition,Object value){
			this(condition,value,null);
		}

		protected Criterion(String condition,Object value,Object secondValue,
				String typeHandler){
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition,Object value,Object secondValue){
			this(condition,value,secondValue,null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table REQUIRE_KIND
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}