package cn.com.chinatelecom.pms.pojo;

import java.math.BigDecimal;

public class RequireType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIRE_TYPE.REQUIRE_TYPE_ID
	 * @mbggenerated
	 */
	private String	requireTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIRE_TYPE.REQUIRE_TYPE_CODE
	 * @mbggenerated
	 */
	private BigDecimal	requireTypeCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIRE_TYPE.REQUIRE_TYPE_NAME
	 * @mbggenerated
	 */
	private String	requireTypeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIRE_TYPE.REQUIRE_TYPE_DESC
	 * @mbggenerated
	 */
	private String	requireTypeDesc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIRE_TYPE.REQUIRE_TYPE_ID
	 * @return  the value of REQUIRE_TYPE.REQUIRE_TYPE_ID
	 * @mbggenerated
	 */
	public String getRequireTypeId(){
		return requireTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIRE_TYPE.REQUIRE_TYPE_ID
	 * @param requireTypeId  the value for REQUIRE_TYPE.REQUIRE_TYPE_ID
	 * @mbggenerated
	 */
	public void setRequireTypeId(String requireTypeId){
		this.requireTypeId = requireTypeId==null ? null : requireTypeId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIRE_TYPE.REQUIRE_TYPE_CODE
	 * @return  the value of REQUIRE_TYPE.REQUIRE_TYPE_CODE
	 * @mbggenerated
	 */
	public BigDecimal getRequireTypeCode(){
		return requireTypeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIRE_TYPE.REQUIRE_TYPE_CODE
	 * @param requireTypeCode  the value for REQUIRE_TYPE.REQUIRE_TYPE_CODE
	 * @mbggenerated
	 */
	public void setRequireTypeCode(BigDecimal requireTypeCode){
		this.requireTypeCode = requireTypeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIRE_TYPE.REQUIRE_TYPE_NAME
	 * @return  the value of REQUIRE_TYPE.REQUIRE_TYPE_NAME
	 * @mbggenerated
	 */
	public String getRequireTypeName(){
		return requireTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIRE_TYPE.REQUIRE_TYPE_NAME
	 * @param requireTypeName  the value for REQUIRE_TYPE.REQUIRE_TYPE_NAME
	 * @mbggenerated
	 */
	public void setRequireTypeName(String requireTypeName){
		this.requireTypeName = requireTypeName==null ? null : requireTypeName
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIRE_TYPE.REQUIRE_TYPE_DESC
	 * @return  the value of REQUIRE_TYPE.REQUIRE_TYPE_DESC
	 * @mbggenerated
	 */
	public String getRequireTypeDesc(){
		return requireTypeDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIRE_TYPE.REQUIRE_TYPE_DESC
	 * @param requireTypeDesc  the value for REQUIRE_TYPE.REQUIRE_TYPE_DESC
	 * @mbggenerated
	 */
	public void setRequireTypeDesc(String requireTypeDesc){
		this.requireTypeDesc = requireTypeDesc==null ? null : requireTypeDesc
				.trim();
	}
}