package cn.com.chinatelecom.pms.pojo;

import java.util.ArrayList;
import java.util.List;

public class RequirementExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	protected String	orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	protected boolean	distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	protected List<Criteria>	oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	public RequirementExample(){
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause){
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	public String getOrderByClause(){
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct){
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	public boolean isDistinct(){
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria(){
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	public void or(Criteria criteria){
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	public Criteria or(){
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	public Criteria createCriteria(){
		Criteria criteria = createCriteriaInternal();
		if(oredCriteria.size()==0){
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal(){
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	public void clear(){
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion>	criteria;

		protected GeneratedCriteria(){
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid(){
			return criteria.size()>0;
		}

		public List<Criterion> getAllCriteria(){
			return criteria;
		}

		public List<Criterion> getCriteria(){
			return criteria;
		}

		protected void addCriterion(String condition){
			if(condition==null){
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition,Object value,
				String property){
			if(value==null){
				throw new RuntimeException("Value for "+property
						+" cannot be null");
			}
			criteria.add(new Criterion(condition,value));
		}

		protected void addCriterion(String condition,Object value1,
				Object value2,String property){
			if(value1==null||value2==null){
				throw new RuntimeException("Between values for "+property
						+" cannot be null");
			}
			criteria.add(new Criterion(condition,value1,value2));
		}

		public Criteria andRequireIdIsNull(){
			addCriterion("REQUIRE_ID is null");
			return (Criteria)this;
		}

		public Criteria andRequireIdIsNotNull(){
			addCriterion("REQUIRE_ID is not null");
			return (Criteria)this;
		}

		public Criteria andRequireIdEqualTo(String value){
			addCriterion("REQUIRE_ID =",value,"requireId");
			return (Criteria)this;
		}

		public Criteria andRequireIdNotEqualTo(String value){
			addCriterion("REQUIRE_ID <>",value,"requireId");
			return (Criteria)this;
		}

		public Criteria andRequireIdGreaterThan(String value){
			addCriterion("REQUIRE_ID >",value,"requireId");
			return (Criteria)this;
		}

		public Criteria andRequireIdGreaterThanOrEqualTo(String value){
			addCriterion("REQUIRE_ID >=",value,"requireId");
			return (Criteria)this;
		}

		public Criteria andRequireIdLessThan(String value){
			addCriterion("REQUIRE_ID <",value,"requireId");
			return (Criteria)this;
		}

		public Criteria andRequireIdLessThanOrEqualTo(String value){
			addCriterion("REQUIRE_ID <=",value,"requireId");
			return (Criteria)this;
		}

		public Criteria andRequireIdLike(String value){
			addCriterion("REQUIRE_ID like",value,"requireId");
			return (Criteria)this;
		}

		public Criteria andRequireIdNotLike(String value){
			addCriterion("REQUIRE_ID not like",value,"requireId");
			return (Criteria)this;
		}

		public Criteria andRequireIdIn(List<String> values){
			addCriterion("REQUIRE_ID in",values,"requireId");
			return (Criteria)this;
		}

		public Criteria andRequireIdNotIn(List<String> values){
			addCriterion("REQUIRE_ID not in",values,"requireId");
			return (Criteria)this;
		}

		public Criteria andRequireIdBetween(String value1,String value2){
			addCriterion("REQUIRE_ID between",value1,value2,"requireId");
			return (Criteria)this;
		}

		public Criteria andRequireIdNotBetween(String value1,String value2){
			addCriterion("REQUIRE_ID not between",value1,value2,"requireId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdIsNull(){
			addCriterion("REQUIRE_KIND_ID is null");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdIsNotNull(){
			addCriterion("REQUIRE_KIND_ID is not null");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdEqualTo(String value){
			addCriterion("REQUIRE_KIND_ID =",value,"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdNotEqualTo(String value){
			addCriterion("REQUIRE_KIND_ID <>",value,"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdGreaterThan(String value){
			addCriterion("REQUIRE_KIND_ID >",value,"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdGreaterThanOrEqualTo(String value){
			addCriterion("REQUIRE_KIND_ID >=",value,"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdLessThan(String value){
			addCriterion("REQUIRE_KIND_ID <",value,"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdLessThanOrEqualTo(String value){
			addCriterion("REQUIRE_KIND_ID <=",value,"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdLike(String value){
			addCriterion("REQUIRE_KIND_ID like",value,"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdNotLike(String value){
			addCriterion("REQUIRE_KIND_ID not like",value,"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdIn(List<String> values){
			addCriterion("REQUIRE_KIND_ID in",values,"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdNotIn(List<String> values){
			addCriterion("REQUIRE_KIND_ID not in",values,"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdBetween(String value1,String value2){
			addCriterion("REQUIRE_KIND_ID between",value1,value2,
					"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireKindIdNotBetween(String value1,String value2){
			addCriterion("REQUIRE_KIND_ID not between",value1,value2,
					"requireKindId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdIsNull(){
			addCriterion("REQUIRE_TYPE_ID is null");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdIsNotNull(){
			addCriterion("REQUIRE_TYPE_ID is not null");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdEqualTo(String value){
			addCriterion("REQUIRE_TYPE_ID =",value,"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdNotEqualTo(String value){
			addCriterion("REQUIRE_TYPE_ID <>",value,"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdGreaterThan(String value){
			addCriterion("REQUIRE_TYPE_ID >",value,"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdGreaterThanOrEqualTo(String value){
			addCriterion("REQUIRE_TYPE_ID >=",value,"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdLessThan(String value){
			addCriterion("REQUIRE_TYPE_ID <",value,"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdLessThanOrEqualTo(String value){
			addCriterion("REQUIRE_TYPE_ID <=",value,"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdLike(String value){
			addCriterion("REQUIRE_TYPE_ID like",value,"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdNotLike(String value){
			addCriterion("REQUIRE_TYPE_ID not like",value,"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdIn(List<String> values){
			addCriterion("REQUIRE_TYPE_ID in",values,"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdNotIn(List<String> values){
			addCriterion("REQUIRE_TYPE_ID not in",values,"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdBetween(String value1,String value2){
			addCriterion("REQUIRE_TYPE_ID between",value1,value2,
					"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdNotBetween(String value1,String value2){
			addCriterion("REQUIRE_TYPE_ID not between",value1,value2,
					"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andModuleIdIsNull(){
			addCriterion("MODULE_ID is null");
			return (Criteria)this;
		}

		public Criteria andModuleIdIsNotNull(){
			addCriterion("MODULE_ID is not null");
			return (Criteria)this;
		}

		public Criteria andModuleIdEqualTo(String value){
			addCriterion("MODULE_ID =",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdNotEqualTo(String value){
			addCriterion("MODULE_ID <>",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdGreaterThan(String value){
			addCriterion("MODULE_ID >",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdGreaterThanOrEqualTo(String value){
			addCriterion("MODULE_ID >=",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdLessThan(String value){
			addCriterion("MODULE_ID <",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdLessThanOrEqualTo(String value){
			addCriterion("MODULE_ID <=",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdLike(String value){
			addCriterion("MODULE_ID like",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdNotLike(String value){
			addCriterion("MODULE_ID not like",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdIn(List<String> values){
			addCriterion("MODULE_ID in",values,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdNotIn(List<String> values){
			addCriterion("MODULE_ID not in",values,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdBetween(String value1,String value2){
			addCriterion("MODULE_ID between",value1,value2,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdNotBetween(String value1,String value2){
			addCriterion("MODULE_ID not between",value1,value2,"moduleId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdIsNull(){
			addCriterion("EFFECT_PROCESS_ID is null");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdIsNotNull(){
			addCriterion("EFFECT_PROCESS_ID is not null");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdEqualTo(String value){
			addCriterion("EFFECT_PROCESS_ID =",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdNotEqualTo(String value){
			addCriterion("EFFECT_PROCESS_ID <>",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdGreaterThan(String value){
			addCriterion("EFFECT_PROCESS_ID >",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdGreaterThanOrEqualTo(String value){
			addCriterion("EFFECT_PROCESS_ID >=",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdLessThan(String value){
			addCriterion("EFFECT_PROCESS_ID <",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdLessThanOrEqualTo(String value){
			addCriterion("EFFECT_PROCESS_ID <=",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdLike(String value){
			addCriterion("EFFECT_PROCESS_ID like",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdNotLike(String value){
			addCriterion("EFFECT_PROCESS_ID not like",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdIn(List<String> values){
			addCriterion("EFFECT_PROCESS_ID in",values,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdNotIn(List<String> values){
			addCriterion("EFFECT_PROCESS_ID not in",values,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdBetween(String value1,String value2){
			addCriterion("EFFECT_PROCESS_ID between",value1,value2,
					"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdNotBetween(String value1,String value2){
			addCriterion("EFFECT_PROCESS_ID not between",value1,value2,
					"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andRequireCreatorIsNull(){
			addCriterion("REQUIRE_CREATOR is null");
			return (Criteria)this;
		}

		public Criteria andRequireCreatorIsNotNull(){
			addCriterion("REQUIRE_CREATOR is not null");
			return (Criteria)this;
		}

		public Criteria andRequireCreatorEqualTo(String value){
			addCriterion("REQUIRE_CREATOR =",value,"requireCreator");
			return (Criteria)this;
		}

		public Criteria andRequireCreatorNotEqualTo(String value){
			addCriterion("REQUIRE_CREATOR <>",value,"requireCreator");
			return (Criteria)this;
		}

		public Criteria andRequireCreatorGreaterThan(String value){
			addCriterion("REQUIRE_CREATOR >",value,"requireCreator");
			return (Criteria)this;
		}

		public Criteria andRequireCreatorGreaterThanOrEqualTo(String value){
			addCriterion("REQUIRE_CREATOR >=",value,"requireCreator");
			return (Criteria)this;
		}

		public Criteria andRequireCreatorLessThan(String value){
			addCriterion("REQUIRE_CREATOR <",value,"requireCreator");
			return (Criteria)this;
		}

		public Criteria andRequireCreatorLessThanOrEqualTo(String value){
			addCriterion("REQUIRE_CREATOR <=",value,"requireCreator");
			return (Criteria)this;
		}

		public Criteria andRequireCreatorLike(String value){
			addCriterion("REQUIRE_CREATOR like",value,"requireCreator");
			return (Criteria)this;
		}

		public Criteria andRequireCreatorNotLike(String value){
			addCriterion("REQUIRE_CREATOR not like",value,"requireCreator");
			return (Criteria)this;
		}

		public Criteria andRequireCreatorIn(List<String> values){
			addCriterion("REQUIRE_CREATOR in",values,"requireCreator");
			return (Criteria)this;
		}

		public Criteria andRequireCreatorNotIn(List<String> values){
			addCriterion("REQUIRE_CREATOR not in",values,"requireCreator");
			return (Criteria)this;
		}

		public Criteria andRequireCreatorBetween(String value1,String value2){
			addCriterion("REQUIRE_CREATOR between",value1,value2,
					"requireCreator");
			return (Criteria)this;
		}

		public Criteria andRequireCreatorNotBetween(String value1,String value2){
			addCriterion("REQUIRE_CREATOR not between",value1,value2,
					"requireCreator");
			return (Criteria)this;
		}

		public Criteria andRequireCreateDateIsNull(){
			addCriterion("REQUIRE_CREATE_DATE is null");
			return (Criteria)this;
		}

		public Criteria andRequireCreateDateIsNotNull(){
			addCriterion("REQUIRE_CREATE_DATE is not null");
			return (Criteria)this;
		}

		public Criteria andRequireCreateDateEqualTo(String value){
			addCriterion("REQUIRE_CREATE_DATE =",value,"requireCreateDate");
			return (Criteria)this;
		}

		public Criteria andRequireCreateDateNotEqualTo(String value){
			addCriterion("REQUIRE_CREATE_DATE <>",value,"requireCreateDate");
			return (Criteria)this;
		}

		public Criteria andRequireCreateDateGreaterThan(String value){
			addCriterion("REQUIRE_CREATE_DATE >",value,"requireCreateDate");
			return (Criteria)this;
		}

		public Criteria andRequireCreateDateGreaterThanOrEqualTo(String value){
			addCriterion("REQUIRE_CREATE_DATE >=",value,"requireCreateDate");
			return (Criteria)this;
		}

		public Criteria andRequireCreateDateLessThan(String value){
			addCriterion("REQUIRE_CREATE_DATE <",value,"requireCreateDate");
			return (Criteria)this;
		}

		public Criteria andRequireCreateDateLessThanOrEqualTo(String value){
			addCriterion("REQUIRE_CREATE_DATE <=",value,"requireCreateDate");
			return (Criteria)this;
		}

		public Criteria andRequireCreateDateLike(String value){
			addCriterion("REQUIRE_CREATE_DATE like",value,"requireCreateDate");
			return (Criteria)this;
		}

		public Criteria andRequireCreateDateNotLike(String value){
			addCriterion("REQUIRE_CREATE_DATE not like",value,
					"requireCreateDate");
			return (Criteria)this;
		}

		public Criteria andRequireCreateDateIn(List<String> values){
			addCriterion("REQUIRE_CREATE_DATE in",values,"requireCreateDate");
			return (Criteria)this;
		}

		public Criteria andRequireCreateDateNotIn(List<String> values){
			addCriterion("REQUIRE_CREATE_DATE not in",values,
					"requireCreateDate");
			return (Criteria)this;
		}

		public Criteria andRequireCreateDateBetween(String value1,String value2){
			addCriterion("REQUIRE_CREATE_DATE between",value1,value2,
					"requireCreateDate");
			return (Criteria)this;
		}

		public Criteria andRequireCreateDateNotBetween(String value1,
				String value2){
			addCriterion("REQUIRE_CREATE_DATE not between",value1,value2,
					"requireCreateDate");
			return (Criteria)this;
		}

		public Criteria andRequirePriorityIsNull(){
			addCriterion("REQUIRE_PRIORITY is null");
			return (Criteria)this;
		}

		public Criteria andRequirePriorityIsNotNull(){
			addCriterion("REQUIRE_PRIORITY is not null");
			return (Criteria)this;
		}

		public Criteria andRequirePriorityEqualTo(String value){
			addCriterion("REQUIRE_PRIORITY =",value,"requirePriority");
			return (Criteria)this;
		}

		public Criteria andRequirePriorityNotEqualTo(String value){
			addCriterion("REQUIRE_PRIORITY <>",value,"requirePriority");
			return (Criteria)this;
		}

		public Criteria andRequirePriorityGreaterThan(String value){
			addCriterion("REQUIRE_PRIORITY >",value,"requirePriority");
			return (Criteria)this;
		}

		public Criteria andRequirePriorityGreaterThanOrEqualTo(String value){
			addCriterion("REQUIRE_PRIORITY >=",value,"requirePriority");
			return (Criteria)this;
		}

		public Criteria andRequirePriorityLessThan(String value){
			addCriterion("REQUIRE_PRIORITY <",value,"requirePriority");
			return (Criteria)this;
		}

		public Criteria andRequirePriorityLessThanOrEqualTo(String value){
			addCriterion("REQUIRE_PRIORITY <=",value,"requirePriority");
			return (Criteria)this;
		}

		public Criteria andRequirePriorityLike(String value){
			addCriterion("REQUIRE_PRIORITY like",value,"requirePriority");
			return (Criteria)this;
		}

		public Criteria andRequirePriorityNotLike(String value){
			addCriterion("REQUIRE_PRIORITY not like",value,"requirePriority");
			return (Criteria)this;
		}

		public Criteria andRequirePriorityIn(List<String> values){
			addCriterion("REQUIRE_PRIORITY in",values,"requirePriority");
			return (Criteria)this;
		}

		public Criteria andRequirePriorityNotIn(List<String> values){
			addCriterion("REQUIRE_PRIORITY not in",values,"requirePriority");
			return (Criteria)this;
		}

		public Criteria andRequirePriorityBetween(String value1,String value2){
			addCriterion("REQUIRE_PRIORITY between",value1,value2,
					"requirePriority");
			return (Criteria)this;
		}

		public Criteria andRequirePriorityNotBetween(String value1,String value2){
			addCriterion("REQUIRE_PRIORITY not between",value1,value2,
					"requirePriority");
			return (Criteria)this;
		}

		public Criteria andRequireExpectOnlineDateIsNull(){
			addCriterion("REQUIRE_EXPECT_ONLINE_DATE is null");
			return (Criteria)this;
		}

		public Criteria andRequireExpectOnlineDateIsNotNull(){
			addCriterion("REQUIRE_EXPECT_ONLINE_DATE is not null");
			return (Criteria)this;
		}

		public Criteria andRequireExpectOnlineDateEqualTo(String value){
			addCriterion("REQUIRE_EXPECT_ONLINE_DATE =",value,
					"requireExpectOnlineDate");
			return (Criteria)this;
		}

		public Criteria andRequireExpectOnlineDateNotEqualTo(String value){
			addCriterion("REQUIRE_EXPECT_ONLINE_DATE <>",value,
					"requireExpectOnlineDate");
			return (Criteria)this;
		}

		public Criteria andRequireExpectOnlineDateGreaterThan(String value){
			addCriterion("REQUIRE_EXPECT_ONLINE_DATE >",value,
					"requireExpectOnlineDate");
			return (Criteria)this;
		}

		public Criteria andRequireExpectOnlineDateGreaterThanOrEqualTo(
				String value){
			addCriterion("REQUIRE_EXPECT_ONLINE_DATE >=",value,
					"requireExpectOnlineDate");
			return (Criteria)this;
		}

		public Criteria andRequireExpectOnlineDateLessThan(String value){
			addCriterion("REQUIRE_EXPECT_ONLINE_DATE <",value,
					"requireExpectOnlineDate");
			return (Criteria)this;
		}

		public Criteria andRequireExpectOnlineDateLessThanOrEqualTo(String value){
			addCriterion("REQUIRE_EXPECT_ONLINE_DATE <=",value,
					"requireExpectOnlineDate");
			return (Criteria)this;
		}

		public Criteria andRequireExpectOnlineDateLike(String value){
			addCriterion("REQUIRE_EXPECT_ONLINE_DATE like",value,
					"requireExpectOnlineDate");
			return (Criteria)this;
		}

		public Criteria andRequireExpectOnlineDateNotLike(String value){
			addCriterion("REQUIRE_EXPECT_ONLINE_DATE not like",value,
					"requireExpectOnlineDate");
			return (Criteria)this;
		}

		public Criteria andRequireExpectOnlineDateIn(List<String> values){
			addCriterion("REQUIRE_EXPECT_ONLINE_DATE in",values,
					"requireExpectOnlineDate");
			return (Criteria)this;
		}

		public Criteria andRequireExpectOnlineDateNotIn(List<String> values){
			addCriterion("REQUIRE_EXPECT_ONLINE_DATE not in",values,
					"requireExpectOnlineDate");
			return (Criteria)this;
		}

		public Criteria andRequireExpectOnlineDateBetween(String value1,
				String value2){
			addCriterion("REQUIRE_EXPECT_ONLINE_DATE between",value1,value2,
					"requireExpectOnlineDate");
			return (Criteria)this;
		}

		public Criteria andRequireExpectOnlineDateNotBetween(String value1,
				String value2){
			addCriterion("REQUIRE_EXPECT_ONLINE_DATE not between",value1,
					value2,"requireExpectOnlineDate");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdIsNull(){
			addCriterion("EXECUTE_ORG_ID is null");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdIsNotNull(){
			addCriterion("EXECUTE_ORG_ID is not null");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdEqualTo(String value){
			addCriterion("EXECUTE_ORG_ID =",value,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdNotEqualTo(String value){
			addCriterion("EXECUTE_ORG_ID <>",value,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdGreaterThan(String value){
			addCriterion("EXECUTE_ORG_ID >",value,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdGreaterThanOrEqualTo(String value){
			addCriterion("EXECUTE_ORG_ID >=",value,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdLessThan(String value){
			addCriterion("EXECUTE_ORG_ID <",value,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdLessThanOrEqualTo(String value){
			addCriterion("EXECUTE_ORG_ID <=",value,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdLike(String value){
			addCriterion("EXECUTE_ORG_ID like",value,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdNotLike(String value){
			addCriterion("EXECUTE_ORG_ID not like",value,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdIn(List<String> values){
			addCriterion("EXECUTE_ORG_ID in",values,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdNotIn(List<String> values){
			addCriterion("EXECUTE_ORG_ID not in",values,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdBetween(String value1,String value2){
			addCriterion("EXECUTE_ORG_ID between",value1,value2,"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andExecuteOrgIdNotBetween(String value1,String value2){
			addCriterion("EXECUTE_ORG_ID not between",value1,value2,
					"executeOrgId");
			return (Criteria)this;
		}

		public Criteria andStageIdIsNull(){
			addCriterion("STAGE_ID is null");
			return (Criteria)this;
		}

		public Criteria andStageIdIsNotNull(){
			addCriterion("STAGE_ID is not null");
			return (Criteria)this;
		}

		public Criteria andStageIdEqualTo(String value){
			addCriterion("STAGE_ID =",value,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdNotEqualTo(String value){
			addCriterion("STAGE_ID <>",value,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdGreaterThan(String value){
			addCriterion("STAGE_ID >",value,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdGreaterThanOrEqualTo(String value){
			addCriterion("STAGE_ID >=",value,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdLessThan(String value){
			addCriterion("STAGE_ID <",value,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdLessThanOrEqualTo(String value){
			addCriterion("STAGE_ID <=",value,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdLike(String value){
			addCriterion("STAGE_ID like",value,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdNotLike(String value){
			addCriterion("STAGE_ID not like",value,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdIn(List<String> values){
			addCriterion("STAGE_ID in",values,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdNotIn(List<String> values){
			addCriterion("STAGE_ID not in",values,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdBetween(String value1,String value2){
			addCriterion("STAGE_ID between",value1,value2,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdNotBetween(String value1,String value2){
			addCriterion("STAGE_ID not between",value1,value2,"stageId");
			return (Criteria)this;
		}

		public Criteria andRequireTitleIsNull(){
			addCriterion("REQUIRE_TITLE is null");
			return (Criteria)this;
		}

		public Criteria andRequireTitleIsNotNull(){
			addCriterion("REQUIRE_TITLE is not null");
			return (Criteria)this;
		}

		public Criteria andRequireTitleEqualTo(String value){
			addCriterion("REQUIRE_TITLE =",value,"requireTitle");
			return (Criteria)this;
		}

		public Criteria andRequireTitleNotEqualTo(String value){
			addCriterion("REQUIRE_TITLE <>",value,"requireTitle");
			return (Criteria)this;
		}

		public Criteria andRequireTitleGreaterThan(String value){
			addCriterion("REQUIRE_TITLE >",value,"requireTitle");
			return (Criteria)this;
		}

		public Criteria andRequireTitleGreaterThanOrEqualTo(String value){
			addCriterion("REQUIRE_TITLE >=",value,"requireTitle");
			return (Criteria)this;
		}

		public Criteria andRequireTitleLessThan(String value){
			addCriterion("REQUIRE_TITLE <",value,"requireTitle");
			return (Criteria)this;
		}

		public Criteria andRequireTitleLessThanOrEqualTo(String value){
			addCriterion("REQUIRE_TITLE <=",value,"requireTitle");
			return (Criteria)this;
		}

		public Criteria andRequireTitleLike(String value){
			addCriterion("REQUIRE_TITLE like",value,"requireTitle");
			return (Criteria)this;
		}

		public Criteria andRequireTitleNotLike(String value){
			addCriterion("REQUIRE_TITLE not like",value,"requireTitle");
			return (Criteria)this;
		}

		public Criteria andRequireTitleIn(List<String> values){
			addCriterion("REQUIRE_TITLE in",values,"requireTitle");
			return (Criteria)this;
		}

		public Criteria andRequireTitleNotIn(List<String> values){
			addCriterion("REQUIRE_TITLE not in",values,"requireTitle");
			return (Criteria)this;
		}

		public Criteria andRequireTitleBetween(String value1,String value2){
			addCriterion("REQUIRE_TITLE between",value1,value2,"requireTitle");
			return (Criteria)this;
		}

		public Criteria andRequireTitleNotBetween(String value1,String value2){
			addCriterion("REQUIRE_TITLE not between",value1,value2,
					"requireTitle");
			return (Criteria)this;
		}

		public Criteria andRequireContentIsNull(){
			addCriterion("REQUIRE_CONTENT is null");
			return (Criteria)this;
		}

		public Criteria andRequireContentIsNotNull(){
			addCriterion("REQUIRE_CONTENT is not null");
			return (Criteria)this;
		}

		public Criteria andRequireContentEqualTo(String value){
			addCriterion("REQUIRE_CONTENT =",value,"requireContent");
			return (Criteria)this;
		}

		public Criteria andRequireContentNotEqualTo(String value){
			addCriterion("REQUIRE_CONTENT <>",value,"requireContent");
			return (Criteria)this;
		}

		public Criteria andRequireContentGreaterThan(String value){
			addCriterion("REQUIRE_CONTENT >",value,"requireContent");
			return (Criteria)this;
		}

		public Criteria andRequireContentGreaterThanOrEqualTo(String value){
			addCriterion("REQUIRE_CONTENT >=",value,"requireContent");
			return (Criteria)this;
		}

		public Criteria andRequireContentLessThan(String value){
			addCriterion("REQUIRE_CONTENT <",value,"requireContent");
			return (Criteria)this;
		}

		public Criteria andRequireContentLessThanOrEqualTo(String value){
			addCriterion("REQUIRE_CONTENT <=",value,"requireContent");
			return (Criteria)this;
		}

		public Criteria andRequireContentLike(String value){
			addCriterion("REQUIRE_CONTENT like",value,"requireContent");
			return (Criteria)this;
		}

		public Criteria andRequireContentNotLike(String value){
			addCriterion("REQUIRE_CONTENT not like",value,"requireContent");
			return (Criteria)this;
		}

		public Criteria andRequireContentIn(List<String> values){
			addCriterion("REQUIRE_CONTENT in",values,"requireContent");
			return (Criteria)this;
		}

		public Criteria andRequireContentNotIn(List<String> values){
			addCriterion("REQUIRE_CONTENT not in",values,"requireContent");
			return (Criteria)this;
		}

		public Criteria andRequireContentBetween(String value1,String value2){
			addCriterion("REQUIRE_CONTENT between",value1,value2,
					"requireContent");
			return (Criteria)this;
		}

		public Criteria andRequireContentNotBetween(String value1,String value2){
			addCriterion("REQUIRE_CONTENT not between",value1,value2,
					"requireContent");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdIsNull(){
			addCriterion("REQUIRE_EFFECT_ID is null");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdIsNotNull(){
			addCriterion("REQUIRE_EFFECT_ID is not null");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdEqualTo(String value){
			addCriterion("REQUIRE_EFFECT_ID =",value,"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdNotEqualTo(String value){
			addCriterion("REQUIRE_EFFECT_ID <>",value,"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdGreaterThan(String value){
			addCriterion("REQUIRE_EFFECT_ID >",value,"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdGreaterThanOrEqualTo(String value){
			addCriterion("REQUIRE_EFFECT_ID >=",value,"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdLessThan(String value){
			addCriterion("REQUIRE_EFFECT_ID <",value,"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdLessThanOrEqualTo(String value){
			addCriterion("REQUIRE_EFFECT_ID <=",value,"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdLike(String value){
			addCriterion("REQUIRE_EFFECT_ID like",value,"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdNotLike(String value){
			addCriterion("REQUIRE_EFFECT_ID not like",value,"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdIn(List<String> values){
			addCriterion("REQUIRE_EFFECT_ID in",values,"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdNotIn(List<String> values){
			addCriterion("REQUIRE_EFFECT_ID not in",values,"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdBetween(String value1,String value2){
			addCriterion("REQUIRE_EFFECT_ID between",value1,value2,
					"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdNotBetween(String value1,String value2){
			addCriterion("REQUIRE_EFFECT_ID not between",value1,value2,
					"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andDeveloperIsNull(){
			addCriterion("DEVELOPER is null");
			return (Criteria)this;
		}

		public Criteria andDeveloperIsNotNull(){
			addCriterion("DEVELOPER is not null");
			return (Criteria)this;
		}

		public Criteria andDeveloperEqualTo(String value){
			addCriterion("DEVELOPER =",value,"developer");
			return (Criteria)this;
		}

		public Criteria andDeveloperNotEqualTo(String value){
			addCriterion("DEVELOPER <>",value,"developer");
			return (Criteria)this;
		}

		public Criteria andDeveloperGreaterThan(String value){
			addCriterion("DEVELOPER >",value,"developer");
			return (Criteria)this;
		}

		public Criteria andDeveloperGreaterThanOrEqualTo(String value){
			addCriterion("DEVELOPER >=",value,"developer");
			return (Criteria)this;
		}

		public Criteria andDeveloperLessThan(String value){
			addCriterion("DEVELOPER <",value,"developer");
			return (Criteria)this;
		}

		public Criteria andDeveloperLessThanOrEqualTo(String value){
			addCriterion("DEVELOPER <=",value,"developer");
			return (Criteria)this;
		}

		public Criteria andDeveloperLike(String value){
			addCriterion("DEVELOPER like",value,"developer");
			return (Criteria)this;
		}

		public Criteria andDeveloperNotLike(String value){
			addCriterion("DEVELOPER not like",value,"developer");
			return (Criteria)this;
		}

		public Criteria andDeveloperIn(List<String> values){
			addCriterion("DEVELOPER in",values,"developer");
			return (Criteria)this;
		}

		public Criteria andDeveloperNotIn(List<String> values){
			addCriterion("DEVELOPER not in",values,"developer");
			return (Criteria)this;
		}

		public Criteria andDeveloperBetween(String value1,String value2){
			addCriterion("DEVELOPER between",value1,value2,"developer");
			return (Criteria)this;
		}

		public Criteria andDeveloperNotBetween(String value1,String value2){
			addCriterion("DEVELOPER not between",value1,value2,"developer");
			return (Criteria)this;
		}

		public Criteria andTesterIsNull(){
			addCriterion("TESTER is null");
			return (Criteria)this;
		}

		public Criteria andTesterIsNotNull(){
			addCriterion("TESTER is not null");
			return (Criteria)this;
		}

		public Criteria andTesterEqualTo(String value){
			addCriterion("TESTER =",value,"tester");
			return (Criteria)this;
		}

		public Criteria andTesterNotEqualTo(String value){
			addCriterion("TESTER <>",value,"tester");
			return (Criteria)this;
		}

		public Criteria andTesterGreaterThan(String value){
			addCriterion("TESTER >",value,"tester");
			return (Criteria)this;
		}

		public Criteria andTesterGreaterThanOrEqualTo(String value){
			addCriterion("TESTER >=",value,"tester");
			return (Criteria)this;
		}

		public Criteria andTesterLessThan(String value){
			addCriterion("TESTER <",value,"tester");
			return (Criteria)this;
		}

		public Criteria andTesterLessThanOrEqualTo(String value){
			addCriterion("TESTER <=",value,"tester");
			return (Criteria)this;
		}

		public Criteria andTesterLike(String value){
			addCriterion("TESTER like",value,"tester");
			return (Criteria)this;
		}

		public Criteria andTesterNotLike(String value){
			addCriterion("TESTER not like",value,"tester");
			return (Criteria)this;
		}

		public Criteria andTesterIn(List<String> values){
			addCriterion("TESTER in",values,"tester");
			return (Criteria)this;
		}

		public Criteria andTesterNotIn(List<String> values){
			addCriterion("TESTER not in",values,"tester");
			return (Criteria)this;
		}

		public Criteria andTesterBetween(String value1,String value2){
			addCriterion("TESTER between",value1,value2,"tester");
			return (Criteria)this;
		}

		public Criteria andTesterNotBetween(String value1,String value2){
			addCriterion("TESTER not between",value1,value2,"tester");
			return (Criteria)this;
		}

		public Criteria andVersionIsNull(){
			addCriterion("VERSION is null");
			return (Criteria)this;
		}

		public Criteria andVersionIsNotNull(){
			addCriterion("VERSION is not null");
			return (Criteria)this;
		}

		public Criteria andVersionEqualTo(String value){
			addCriterion("VERSION =",value,"version");
			return (Criteria)this;
		}

		public Criteria andVersionNotEqualTo(String value){
			addCriterion("VERSION <>",value,"version");
			return (Criteria)this;
		}

		public Criteria andVersionGreaterThan(String value){
			addCriterion("VERSION >",value,"version");
			return (Criteria)this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(String value){
			addCriterion("VERSION >=",value,"version");
			return (Criteria)this;
		}

		public Criteria andVersionLessThan(String value){
			addCriterion("VERSION <",value,"version");
			return (Criteria)this;
		}

		public Criteria andVersionLessThanOrEqualTo(String value){
			addCriterion("VERSION <=",value,"version");
			return (Criteria)this;
		}

		public Criteria andVersionLike(String value){
			addCriterion("VERSION like",value,"version");
			return (Criteria)this;
		}

		public Criteria andVersionNotLike(String value){
			addCriterion("VERSION not like",value,"version");
			return (Criteria)this;
		}

		public Criteria andVersionIn(List<String> values){
			addCriterion("VERSION in",values,"version");
			return (Criteria)this;
		}

		public Criteria andVersionNotIn(List<String> values){
			addCriterion("VERSION not in",values,"version");
			return (Criteria)this;
		}

		public Criteria andVersionBetween(String value1,String value2){
			addCriterion("VERSION between",value1,value2,"version");
			return (Criteria)this;
		}

		public Criteria andVersionNotBetween(String value1,String value2){
			addCriterion("VERSION not between",value1,value2,"version");
			return (Criteria)this;
		}

		public Criteria andRemarksIsNull(){
			addCriterion("REMARKS is null");
			return (Criteria)this;
		}

		public Criteria andRemarksIsNotNull(){
			addCriterion("REMARKS is not null");
			return (Criteria)this;
		}

		public Criteria andRemarksEqualTo(String value){
			addCriterion("REMARKS =",value,"remarks");
			return (Criteria)this;
		}

		public Criteria andRemarksNotEqualTo(String value){
			addCriterion("REMARKS <>",value,"remarks");
			return (Criteria)this;
		}

		public Criteria andRemarksGreaterThan(String value){
			addCriterion("REMARKS >",value,"remarks");
			return (Criteria)this;
		}

		public Criteria andRemarksGreaterThanOrEqualTo(String value){
			addCriterion("REMARKS >=",value,"remarks");
			return (Criteria)this;
		}

		public Criteria andRemarksLessThan(String value){
			addCriterion("REMARKS <",value,"remarks");
			return (Criteria)this;
		}

		public Criteria andRemarksLessThanOrEqualTo(String value){
			addCriterion("REMARKS <=",value,"remarks");
			return (Criteria)this;
		}

		public Criteria andRemarksLike(String value){
			addCriterion("REMARKS like",value,"remarks");
			return (Criteria)this;
		}

		public Criteria andRemarksNotLike(String value){
			addCriterion("REMARKS not like",value,"remarks");
			return (Criteria)this;
		}

		public Criteria andRemarksIn(List<String> values){
			addCriterion("REMARKS in",values,"remarks");
			return (Criteria)this;
		}

		public Criteria andRemarksNotIn(List<String> values){
			addCriterion("REMARKS not in",values,"remarks");
			return (Criteria)this;
		}

		public Criteria andRemarksBetween(String value1,String value2){
			addCriterion("REMARKS between",value1,value2,"remarks");
			return (Criteria)this;
		}

		public Criteria andRemarksNotBetween(String value1,String value2){
			addCriterion("REMARKS not between",value1,value2,"remarks");
			return (Criteria)this;
		}

		public Criteria andRequirePeopleIsNull(){
			addCriterion("REQUIRE_PEOPLE is null");
			return (Criteria)this;
		}

		public Criteria andRequirePeopleIsNotNull(){
			addCriterion("REQUIRE_PEOPLE is not null");
			return (Criteria)this;
		}

		public Criteria andRequirePeopleEqualTo(String value){
			addCriterion("REQUIRE_PEOPLE =",value,"requirePeople");
			return (Criteria)this;
		}

		public Criteria andRequirePeopleNotEqualTo(String value){
			addCriterion("REQUIRE_PEOPLE <>",value,"requirePeople");
			return (Criteria)this;
		}

		public Criteria andRequirePeopleGreaterThan(String value){
			addCriterion("REQUIRE_PEOPLE >",value,"requirePeople");
			return (Criteria)this;
		}

		public Criteria andRequirePeopleGreaterThanOrEqualTo(String value){
			addCriterion("REQUIRE_PEOPLE >=",value,"requirePeople");
			return (Criteria)this;
		}

		public Criteria andRequirePeopleLessThan(String value){
			addCriterion("REQUIRE_PEOPLE <",value,"requirePeople");
			return (Criteria)this;
		}

		public Criteria andRequirePeopleLessThanOrEqualTo(String value){
			addCriterion("REQUIRE_PEOPLE <=",value,"requirePeople");
			return (Criteria)this;
		}

		public Criteria andRequirePeopleLike(String value){
			addCriterion("REQUIRE_PEOPLE like",value,"requirePeople");
			return (Criteria)this;
		}

		public Criteria andRequirePeopleNotLike(String value){
			addCriterion("REQUIRE_PEOPLE not like",value,"requirePeople");
			return (Criteria)this;
		}

		public Criteria andRequirePeopleIn(List<String> values){
			addCriterion("REQUIRE_PEOPLE in",values,"requirePeople");
			return (Criteria)this;
		}

		public Criteria andRequirePeopleNotIn(List<String> values){
			addCriterion("REQUIRE_PEOPLE not in",values,"requirePeople");
			return (Criteria)this;
		}

		public Criteria andRequirePeopleBetween(String value1,String value2){
			addCriterion("REQUIRE_PEOPLE between",value1,value2,"requirePeople");
			return (Criteria)this;
		}

		public Criteria andRequirePeopleNotBetween(String value1,String value2){
			addCriterion("REQUIRE_PEOPLE not between",value1,value2,
					"requirePeople");
			return (Criteria)this;
		}

		public Criteria andRequireStateIdIsNull(){
			addCriterion("REQUIRE_STATE_ID is null");
			return (Criteria)this;
		}

		public Criteria andRequireStateIdIsNotNull(){
			addCriterion("REQUIRE_STATE_ID is not null");
			return (Criteria)this;
		}

		public Criteria andRequireStateIdEqualTo(String value){
			addCriterion("REQUIRE_STATE_ID =",value,"requireStateId");
			return (Criteria)this;
		}

		public Criteria andRequireStateIdNotEqualTo(String value){
			addCriterion("REQUIRE_STATE_ID <>",value,"requireStateId");
			return (Criteria)this;
		}

		public Criteria andRequireStateIdGreaterThan(String value){
			addCriterion("REQUIRE_STATE_ID >",value,"requireStateId");
			return (Criteria)this;
		}

		public Criteria andRequireStateIdGreaterThanOrEqualTo(String value){
			addCriterion("REQUIRE_STATE_ID >=",value,"requireStateId");
			return (Criteria)this;
		}

		public Criteria andRequireStateIdLessThan(String value){
			addCriterion("REQUIRE_STATE_ID <",value,"requireStateId");
			return (Criteria)this;
		}

		public Criteria andRequireStateIdLessThanOrEqualTo(String value){
			addCriterion("REQUIRE_STATE_ID <=",value,"requireStateId");
			return (Criteria)this;
		}

		public Criteria andRequireStateIdLike(String value){
			addCriterion("REQUIRE_STATE_ID like",value,"requireStateId");
			return (Criteria)this;
		}

		public Criteria andRequireStateIdNotLike(String value){
			addCriterion("REQUIRE_STATE_ID not like",value,"requireStateId");
			return (Criteria)this;
		}

		public Criteria andRequireStateIdIn(List<String> values){
			addCriterion("REQUIRE_STATE_ID in",values,"requireStateId");
			return (Criteria)this;
		}

		public Criteria andRequireStateIdNotIn(List<String> values){
			addCriterion("REQUIRE_STATE_ID not in",values,"requireStateId");
			return (Criteria)this;
		}

		public Criteria andRequireStateIdBetween(String value1,String value2){
			addCriterion("REQUIRE_STATE_ID between",value1,value2,
					"requireStateId");
			return (Criteria)this;
		}

		public Criteria andRequireStateIdNotBetween(String value1,String value2){
			addCriterion("REQUIRE_STATE_ID not between",value1,value2,
					"requireStateId");
			return (Criteria)this;
		}

		public Criteria andEffectActionIdIsNull(){
			addCriterion("EFFECT_ACTION_ID is null");
			return (Criteria)this;
		}

		public Criteria andEffectActionIdIsNotNull(){
			addCriterion("EFFECT_ACTION_ID is not null");
			return (Criteria)this;
		}

		public Criteria andEffectActionIdEqualTo(String value){
			addCriterion("EFFECT_ACTION_ID =",value,"effectActionId");
			return (Criteria)this;
		}

		public Criteria andEffectActionIdNotEqualTo(String value){
			addCriterion("EFFECT_ACTION_ID <>",value,"effectActionId");
			return (Criteria)this;
		}

		public Criteria andEffectActionIdGreaterThan(String value){
			addCriterion("EFFECT_ACTION_ID >",value,"effectActionId");
			return (Criteria)this;
		}

		public Criteria andEffectActionIdGreaterThanOrEqualTo(String value){
			addCriterion("EFFECT_ACTION_ID >=",value,"effectActionId");
			return (Criteria)this;
		}

		public Criteria andEffectActionIdLessThan(String value){
			addCriterion("EFFECT_ACTION_ID <",value,"effectActionId");
			return (Criteria)this;
		}

		public Criteria andEffectActionIdLessThanOrEqualTo(String value){
			addCriterion("EFFECT_ACTION_ID <=",value,"effectActionId");
			return (Criteria)this;
		}

		public Criteria andEffectActionIdLike(String value){
			addCriterion("EFFECT_ACTION_ID like",value,"effectActionId");
			return (Criteria)this;
		}

		public Criteria andEffectActionIdNotLike(String value){
			addCriterion("EFFECT_ACTION_ID not like",value,"effectActionId");
			return (Criteria)this;
		}

		public Criteria andEffectActionIdIn(List<String> values){
			addCriterion("EFFECT_ACTION_ID in",values,"effectActionId");
			return (Criteria)this;
		}

		public Criteria andEffectActionIdNotIn(List<String> values){
			addCriterion("EFFECT_ACTION_ID not in",values,"effectActionId");
			return (Criteria)this;
		}

		public Criteria andEffectActionIdBetween(String value1,String value2){
			addCriterion("EFFECT_ACTION_ID between",value1,value2,
					"effectActionId");
			return (Criteria)this;
		}

		public Criteria andEffectActionIdNotBetween(String value1,String value2){
			addCriterion("EFFECT_ACTION_ID not between",value1,value2,
					"effectActionId");
			return (Criteria)this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	public static class Criterion {
		private String	condition;
		private Object	value;
		private Object	secondValue;
		private boolean	noValue;
		private boolean	singleValue;
		private boolean	betweenValue;
		private boolean	listValue;
		private String	typeHandler;

		public String getCondition(){
			return condition;
		}

		public Object getValue(){
			return value;
		}

		public Object getSecondValue(){
			return secondValue;
		}

		public boolean isNoValue(){
			return noValue;
		}

		public boolean isSingleValue(){
			return singleValue;
		}

		public boolean isBetweenValue(){
			return betweenValue;
		}

		public boolean isListValue(){
			return listValue;
		}

		public String getTypeHandler(){
			return typeHandler;
		}

		protected Criterion(String condition){
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition,Object value,String typeHandler){
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if(value instanceof List<?>){
				this.listValue = true;
			} else{
				this.singleValue = true;
			}
		}

		protected Criterion(String condition,Object value){
			this(condition,value,null);
		}

		protected Criterion(String condition,Object value,Object secondValue,
				String typeHandler){
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition,Object value,Object secondValue){
			this(condition,value,secondValue,null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table REQUIREMENT
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}