package cn.com.chinatelecom.pms.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class RequirePriorityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    public RequirePriorityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPriorityIdIsNull() {
            addCriterion("PRIORITY_ID is null");
            return (Criteria) this;
        }

        public Criteria andPriorityIdIsNotNull() {
            addCriterion("PRIORITY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityIdEqualTo(String value) {
            addCriterion("PRIORITY_ID =", value, "priorityId");
            return (Criteria) this;
        }

        public Criteria andPriorityIdNotEqualTo(String value) {
            addCriterion("PRIORITY_ID <>", value, "priorityId");
            return (Criteria) this;
        }

        public Criteria andPriorityIdGreaterThan(String value) {
            addCriterion("PRIORITY_ID >", value, "priorityId");
            return (Criteria) this;
        }

        public Criteria andPriorityIdGreaterThanOrEqualTo(String value) {
            addCriterion("PRIORITY_ID >=", value, "priorityId");
            return (Criteria) this;
        }

        public Criteria andPriorityIdLessThan(String value) {
            addCriterion("PRIORITY_ID <", value, "priorityId");
            return (Criteria) this;
        }

        public Criteria andPriorityIdLessThanOrEqualTo(String value) {
            addCriterion("PRIORITY_ID <=", value, "priorityId");
            return (Criteria) this;
        }

        public Criteria andPriorityIdLike(String value) {
            addCriterion("PRIORITY_ID like", value, "priorityId");
            return (Criteria) this;
        }

        public Criteria andPriorityIdNotLike(String value) {
            addCriterion("PRIORITY_ID not like", value, "priorityId");
            return (Criteria) this;
        }

        public Criteria andPriorityIdIn(List<String> values) {
            addCriterion("PRIORITY_ID in", values, "priorityId");
            return (Criteria) this;
        }

        public Criteria andPriorityIdNotIn(List<String> values) {
            addCriterion("PRIORITY_ID not in", values, "priorityId");
            return (Criteria) this;
        }

        public Criteria andPriorityIdBetween(String value1, String value2) {
            addCriterion("PRIORITY_ID between", value1, value2, "priorityId");
            return (Criteria) this;
        }

        public Criteria andPriorityIdNotBetween(String value1, String value2) {
            addCriterion("PRIORITY_ID not between", value1, value2, "priorityId");
            return (Criteria) this;
        }

        public Criteria andPriorityCodeIsNull() {
            addCriterion("PRIORITY_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPriorityCodeIsNotNull() {
            addCriterion("PRIORITY_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityCodeEqualTo(BigDecimal value) {
            addCriterion("PRIORITY_CODE =", value, "priorityCode");
            return (Criteria) this;
        }

        public Criteria andPriorityCodeNotEqualTo(BigDecimal value) {
            addCriterion("PRIORITY_CODE <>", value, "priorityCode");
            return (Criteria) this;
        }

        public Criteria andPriorityCodeGreaterThan(BigDecimal value) {
            addCriterion("PRIORITY_CODE >", value, "priorityCode");
            return (Criteria) this;
        }

        public Criteria andPriorityCodeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PRIORITY_CODE >=", value, "priorityCode");
            return (Criteria) this;
        }

        public Criteria andPriorityCodeLessThan(BigDecimal value) {
            addCriterion("PRIORITY_CODE <", value, "priorityCode");
            return (Criteria) this;
        }

        public Criteria andPriorityCodeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PRIORITY_CODE <=", value, "priorityCode");
            return (Criteria) this;
        }

        public Criteria andPriorityCodeIn(List<BigDecimal> values) {
            addCriterion("PRIORITY_CODE in", values, "priorityCode");
            return (Criteria) this;
        }

        public Criteria andPriorityCodeNotIn(List<BigDecimal> values) {
            addCriterion("PRIORITY_CODE not in", values, "priorityCode");
            return (Criteria) this;
        }

        public Criteria andPriorityCodeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PRIORITY_CODE between", value1, value2, "priorityCode");
            return (Criteria) this;
        }

        public Criteria andPriorityCodeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PRIORITY_CODE not between", value1, value2, "priorityCode");
            return (Criteria) this;
        }

        public Criteria andPriorityNameIsNull() {
            addCriterion("PRIORITY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andPriorityNameIsNotNull() {
            addCriterion("PRIORITY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityNameEqualTo(String value) {
            addCriterion("PRIORITY_NAME =", value, "priorityName");
            return (Criteria) this;
        }

        public Criteria andPriorityNameNotEqualTo(String value) {
            addCriterion("PRIORITY_NAME <>", value, "priorityName");
            return (Criteria) this;
        }

        public Criteria andPriorityNameGreaterThan(String value) {
            addCriterion("PRIORITY_NAME >", value, "priorityName");
            return (Criteria) this;
        }

        public Criteria andPriorityNameGreaterThanOrEqualTo(String value) {
            addCriterion("PRIORITY_NAME >=", value, "priorityName");
            return (Criteria) this;
        }

        public Criteria andPriorityNameLessThan(String value) {
            addCriterion("PRIORITY_NAME <", value, "priorityName");
            return (Criteria) this;
        }

        public Criteria andPriorityNameLessThanOrEqualTo(String value) {
            addCriterion("PRIORITY_NAME <=", value, "priorityName");
            return (Criteria) this;
        }

        public Criteria andPriorityNameLike(String value) {
            addCriterion("PRIORITY_NAME like", value, "priorityName");
            return (Criteria) this;
        }

        public Criteria andPriorityNameNotLike(String value) {
            addCriterion("PRIORITY_NAME not like", value, "priorityName");
            return (Criteria) this;
        }

        public Criteria andPriorityNameIn(List<String> values) {
            addCriterion("PRIORITY_NAME in", values, "priorityName");
            return (Criteria) this;
        }

        public Criteria andPriorityNameNotIn(List<String> values) {
            addCriterion("PRIORITY_NAME not in", values, "priorityName");
            return (Criteria) this;
        }

        public Criteria andPriorityNameBetween(String value1, String value2) {
            addCriterion("PRIORITY_NAME between", value1, value2, "priorityName");
            return (Criteria) this;
        }

        public Criteria andPriorityNameNotBetween(String value1, String value2) {
            addCriterion("PRIORITY_NAME not between", value1, value2, "priorityName");
            return (Criteria) this;
        }

        public Criteria andPriorityDescIsNull() {
            addCriterion("PRIORITY_DESC is null");
            return (Criteria) this;
        }

        public Criteria andPriorityDescIsNotNull() {
            addCriterion("PRIORITY_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityDescEqualTo(String value) {
            addCriterion("PRIORITY_DESC =", value, "priorityDesc");
            return (Criteria) this;
        }

        public Criteria andPriorityDescNotEqualTo(String value) {
            addCriterion("PRIORITY_DESC <>", value, "priorityDesc");
            return (Criteria) this;
        }

        public Criteria andPriorityDescGreaterThan(String value) {
            addCriterion("PRIORITY_DESC >", value, "priorityDesc");
            return (Criteria) this;
        }

        public Criteria andPriorityDescGreaterThanOrEqualTo(String value) {
            addCriterion("PRIORITY_DESC >=", value, "priorityDesc");
            return (Criteria) this;
        }

        public Criteria andPriorityDescLessThan(String value) {
            addCriterion("PRIORITY_DESC <", value, "priorityDesc");
            return (Criteria) this;
        }

        public Criteria andPriorityDescLessThanOrEqualTo(String value) {
            addCriterion("PRIORITY_DESC <=", value, "priorityDesc");
            return (Criteria) this;
        }

        public Criteria andPriorityDescLike(String value) {
            addCriterion("PRIORITY_DESC like", value, "priorityDesc");
            return (Criteria) this;
        }

        public Criteria andPriorityDescNotLike(String value) {
            addCriterion("PRIORITY_DESC not like", value, "priorityDesc");
            return (Criteria) this;
        }

        public Criteria andPriorityDescIn(List<String> values) {
            addCriterion("PRIORITY_DESC in", values, "priorityDesc");
            return (Criteria) this;
        }

        public Criteria andPriorityDescNotIn(List<String> values) {
            addCriterion("PRIORITY_DESC not in", values, "priorityDesc");
            return (Criteria) this;
        }

        public Criteria andPriorityDescBetween(String value1, String value2) {
            addCriterion("PRIORITY_DESC between", value1, value2, "priorityDesc");
            return (Criteria) this;
        }

        public Criteria andPriorityDescNotBetween(String value1, String value2) {
            addCriterion("PRIORITY_DESC not between", value1, value2, "priorityDesc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}