package cn.com.chinatelecom.pms.pojo;

import java.math.BigDecimal;

public class RequireKind {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIRE_KIND.REQUIRE_KIND_ID
	 * @mbggenerated
	 */
	private String	requireKindId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIRE_KIND.REQUIRE_KIND_CODE
	 * @mbggenerated
	 */
	private BigDecimal	requireKindCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIRE_KIND.REQUIRE_KIND_NAME
	 * @mbggenerated
	 */
	private String	requireKindName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIRE_KIND.REQUIRE_KIND_DESC
	 * @mbggenerated
	 */
	private String	requireKindDesc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIRE_KIND.REQUIRE_KIND_ID
	 * @return  the value of REQUIRE_KIND.REQUIRE_KIND_ID
	 * @mbggenerated
	 */
	public String getRequireKindId(){
		return requireKindId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIRE_KIND.REQUIRE_KIND_ID
	 * @param requireKindId  the value for REQUIRE_KIND.REQUIRE_KIND_ID
	 * @mbggenerated
	 */
	public void setRequireKindId(String requireKindId){
		this.requireKindId = requireKindId==null ? null : requireKindId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIRE_KIND.REQUIRE_KIND_CODE
	 * @return  the value of REQUIRE_KIND.REQUIRE_KIND_CODE
	 * @mbggenerated
	 */
	public BigDecimal getRequireKindCode(){
		return requireKindCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIRE_KIND.REQUIRE_KIND_CODE
	 * @param requireKindCode  the value for REQUIRE_KIND.REQUIRE_KIND_CODE
	 * @mbggenerated
	 */
	public void setRequireKindCode(BigDecimal requireKindCode){
		this.requireKindCode = requireKindCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIRE_KIND.REQUIRE_KIND_NAME
	 * @return  the value of REQUIRE_KIND.REQUIRE_KIND_NAME
	 * @mbggenerated
	 */
	public String getRequireKindName(){
		return requireKindName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIRE_KIND.REQUIRE_KIND_NAME
	 * @param requireKindName  the value for REQUIRE_KIND.REQUIRE_KIND_NAME
	 * @mbggenerated
	 */
	public void setRequireKindName(String requireKindName){
		this.requireKindName = requireKindName==null ? null : requireKindName
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIRE_KIND.REQUIRE_KIND_DESC
	 * @return  the value of REQUIRE_KIND.REQUIRE_KIND_DESC
	 * @mbggenerated
	 */
	public String getRequireKindDesc(){
		return requireKindDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIRE_KIND.REQUIRE_KIND_DESC
	 * @param requireKindDesc  the value for REQUIRE_KIND.REQUIRE_KIND_DESC
	 * @mbggenerated
	 */
	public void setRequireKindDesc(String requireKindDesc){
		this.requireKindDesc = requireKindDesc==null ? null : requireKindDesc
				.trim();
	}
}