package cn.com.chinatelecom.pms.pojo;

public class Requirement {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIREMENT.REQUIRE_ID
	 * @mbggenerated
	 */
	private String	requireId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIREMENT.REQUIRE_KIND_ID
	 * @mbggenerated
	 */
	private String	requireKindId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIREMENT.REQUIRE_TYPE_ID
	 * @mbggenerated
	 */
	private String	requireTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIREMENT.MODULE_ID
	 * @mbggenerated
	 */
	private String	moduleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIREMENT.EFFECT_PROCESS_ID
	 * @mbggenerated
	 */
	private String	effectProcessId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIREMENT.REQUIRE_CREATOR
	 * @mbggenerated
	 */
	private String	requireCreator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIREMENT.REQUIRE_CREATE_DATE
	 * @mbggenerated
	 */
	private String	requireCreateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIREMENT.REQUIRE_PRIORITY
	 * @mbggenerated
	 */
	private String	requirePriority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIREMENT.REQUIRE_EXPECT_ONLINE_DATE
	 * @mbggenerated
	 */
	private String	requireExpectOnlineDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIREMENT.EXECUTE_ORG_ID
	 * @mbggenerated
	 */
	private String	executeOrgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIREMENT.STAGE_ID
	 * @mbggenerated
	 */
	private String	stageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIREMENT.REQUIRE_TITLE
	 * @mbggenerated
	 */
	private String	requireTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIREMENT.REQUIRE_CONTENT
	 * @mbggenerated
	 */
	private String	requireContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIREMENT.REQUIRE_EFFECT_ID
	 * @mbggenerated
	 */
	private String	requireEffectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIREMENT.DEVELOPER
	 * @mbggenerated
	 */
	private String	developer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIREMENT.TESTER
	 * @mbggenerated
	 */
	private String	tester;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIREMENT.VERSION
	 * @mbggenerated
	 */
	private String	version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIREMENT.REMARKS
	 * @mbggenerated
	 */
	private String	remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIREMENT.REQUIRE_PEOPLE
	 * @mbggenerated
	 */
	private String	requirePeople;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIREMENT.REQUIRE_STATE_ID
	 * @mbggenerated
	 */
	private String	requireStateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIREMENT.EFFECT_ACTION_ID
	 * @mbggenerated
	 */
	private String	effectActionId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIREMENT.REQUIRE_ID
	 * @return  the value of REQUIREMENT.REQUIRE_ID
	 * @mbggenerated
	 */
	public String getRequireId(){
		return requireId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIREMENT.REQUIRE_ID
	 * @param requireId  the value for REQUIREMENT.REQUIRE_ID
	 * @mbggenerated
	 */
	public void setRequireId(String requireId){
		this.requireId = requireId==null ? null : requireId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIREMENT.REQUIRE_KIND_ID
	 * @return  the value of REQUIREMENT.REQUIRE_KIND_ID
	 * @mbggenerated
	 */
	public String getRequireKindId(){
		return requireKindId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIREMENT.REQUIRE_KIND_ID
	 * @param requireKindId  the value for REQUIREMENT.REQUIRE_KIND_ID
	 * @mbggenerated
	 */
	public void setRequireKindId(String requireKindId){
		this.requireKindId = requireKindId==null ? null : requireKindId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIREMENT.REQUIRE_TYPE_ID
	 * @return  the value of REQUIREMENT.REQUIRE_TYPE_ID
	 * @mbggenerated
	 */
	public String getRequireTypeId(){
		return requireTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIREMENT.REQUIRE_TYPE_ID
	 * @param requireTypeId  the value for REQUIREMENT.REQUIRE_TYPE_ID
	 * @mbggenerated
	 */
	public void setRequireTypeId(String requireTypeId){
		this.requireTypeId = requireTypeId==null ? null : requireTypeId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIREMENT.MODULE_ID
	 * @return  the value of REQUIREMENT.MODULE_ID
	 * @mbggenerated
	 */
	public String getModuleId(){
		return moduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIREMENT.MODULE_ID
	 * @param moduleId  the value for REQUIREMENT.MODULE_ID
	 * @mbggenerated
	 */
	public void setModuleId(String moduleId){
		this.moduleId = moduleId==null ? null : moduleId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIREMENT.EFFECT_PROCESS_ID
	 * @return  the value of REQUIREMENT.EFFECT_PROCESS_ID
	 * @mbggenerated
	 */
	public String getEffectProcessId(){
		return effectProcessId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIREMENT.EFFECT_PROCESS_ID
	 * @param effectProcessId  the value for REQUIREMENT.EFFECT_PROCESS_ID
	 * @mbggenerated
	 */
	public void setEffectProcessId(String effectProcessId){
		this.effectProcessId = effectProcessId==null ? null : effectProcessId
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIREMENT.REQUIRE_CREATOR
	 * @return  the value of REQUIREMENT.REQUIRE_CREATOR
	 * @mbggenerated
	 */
	public String getRequireCreator(){
		return requireCreator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIREMENT.REQUIRE_CREATOR
	 * @param requireCreator  the value for REQUIREMENT.REQUIRE_CREATOR
	 * @mbggenerated
	 */
	public void setRequireCreator(String requireCreator){
		this.requireCreator = requireCreator==null ? null : requireCreator
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIREMENT.REQUIRE_CREATE_DATE
	 * @return  the value of REQUIREMENT.REQUIRE_CREATE_DATE
	 * @mbggenerated
	 */
	public String getRequireCreateDate(){
		return requireCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIREMENT.REQUIRE_CREATE_DATE
	 * @param requireCreateDate  the value for REQUIREMENT.REQUIRE_CREATE_DATE
	 * @mbggenerated
	 */
	public void setRequireCreateDate(String requireCreateDate){
		this.requireCreateDate = requireCreateDate==null ? null
				: requireCreateDate.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIREMENT.REQUIRE_PRIORITY
	 * @return  the value of REQUIREMENT.REQUIRE_PRIORITY
	 * @mbggenerated
	 */
	public String getRequirePriority(){
		return requirePriority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIREMENT.REQUIRE_PRIORITY
	 * @param requirePriority  the value for REQUIREMENT.REQUIRE_PRIORITY
	 * @mbggenerated
	 */
	public void setRequirePriority(String requirePriority){
		this.requirePriority = requirePriority==null ? null : requirePriority
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIREMENT.REQUIRE_EXPECT_ONLINE_DATE
	 * @return  the value of REQUIREMENT.REQUIRE_EXPECT_ONLINE_DATE
	 * @mbggenerated
	 */
	public String getRequireExpectOnlineDate(){
		return requireExpectOnlineDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIREMENT.REQUIRE_EXPECT_ONLINE_DATE
	 * @param requireExpectOnlineDate  the value for REQUIREMENT.REQUIRE_EXPECT_ONLINE_DATE
	 * @mbggenerated
	 */
	public void setRequireExpectOnlineDate(String requireExpectOnlineDate){
		this.requireExpectOnlineDate = requireExpectOnlineDate==null ? null
				: requireExpectOnlineDate.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIREMENT.EXECUTE_ORG_ID
	 * @return  the value of REQUIREMENT.EXECUTE_ORG_ID
	 * @mbggenerated
	 */
	public String getExecuteOrgId(){
		return executeOrgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIREMENT.EXECUTE_ORG_ID
	 * @param executeOrgId  the value for REQUIREMENT.EXECUTE_ORG_ID
	 * @mbggenerated
	 */
	public void setExecuteOrgId(String executeOrgId){
		this.executeOrgId = executeOrgId==null ? null : executeOrgId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIREMENT.STAGE_ID
	 * @return  the value of REQUIREMENT.STAGE_ID
	 * @mbggenerated
	 */
	public String getStageId(){
		return stageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIREMENT.STAGE_ID
	 * @param stageId  the value for REQUIREMENT.STAGE_ID
	 * @mbggenerated
	 */
	public void setStageId(String stageId){
		this.stageId = stageId==null ? null : stageId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIREMENT.REQUIRE_TITLE
	 * @return  the value of REQUIREMENT.REQUIRE_TITLE
	 * @mbggenerated
	 */
	public String getRequireTitle(){
		return requireTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIREMENT.REQUIRE_TITLE
	 * @param requireTitle  the value for REQUIREMENT.REQUIRE_TITLE
	 * @mbggenerated
	 */
	public void setRequireTitle(String requireTitle){
		this.requireTitle = requireTitle==null ? null : requireTitle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIREMENT.REQUIRE_CONTENT
	 * @return  the value of REQUIREMENT.REQUIRE_CONTENT
	 * @mbggenerated
	 */
	public String getRequireContent(){
		return requireContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIREMENT.REQUIRE_CONTENT
	 * @param requireContent  the value for REQUIREMENT.REQUIRE_CONTENT
	 * @mbggenerated
	 */
	public void setRequireContent(String requireContent){
		this.requireContent = requireContent==null ? null : requireContent
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIREMENT.REQUIRE_EFFECT_ID
	 * @return  the value of REQUIREMENT.REQUIRE_EFFECT_ID
	 * @mbggenerated
	 */
	public String getRequireEffectId(){
		return requireEffectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIREMENT.REQUIRE_EFFECT_ID
	 * @param requireEffectId  the value for REQUIREMENT.REQUIRE_EFFECT_ID
	 * @mbggenerated
	 */
	public void setRequireEffectId(String requireEffectId){
		this.requireEffectId = requireEffectId==null ? null : requireEffectId
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIREMENT.DEVELOPER
	 * @return  the value of REQUIREMENT.DEVELOPER
	 * @mbggenerated
	 */
	public String getDeveloper(){
		return developer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIREMENT.DEVELOPER
	 * @param developer  the value for REQUIREMENT.DEVELOPER
	 * @mbggenerated
	 */
	public void setDeveloper(String developer){
		this.developer = developer==null ? null : developer.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIREMENT.TESTER
	 * @return  the value of REQUIREMENT.TESTER
	 * @mbggenerated
	 */
	public String getTester(){
		return tester;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIREMENT.TESTER
	 * @param tester  the value for REQUIREMENT.TESTER
	 * @mbggenerated
	 */
	public void setTester(String tester){
		this.tester = tester==null ? null : tester.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIREMENT.VERSION
	 * @return  the value of REQUIREMENT.VERSION
	 * @mbggenerated
	 */
	public String getVersion(){
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIREMENT.VERSION
	 * @param version  the value for REQUIREMENT.VERSION
	 * @mbggenerated
	 */
	public void setVersion(String version){
		this.version = version==null ? null : version.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIREMENT.REMARKS
	 * @return  the value of REQUIREMENT.REMARKS
	 * @mbggenerated
	 */
	public String getRemarks(){
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIREMENT.REMARKS
	 * @param remarks  the value for REQUIREMENT.REMARKS
	 * @mbggenerated
	 */
	public void setRemarks(String remarks){
		this.remarks = remarks==null ? null : remarks.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIREMENT.REQUIRE_PEOPLE
	 * @return  the value of REQUIREMENT.REQUIRE_PEOPLE
	 * @mbggenerated
	 */
	public String getRequirePeople(){
		return requirePeople;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIREMENT.REQUIRE_PEOPLE
	 * @param requirePeople  the value for REQUIREMENT.REQUIRE_PEOPLE
	 * @mbggenerated
	 */
	public void setRequirePeople(String requirePeople){
		this.requirePeople = requirePeople==null ? null : requirePeople.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIREMENT.REQUIRE_STATE_ID
	 * @return  the value of REQUIREMENT.REQUIRE_STATE_ID
	 * @mbggenerated
	 */
	public String getRequireStateId(){
		return requireStateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIREMENT.REQUIRE_STATE_ID
	 * @param requireStateId  the value for REQUIREMENT.REQUIRE_STATE_ID
	 * @mbggenerated
	 */
	public void setRequireStateId(String requireStateId){
		this.requireStateId = requireStateId==null ? null : requireStateId
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIREMENT.EFFECT_ACTION_ID
	 * @return  the value of REQUIREMENT.EFFECT_ACTION_ID
	 * @mbggenerated
	 */
	public String getEffectActionId(){
		return effectActionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIREMENT.EFFECT_ACTION_ID
	 * @param effectActionId  the value for REQUIREMENT.EFFECT_ACTION_ID
	 * @mbggenerated
	 */
	public void setEffectActionId(String effectActionId){
		this.effectActionId = effectActionId==null ? null : effectActionId
				.trim();
	}
}