package cn.com.chinatelecom.pms.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class RequireTypeExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	protected String	orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	protected boolean	distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	protected List<Criteria>	oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	public RequireTypeExample(){
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause){
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	public String getOrderByClause(){
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct){
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	public boolean isDistinct(){
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria(){
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	public void or(Criteria criteria){
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	public Criteria or(){
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	public Criteria createCriteria(){
		Criteria criteria = createCriteriaInternal();
		if(oredCriteria.size()==0){
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal(){
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	public void clear(){
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion>	criteria;

		protected GeneratedCriteria(){
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid(){
			return criteria.size()>0;
		}

		public List<Criterion> getAllCriteria(){
			return criteria;
		}

		public List<Criterion> getCriteria(){
			return criteria;
		}

		protected void addCriterion(String condition){
			if(condition==null){
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition,Object value,
				String property){
			if(value==null){
				throw new RuntimeException("Value for "+property
						+" cannot be null");
			}
			criteria.add(new Criterion(condition,value));
		}

		protected void addCriterion(String condition,Object value1,
				Object value2,String property){
			if(value1==null||value2==null){
				throw new RuntimeException("Between values for "+property
						+" cannot be null");
			}
			criteria.add(new Criterion(condition,value1,value2));
		}

		public Criteria andRequireTypeIdIsNull(){
			addCriterion("REQUIRE_TYPE_ID is null");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdIsNotNull(){
			addCriterion("REQUIRE_TYPE_ID is not null");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdEqualTo(String value){
			addCriterion("REQUIRE_TYPE_ID =",value,"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdNotEqualTo(String value){
			addCriterion("REQUIRE_TYPE_ID <>",value,"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdGreaterThan(String value){
			addCriterion("REQUIRE_TYPE_ID >",value,"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdGreaterThanOrEqualTo(String value){
			addCriterion("REQUIRE_TYPE_ID >=",value,"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdLessThan(String value){
			addCriterion("REQUIRE_TYPE_ID <",value,"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdLessThanOrEqualTo(String value){
			addCriterion("REQUIRE_TYPE_ID <=",value,"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdLike(String value){
			addCriterion("REQUIRE_TYPE_ID like",value,"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdNotLike(String value){
			addCriterion("REQUIRE_TYPE_ID not like",value,"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdIn(List<String> values){
			addCriterion("REQUIRE_TYPE_ID in",values,"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdNotIn(List<String> values){
			addCriterion("REQUIRE_TYPE_ID not in",values,"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdBetween(String value1,String value2){
			addCriterion("REQUIRE_TYPE_ID between",value1,value2,
					"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeIdNotBetween(String value1,String value2){
			addCriterion("REQUIRE_TYPE_ID not between",value1,value2,
					"requireTypeId");
			return (Criteria)this;
		}

		public Criteria andRequireTypeCodeIsNull(){
			addCriterion("REQUIRE_TYPE_CODE is null");
			return (Criteria)this;
		}

		public Criteria andRequireTypeCodeIsNotNull(){
			addCriterion("REQUIRE_TYPE_CODE is not null");
			return (Criteria)this;
		}

		public Criteria andRequireTypeCodeEqualTo(BigDecimal value){
			addCriterion("REQUIRE_TYPE_CODE =",value,"requireTypeCode");
			return (Criteria)this;
		}

		public Criteria andRequireTypeCodeNotEqualTo(BigDecimal value){
			addCriterion("REQUIRE_TYPE_CODE <>",value,"requireTypeCode");
			return (Criteria)this;
		}

		public Criteria andRequireTypeCodeGreaterThan(BigDecimal value){
			addCriterion("REQUIRE_TYPE_CODE >",value,"requireTypeCode");
			return (Criteria)this;
		}

		public Criteria andRequireTypeCodeGreaterThanOrEqualTo(BigDecimal value){
			addCriterion("REQUIRE_TYPE_CODE >=",value,"requireTypeCode");
			return (Criteria)this;
		}

		public Criteria andRequireTypeCodeLessThan(BigDecimal value){
			addCriterion("REQUIRE_TYPE_CODE <",value,"requireTypeCode");
			return (Criteria)this;
		}

		public Criteria andRequireTypeCodeLessThanOrEqualTo(BigDecimal value){
			addCriterion("REQUIRE_TYPE_CODE <=",value,"requireTypeCode");
			return (Criteria)this;
		}

		public Criteria andRequireTypeCodeIn(List<BigDecimal> values){
			addCriterion("REQUIRE_TYPE_CODE in",values,"requireTypeCode");
			return (Criteria)this;
		}

		public Criteria andRequireTypeCodeNotIn(List<BigDecimal> values){
			addCriterion("REQUIRE_TYPE_CODE not in",values,"requireTypeCode");
			return (Criteria)this;
		}

		public Criteria andRequireTypeCodeBetween(BigDecimal value1,
				BigDecimal value2){
			addCriterion("REQUIRE_TYPE_CODE between",value1,value2,
					"requireTypeCode");
			return (Criteria)this;
		}

		public Criteria andRequireTypeCodeNotBetween(BigDecimal value1,
				BigDecimal value2){
			addCriterion("REQUIRE_TYPE_CODE not between",value1,value2,
					"requireTypeCode");
			return (Criteria)this;
		}

		public Criteria andRequireTypeNameIsNull(){
			addCriterion("REQUIRE_TYPE_NAME is null");
			return (Criteria)this;
		}

		public Criteria andRequireTypeNameIsNotNull(){
			addCriterion("REQUIRE_TYPE_NAME is not null");
			return (Criteria)this;
		}

		public Criteria andRequireTypeNameEqualTo(String value){
			addCriterion("REQUIRE_TYPE_NAME =",value,"requireTypeName");
			return (Criteria)this;
		}

		public Criteria andRequireTypeNameNotEqualTo(String value){
			addCriterion("REQUIRE_TYPE_NAME <>",value,"requireTypeName");
			return (Criteria)this;
		}

		public Criteria andRequireTypeNameGreaterThan(String value){
			addCriterion("REQUIRE_TYPE_NAME >",value,"requireTypeName");
			return (Criteria)this;
		}

		public Criteria andRequireTypeNameGreaterThanOrEqualTo(String value){
			addCriterion("REQUIRE_TYPE_NAME >=",value,"requireTypeName");
			return (Criteria)this;
		}

		public Criteria andRequireTypeNameLessThan(String value){
			addCriterion("REQUIRE_TYPE_NAME <",value,"requireTypeName");
			return (Criteria)this;
		}

		public Criteria andRequireTypeNameLessThanOrEqualTo(String value){
			addCriterion("REQUIRE_TYPE_NAME <=",value,"requireTypeName");
			return (Criteria)this;
		}

		public Criteria andRequireTypeNameLike(String value){
			addCriterion("REQUIRE_TYPE_NAME like",value,"requireTypeName");
			return (Criteria)this;
		}

		public Criteria andRequireTypeNameNotLike(String value){
			addCriterion("REQUIRE_TYPE_NAME not like",value,"requireTypeName");
			return (Criteria)this;
		}

		public Criteria andRequireTypeNameIn(List<String> values){
			addCriterion("REQUIRE_TYPE_NAME in",values,"requireTypeName");
			return (Criteria)this;
		}

		public Criteria andRequireTypeNameNotIn(List<String> values){
			addCriterion("REQUIRE_TYPE_NAME not in",values,"requireTypeName");
			return (Criteria)this;
		}

		public Criteria andRequireTypeNameBetween(String value1,String value2){
			addCriterion("REQUIRE_TYPE_NAME between",value1,value2,
					"requireTypeName");
			return (Criteria)this;
		}

		public Criteria andRequireTypeNameNotBetween(String value1,String value2){
			addCriterion("REQUIRE_TYPE_NAME not between",value1,value2,
					"requireTypeName");
			return (Criteria)this;
		}

		public Criteria andRequireTypeDescIsNull(){
			addCriterion("REQUIRE_TYPE_DESC is null");
			return (Criteria)this;
		}

		public Criteria andRequireTypeDescIsNotNull(){
			addCriterion("REQUIRE_TYPE_DESC is not null");
			return (Criteria)this;
		}

		public Criteria andRequireTypeDescEqualTo(String value){
			addCriterion("REQUIRE_TYPE_DESC =",value,"requireTypeDesc");
			return (Criteria)this;
		}

		public Criteria andRequireTypeDescNotEqualTo(String value){
			addCriterion("REQUIRE_TYPE_DESC <>",value,"requireTypeDesc");
			return (Criteria)this;
		}

		public Criteria andRequireTypeDescGreaterThan(String value){
			addCriterion("REQUIRE_TYPE_DESC >",value,"requireTypeDesc");
			return (Criteria)this;
		}

		public Criteria andRequireTypeDescGreaterThanOrEqualTo(String value){
			addCriterion("REQUIRE_TYPE_DESC >=",value,"requireTypeDesc");
			return (Criteria)this;
		}

		public Criteria andRequireTypeDescLessThan(String value){
			addCriterion("REQUIRE_TYPE_DESC <",value,"requireTypeDesc");
			return (Criteria)this;
		}

		public Criteria andRequireTypeDescLessThanOrEqualTo(String value){
			addCriterion("REQUIRE_TYPE_DESC <=",value,"requireTypeDesc");
			return (Criteria)this;
		}

		public Criteria andRequireTypeDescLike(String value){
			addCriterion("REQUIRE_TYPE_DESC like",value,"requireTypeDesc");
			return (Criteria)this;
		}

		public Criteria andRequireTypeDescNotLike(String value){
			addCriterion("REQUIRE_TYPE_DESC not like",value,"requireTypeDesc");
			return (Criteria)this;
		}

		public Criteria andRequireTypeDescIn(List<String> values){
			addCriterion("REQUIRE_TYPE_DESC in",values,"requireTypeDesc");
			return (Criteria)this;
		}

		public Criteria andRequireTypeDescNotIn(List<String> values){
			addCriterion("REQUIRE_TYPE_DESC not in",values,"requireTypeDesc");
			return (Criteria)this;
		}

		public Criteria andRequireTypeDescBetween(String value1,String value2){
			addCriterion("REQUIRE_TYPE_DESC between",value1,value2,
					"requireTypeDesc");
			return (Criteria)this;
		}

		public Criteria andRequireTypeDescNotBetween(String value1,String value2){
			addCriterion("REQUIRE_TYPE_DESC not between",value1,value2,
					"requireTypeDesc");
			return (Criteria)this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	public static class Criterion {
		private String	condition;
		private Object	value;
		private Object	secondValue;
		private boolean	noValue;
		private boolean	singleValue;
		private boolean	betweenValue;
		private boolean	listValue;
		private String	typeHandler;

		public String getCondition(){
			return condition;
		}

		public Object getValue(){
			return value;
		}

		public Object getSecondValue(){
			return secondValue;
		}

		public boolean isNoValue(){
			return noValue;
		}

		public boolean isSingleValue(){
			return singleValue;
		}

		public boolean isBetweenValue(){
			return betweenValue;
		}

		public boolean isListValue(){
			return listValue;
		}

		public String getTypeHandler(){
			return typeHandler;
		}

		protected Criterion(String condition){
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition,Object value,String typeHandler){
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if(value instanceof List<?>){
				this.listValue = true;
			} else{
				this.singleValue = true;
			}
		}

		protected Criterion(String condition,Object value){
			this(condition,value,null);
		}

		protected Criterion(String condition,Object value,Object secondValue,
				String typeHandler){
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition,Object value,Object secondValue){
			this(condition,value,secondValue,null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table REQUIRE_TYPE
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}