package cn.com.chinatelecom.pms.pojo;

public class RequireEffect {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIRE_EFFECT.REQUIRE_EFFECT_ID
	 * @mbggenerated
	 */
	private String	requireEffectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIRE_EFFECT.MODULE_ID
	 * @mbggenerated
	 */
	private String	moduleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIRE_EFFECT.EFFECT_PROCESS_ID
	 * @mbggenerated
	 */
	private String	effectProcessId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIRE_EFFECT.REQUIRE_EFFECT_VERSIONS
	 * @mbggenerated
	 */
	private String	requireEffectVersions;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIRE_EFFECT.STAGE_ID
	 * @mbggenerated
	 */
	private String	stageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REQUIRE_EFFECT.REQUIRE_EFFECT_COMMENT
	 * @mbggenerated
	 */
	private String	requireEffectComment;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIRE_EFFECT.REQUIRE_EFFECT_ID
	 * @return  the value of REQUIRE_EFFECT.REQUIRE_EFFECT_ID
	 * @mbggenerated
	 */
	public String getRequireEffectId(){
		return requireEffectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIRE_EFFECT.REQUIRE_EFFECT_ID
	 * @param requireEffectId  the value for REQUIRE_EFFECT.REQUIRE_EFFECT_ID
	 * @mbggenerated
	 */
	public void setRequireEffectId(String requireEffectId){
		this.requireEffectId = requireEffectId==null ? null : requireEffectId
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIRE_EFFECT.MODULE_ID
	 * @return  the value of REQUIRE_EFFECT.MODULE_ID
	 * @mbggenerated
	 */
	public String getModuleId(){
		return moduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIRE_EFFECT.MODULE_ID
	 * @param moduleId  the value for REQUIRE_EFFECT.MODULE_ID
	 * @mbggenerated
	 */
	public void setModuleId(String moduleId){
		this.moduleId = moduleId==null ? null : moduleId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIRE_EFFECT.EFFECT_PROCESS_ID
	 * @return  the value of REQUIRE_EFFECT.EFFECT_PROCESS_ID
	 * @mbggenerated
	 */
	public String getEffectProcessId(){
		return effectProcessId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIRE_EFFECT.EFFECT_PROCESS_ID
	 * @param effectProcessId  the value for REQUIRE_EFFECT.EFFECT_PROCESS_ID
	 * @mbggenerated
	 */
	public void setEffectProcessId(String effectProcessId){
		this.effectProcessId = effectProcessId==null ? null : effectProcessId
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIRE_EFFECT.REQUIRE_EFFECT_VERSIONS
	 * @return  the value of REQUIRE_EFFECT.REQUIRE_EFFECT_VERSIONS
	 * @mbggenerated
	 */
	public String getRequireEffectVersions(){
		return requireEffectVersions;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIRE_EFFECT.REQUIRE_EFFECT_VERSIONS
	 * @param requireEffectVersions  the value for REQUIRE_EFFECT.REQUIRE_EFFECT_VERSIONS
	 * @mbggenerated
	 */
	public void setRequireEffectVersions(String requireEffectVersions){
		this.requireEffectVersions = requireEffectVersions==null ? null
				: requireEffectVersions.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIRE_EFFECT.STAGE_ID
	 * @return  the value of REQUIRE_EFFECT.STAGE_ID
	 * @mbggenerated
	 */
	public String getStageId(){
		return stageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIRE_EFFECT.STAGE_ID
	 * @param stageId  the value for REQUIRE_EFFECT.STAGE_ID
	 * @mbggenerated
	 */
	public void setStageId(String stageId){
		this.stageId = stageId==null ? null : stageId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REQUIRE_EFFECT.REQUIRE_EFFECT_COMMENT
	 * @return  the value of REQUIRE_EFFECT.REQUIRE_EFFECT_COMMENT
	 * @mbggenerated
	 */
	public String getRequireEffectComment(){
		return requireEffectComment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REQUIRE_EFFECT.REQUIRE_EFFECT_COMMENT
	 * @param requireEffectComment  the value for REQUIRE_EFFECT.REQUIRE_EFFECT_COMMENT
	 * @mbggenerated
	 */
	public void setRequireEffectComment(String requireEffectComment){
		this.requireEffectComment = requireEffectComment==null ? null
				: requireEffectComment.trim();
	}
}