package cn.com.chinatelecom.pms.pojo;

import java.util.ArrayList;
import java.util.List;

public class RequireEffectExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	protected String	orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	protected boolean	distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	protected List<Criteria>	oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	public RequireEffectExample(){
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause){
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	public String getOrderByClause(){
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct){
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	public boolean isDistinct(){
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria(){
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	public void or(Criteria criteria){
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	public Criteria or(){
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	public Criteria createCriteria(){
		Criteria criteria = createCriteriaInternal();
		if(oredCriteria.size()==0){
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal(){
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	public void clear(){
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion>	criteria;

		protected GeneratedCriteria(){
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid(){
			return criteria.size()>0;
		}

		public List<Criterion> getAllCriteria(){
			return criteria;
		}

		public List<Criterion> getCriteria(){
			return criteria;
		}

		protected void addCriterion(String condition){
			if(condition==null){
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition,Object value,
				String property){
			if(value==null){
				throw new RuntimeException("Value for "+property
						+" cannot be null");
			}
			criteria.add(new Criterion(condition,value));
		}

		protected void addCriterion(String condition,Object value1,
				Object value2,String property){
			if(value1==null||value2==null){
				throw new RuntimeException("Between values for "+property
						+" cannot be null");
			}
			criteria.add(new Criterion(condition,value1,value2));
		}

		public Criteria andRequireEffectIdIsNull(){
			addCriterion("REQUIRE_EFFECT_ID is null");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdIsNotNull(){
			addCriterion("REQUIRE_EFFECT_ID is not null");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdEqualTo(String value){
			addCriterion("REQUIRE_EFFECT_ID =",value,"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdNotEqualTo(String value){
			addCriterion("REQUIRE_EFFECT_ID <>",value,"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdGreaterThan(String value){
			addCriterion("REQUIRE_EFFECT_ID >",value,"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdGreaterThanOrEqualTo(String value){
			addCriterion("REQUIRE_EFFECT_ID >=",value,"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdLessThan(String value){
			addCriterion("REQUIRE_EFFECT_ID <",value,"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdLessThanOrEqualTo(String value){
			addCriterion("REQUIRE_EFFECT_ID <=",value,"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdLike(String value){
			addCriterion("REQUIRE_EFFECT_ID like",value,"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdNotLike(String value){
			addCriterion("REQUIRE_EFFECT_ID not like",value,"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdIn(List<String> values){
			addCriterion("REQUIRE_EFFECT_ID in",values,"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdNotIn(List<String> values){
			addCriterion("REQUIRE_EFFECT_ID not in",values,"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdBetween(String value1,String value2){
			addCriterion("REQUIRE_EFFECT_ID between",value1,value2,
					"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectIdNotBetween(String value1,String value2){
			addCriterion("REQUIRE_EFFECT_ID not between",value1,value2,
					"requireEffectId");
			return (Criteria)this;
		}

		public Criteria andModuleIdIsNull(){
			addCriterion("MODULE_ID is null");
			return (Criteria)this;
		}

		public Criteria andModuleIdIsNotNull(){
			addCriterion("MODULE_ID is not null");
			return (Criteria)this;
		}

		public Criteria andModuleIdEqualTo(String value){
			addCriterion("MODULE_ID =",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdNotEqualTo(String value){
			addCriterion("MODULE_ID <>",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdGreaterThan(String value){
			addCriterion("MODULE_ID >",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdGreaterThanOrEqualTo(String value){
			addCriterion("MODULE_ID >=",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdLessThan(String value){
			addCriterion("MODULE_ID <",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdLessThanOrEqualTo(String value){
			addCriterion("MODULE_ID <=",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdLike(String value){
			addCriterion("MODULE_ID like",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdNotLike(String value){
			addCriterion("MODULE_ID not like",value,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdIn(List<String> values){
			addCriterion("MODULE_ID in",values,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdNotIn(List<String> values){
			addCriterion("MODULE_ID not in",values,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdBetween(String value1,String value2){
			addCriterion("MODULE_ID between",value1,value2,"moduleId");
			return (Criteria)this;
		}

		public Criteria andModuleIdNotBetween(String value1,String value2){
			addCriterion("MODULE_ID not between",value1,value2,"moduleId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdIsNull(){
			addCriterion("EFFECT_PROCESS_ID is null");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdIsNotNull(){
			addCriterion("EFFECT_PROCESS_ID is not null");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdEqualTo(String value){
			addCriterion("EFFECT_PROCESS_ID =",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdNotEqualTo(String value){
			addCriterion("EFFECT_PROCESS_ID <>",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdGreaterThan(String value){
			addCriterion("EFFECT_PROCESS_ID >",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdGreaterThanOrEqualTo(String value){
			addCriterion("EFFECT_PROCESS_ID >=",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdLessThan(String value){
			addCriterion("EFFECT_PROCESS_ID <",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdLessThanOrEqualTo(String value){
			addCriterion("EFFECT_PROCESS_ID <=",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdLike(String value){
			addCriterion("EFFECT_PROCESS_ID like",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdNotLike(String value){
			addCriterion("EFFECT_PROCESS_ID not like",value,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdIn(List<String> values){
			addCriterion("EFFECT_PROCESS_ID in",values,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdNotIn(List<String> values){
			addCriterion("EFFECT_PROCESS_ID not in",values,"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdBetween(String value1,String value2){
			addCriterion("EFFECT_PROCESS_ID between",value1,value2,
					"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andEffectProcessIdNotBetween(String value1,String value2){
			addCriterion("EFFECT_PROCESS_ID not between",value1,value2,
					"effectProcessId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectVersionsIsNull(){
			addCriterion("REQUIRE_EFFECT_VERSIONS is null");
			return (Criteria)this;
		}

		public Criteria andRequireEffectVersionsIsNotNull(){
			addCriterion("REQUIRE_EFFECT_VERSIONS is not null");
			return (Criteria)this;
		}

		public Criteria andRequireEffectVersionsEqualTo(String value){
			addCriterion("REQUIRE_EFFECT_VERSIONS =",value,
					"requireEffectVersions");
			return (Criteria)this;
		}

		public Criteria andRequireEffectVersionsNotEqualTo(String value){
			addCriterion("REQUIRE_EFFECT_VERSIONS <>",value,
					"requireEffectVersions");
			return (Criteria)this;
		}

		public Criteria andRequireEffectVersionsGreaterThan(String value){
			addCriterion("REQUIRE_EFFECT_VERSIONS >",value,
					"requireEffectVersions");
			return (Criteria)this;
		}

		public Criteria andRequireEffectVersionsGreaterThanOrEqualTo(
				String value){
			addCriterion("REQUIRE_EFFECT_VERSIONS >=",value,
					"requireEffectVersions");
			return (Criteria)this;
		}

		public Criteria andRequireEffectVersionsLessThan(String value){
			addCriterion("REQUIRE_EFFECT_VERSIONS <",value,
					"requireEffectVersions");
			return (Criteria)this;
		}

		public Criteria andRequireEffectVersionsLessThanOrEqualTo(String value){
			addCriterion("REQUIRE_EFFECT_VERSIONS <=",value,
					"requireEffectVersions");
			return (Criteria)this;
		}

		public Criteria andRequireEffectVersionsLike(String value){
			addCriterion("REQUIRE_EFFECT_VERSIONS like",value,
					"requireEffectVersions");
			return (Criteria)this;
		}

		public Criteria andRequireEffectVersionsNotLike(String value){
			addCriterion("REQUIRE_EFFECT_VERSIONS not like",value,
					"requireEffectVersions");
			return (Criteria)this;
		}

		public Criteria andRequireEffectVersionsIn(List<String> values){
			addCriterion("REQUIRE_EFFECT_VERSIONS in",values,
					"requireEffectVersions");
			return (Criteria)this;
		}

		public Criteria andRequireEffectVersionsNotIn(List<String> values){
			addCriterion("REQUIRE_EFFECT_VERSIONS not in",values,
					"requireEffectVersions");
			return (Criteria)this;
		}

		public Criteria andRequireEffectVersionsBetween(String value1,
				String value2){
			addCriterion("REQUIRE_EFFECT_VERSIONS between",value1,value2,
					"requireEffectVersions");
			return (Criteria)this;
		}

		public Criteria andRequireEffectVersionsNotBetween(String value1,
				String value2){
			addCriterion("REQUIRE_EFFECT_VERSIONS not between",value1,value2,
					"requireEffectVersions");
			return (Criteria)this;
		}

		public Criteria andStageIdIsNull(){
			addCriterion("STAGE_ID is null");
			return (Criteria)this;
		}

		public Criteria andStageIdIsNotNull(){
			addCriterion("STAGE_ID is not null");
			return (Criteria)this;
		}

		public Criteria andStageIdEqualTo(String value){
			addCriterion("STAGE_ID =",value,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdNotEqualTo(String value){
			addCriterion("STAGE_ID <>",value,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdGreaterThan(String value){
			addCriterion("STAGE_ID >",value,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdGreaterThanOrEqualTo(String value){
			addCriterion("STAGE_ID >=",value,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdLessThan(String value){
			addCriterion("STAGE_ID <",value,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdLessThanOrEqualTo(String value){
			addCriterion("STAGE_ID <=",value,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdLike(String value){
			addCriterion("STAGE_ID like",value,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdNotLike(String value){
			addCriterion("STAGE_ID not like",value,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdIn(List<String> values){
			addCriterion("STAGE_ID in",values,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdNotIn(List<String> values){
			addCriterion("STAGE_ID not in",values,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdBetween(String value1,String value2){
			addCriterion("STAGE_ID between",value1,value2,"stageId");
			return (Criteria)this;
		}

		public Criteria andStageIdNotBetween(String value1,String value2){
			addCriterion("STAGE_ID not between",value1,value2,"stageId");
			return (Criteria)this;
		}

		public Criteria andRequireEffectCommentIsNull(){
			addCriterion("REQUIRE_EFFECT_COMMENT is null");
			return (Criteria)this;
		}

		public Criteria andRequireEffectCommentIsNotNull(){
			addCriterion("REQUIRE_EFFECT_COMMENT is not null");
			return (Criteria)this;
		}

		public Criteria andRequireEffectCommentEqualTo(String value){
			addCriterion("REQUIRE_EFFECT_COMMENT =",value,
					"requireEffectComment");
			return (Criteria)this;
		}

		public Criteria andRequireEffectCommentNotEqualTo(String value){
			addCriterion("REQUIRE_EFFECT_COMMENT <>",value,
					"requireEffectComment");
			return (Criteria)this;
		}

		public Criteria andRequireEffectCommentGreaterThan(String value){
			addCriterion("REQUIRE_EFFECT_COMMENT >",value,
					"requireEffectComment");
			return (Criteria)this;
		}

		public Criteria andRequireEffectCommentGreaterThanOrEqualTo(String value){
			addCriterion("REQUIRE_EFFECT_COMMENT >=",value,
					"requireEffectComment");
			return (Criteria)this;
		}

		public Criteria andRequireEffectCommentLessThan(String value){
			addCriterion("REQUIRE_EFFECT_COMMENT <",value,
					"requireEffectComment");
			return (Criteria)this;
		}

		public Criteria andRequireEffectCommentLessThanOrEqualTo(String value){
			addCriterion("REQUIRE_EFFECT_COMMENT <=",value,
					"requireEffectComment");
			return (Criteria)this;
		}

		public Criteria andRequireEffectCommentLike(String value){
			addCriterion("REQUIRE_EFFECT_COMMENT like",value,
					"requireEffectComment");
			return (Criteria)this;
		}

		public Criteria andRequireEffectCommentNotLike(String value){
			addCriterion("REQUIRE_EFFECT_COMMENT not like",value,
					"requireEffectComment");
			return (Criteria)this;
		}

		public Criteria andRequireEffectCommentIn(List<String> values){
			addCriterion("REQUIRE_EFFECT_COMMENT in",values,
					"requireEffectComment");
			return (Criteria)this;
		}

		public Criteria andRequireEffectCommentNotIn(List<String> values){
			addCriterion("REQUIRE_EFFECT_COMMENT not in",values,
					"requireEffectComment");
			return (Criteria)this;
		}

		public Criteria andRequireEffectCommentBetween(String value1,
				String value2){
			addCriterion("REQUIRE_EFFECT_COMMENT between",value1,value2,
					"requireEffectComment");
			return (Criteria)this;
		}

		public Criteria andRequireEffectCommentNotBetween(String value1,
				String value2){
			addCriterion("REQUIRE_EFFECT_COMMENT not between",value1,value2,
					"requireEffectComment");
			return (Criteria)this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	public static class Criterion {
		private String	condition;
		private Object	value;
		private Object	secondValue;
		private boolean	noValue;
		private boolean	singleValue;
		private boolean	betweenValue;
		private boolean	listValue;
		private String	typeHandler;

		public String getCondition(){
			return condition;
		}

		public Object getValue(){
			return value;
		}

		public Object getSecondValue(){
			return secondValue;
		}

		public boolean isNoValue(){
			return noValue;
		}

		public boolean isSingleValue(){
			return singleValue;
		}

		public boolean isBetweenValue(){
			return betweenValue;
		}

		public boolean isListValue(){
			return listValue;
		}

		public String getTypeHandler(){
			return typeHandler;
		}

		protected Criterion(String condition){
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition,Object value,String typeHandler){
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if(value instanceof List<?>){
				this.listValue = true;
			} else{
				this.singleValue = true;
			}
		}

		protected Criterion(String condition,Object value){
			this(condition,value,null);
		}

		protected Criterion(String condition,Object value,Object secondValue,
				String typeHandler){
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition,Object value,Object secondValue){
			this(condition,value,secondValue,null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table REQUIRE_EFFECT
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}