package cn.com.chinatelecom.pms.dao;

import cn.com.chinatelecom.pms.pojo.EffectAction;
import cn.com.chinatelecom.pms.pojo.EffectActionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EffectActionMapper {
	
	String getNameById(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    int countByExample(EffectActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    int deleteByExample(EffectActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String effectActionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    int insert(EffectAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    int insertSelective(EffectAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    List<EffectAction> selectByExample(EffectActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    EffectAction selectByPrimaryKey(String effectActionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EffectAction record, @Param("example") EffectActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EffectAction record, @Param("example") EffectActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EffectAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EFFECT_ACTION
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EffectAction record);
}