package cn.com.chinatelecom.pms.dao;

import cn.com.chinatelecom.pms.pojo.EffectProcess;
import cn.com.chinatelecom.pms.pojo.EffectProcessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EffectProcessMapper {

	String getNameById(String id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	int countByExample(EffectProcessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	int deleteByExample(EffectProcessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String effectProcessId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	int insert(EffectProcess record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	int insertSelective(EffectProcess record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	List<EffectProcess> selectByExample(EffectProcessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	EffectProcess selectByPrimaryKey(String effectProcessId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record")
	EffectProcess record,@Param("example")
	EffectProcessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	int updateByExample(@Param("record")
	EffectProcess record,@Param("example")
	EffectProcessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(EffectProcess record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EFFECT_PROCESS
	 * @mbggenerated
	 */
	int updateByPrimaryKey(EffectProcess record);
}