package cn.com.chinatelecom.pms.dao;

import cn.com.chinatelecom.pms.pojo.ExecuteOrg;
import cn.com.chinatelecom.pms.pojo.ExecuteOrgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExecuteOrgMapper {
	
	String getNameById(String id);
	
	List<ExecuteOrg> selectAllExecuteOrg();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	int countByExample(ExecuteOrgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	int deleteByExample(ExecuteOrgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String executeOrgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	int insert(ExecuteOrg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	int insertSelective(ExecuteOrg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	List<ExecuteOrg> selectByExample(ExecuteOrgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	ExecuteOrg selectByPrimaryKey(String executeOrgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record")
	ExecuteOrg record,@Param("example")
	ExecuteOrgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	int updateByExample(@Param("record")
	ExecuteOrg record,@Param("example")
	ExecuteOrgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ExecuteOrg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EXECUTE_ORG
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ExecuteOrg record);
}