package cn.com.chinatelecom.pms.dao;

import cn.com.chinatelecom.pms.pojo.Members;
import cn.com.chinatelecom.pms.pojo.MembersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MembersMapper {
	List<Members> selectAllMember();
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	int countByExample(MembersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	int deleteByExample(MembersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String memberId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	int insert(Members record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	int insertSelective(Members record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	List<Members> selectByExample(MembersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	Members selectByPrimaryKey(String memberId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record")
	Members record,@Param("example")
	MembersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	int updateByExample(@Param("record")
	Members record,@Param("example")
	MembersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Members record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEMBERS
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Members record);

	
}