package cn.com.chinatelecom.pms.dao;

import cn.com.chinatelecom.pms.pojo.Module;
import cn.com.chinatelecom.pms.pojo.ModuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ModuleMapper {
	
	String getNameById(String id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	int countByExample(ModuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	int deleteByExample(ModuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String moduleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	int insert(Module record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	int insertSelective(Module record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	List<Module> selectByExample(ModuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	Module selectByPrimaryKey(String moduleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record")
	Module record,@Param("example")
	ModuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	int updateByExample(@Param("record")
	Module record,@Param("example")
	ModuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Module record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Module record);

	List<Module> selectAllModule();
}