package cn.com.chinatelecom.pms.dao;

import cn.com.chinatelecom.pms.pojo.OperationLogs;
import cn.com.chinatelecom.pms.pojo.OperationLogsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperationLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECT_OPERATION_LOGS
     *
     * @mbggenerated
     */
    int countByExample(OperationLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECT_OPERATION_LOGS
     *
     * @mbggenerated
     */
    int deleteByExample(OperationLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECT_OPERATION_LOGS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECT_OPERATION_LOGS
     *
     * @mbggenerated
     */
    int insert(OperationLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECT_OPERATION_LOGS
     *
     * @mbggenerated
     */
    int insertSelective(OperationLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECT_OPERATION_LOGS
     *
     * @mbggenerated
     */
    List<OperationLogs> selectByExampleWithBLOBs(OperationLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECT_OPERATION_LOGS
     *
     * @mbggenerated
     */
    List<OperationLogs> selectByExample(OperationLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECT_OPERATION_LOGS
     *
     * @mbggenerated
     */
    OperationLogs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECT_OPERATION_LOGS
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OperationLogs record, @Param("example") OperationLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECT_OPERATION_LOGS
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") OperationLogs record, @Param("example") OperationLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECT_OPERATION_LOGS
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OperationLogs record, @Param("example") OperationLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECT_OPERATION_LOGS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OperationLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECT_OPERATION_LOGS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(OperationLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECT_OPERATION_LOGS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OperationLogs record);
}