package cn.com.chinatelecom.pms.dao;

import cn.com.chinatelecom.pms.pojo.Process;
import cn.com.chinatelecom.pms.pojo.ProcessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProcessMapper {

	List<Process> selectAllProcess();
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	int countByExample(ProcessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	int deleteByExample(ProcessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String processId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	int insert(Process record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	int insertSelective(Process record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	List<Process> selectByExample(ProcessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	Process selectByPrimaryKey(String processId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record")
	Process record,@Param("example")
	ProcessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	int updateByExample(@Param("record")
	Process record,@Param("example")
	ProcessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Process record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Process record);
}