package cn.com.chinatelecom.pms.dao;

import cn.com.chinatelecom.pms.pojo.RequireEffect;
import cn.com.chinatelecom.pms.pojo.RequireEffectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RequireEffectMapper {

	String getNameById(String id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	int countByExample(RequireEffectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	int deleteByExample(RequireEffectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String requireEffectId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	int insert(RequireEffect record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	int insertSelective(RequireEffect record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	List<RequireEffect> selectByExample(RequireEffectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	RequireEffect selectByPrimaryKey(String requireEffectId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record")
	RequireEffect record,@Param("example")
	RequireEffectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	int updateByExample(@Param("record")
	RequireEffect record,@Param("example")
	RequireEffectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(RequireEffect record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_EFFECT
	 * @mbggenerated
	 */
	int updateByPrimaryKey(RequireEffect record);
}