package cn.com.chinatelecom.pms.dao;

import cn.com.chinatelecom.pms.pojo.RequireKind;
import cn.com.chinatelecom.pms.pojo.RequireKindExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RequireKindMapper {
	
	String getNameById(String id);
	
	List<RequireKind> selectAllRequireKind();
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	int countByExample(RequireKindExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	int deleteByExample(RequireKindExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	int insert(RequireKind record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	int insertSelective(RequireKind record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	List<RequireKind> selectByExample(RequireKindExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record")
	RequireKind record,@Param("example")
	RequireKindExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_KIND
	 * @mbggenerated
	 */
	int updateByExample(@Param("record")
	RequireKind record,@Param("example")
	RequireKindExample example);

	
}