package cn.com.chinatelecom.pms.dao;

import cn.com.chinatelecom.pms.pojo.RequireType;
import cn.com.chinatelecom.pms.pojo.RequireTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RequireTypeMapper {
	
	String getNameById(String id);
	
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	int countByExample(RequireTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	int deleteByExample(RequireTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String requireTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	int insert(RequireType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	int insertSelective(RequireType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	List<RequireType> selectByExample(RequireTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	RequireType selectByPrimaryKey(String requireTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record")
	RequireType record,@Param("example")
	RequireTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	int updateByExample(@Param("record")
	RequireType record,@Param("example")
	RequireTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(RequireType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIRE_TYPE
	 * @mbggenerated
	 */
	int updateByPrimaryKey(RequireType record);

	List<RequireType> selectAllRequireType();
}