package cn.com.chinatelecom.pms.dao;

import cn.com.chinatelecom.pms.pojo.Requirement;
import cn.com.chinatelecom.pms.pojo.RequirementExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RequirementMapper {
	List<Requirement> selectAllRequirement();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	int countByExample(RequirementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	int deleteByExample(RequirementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	int insert(Requirement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	int insertSelective(Requirement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	List<Requirement> selectByExample(RequirementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record")
	Requirement record,@Param("example")
	RequirementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REQUIREMENT
	 * @mbggenerated
	 */
	int updateByExample(@Param("record")
	Requirement record,@Param("example")
	RequirementExample example);
}