package cn.com.chinatelecom.pms.dao;

import cn.com.chinatelecom.pms.pojo.RequirePriority;
import cn.com.chinatelecom.pms.pojo.RequirePriorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RequirePriorityMapper {
	List<RequirePriority> selectAllPriority();
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    int countByExample(RequirePriorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    int deleteByExample(RequirePriorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String priorityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    int insert(RequirePriority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    int insertSelective(RequirePriority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    List<RequirePriority> selectByExample(RequirePriorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    RequirePriority selectByPrimaryKey(String priorityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RequirePriority record, @Param("example") RequirePriorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RequirePriority record, @Param("example") RequirePriorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RequirePriority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REQUIRE_PRIORITY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RequirePriority record);
}